### ISSUE TITLE
Plan meeting time for Spring 2023

### ISSUE THREAD

**Issue by ahmad00m** [dondi/GRNsight#1009]
Please post here any unavailabilities outside of class time.

**Comment by Onariaginosa** [comment]
My schedule is my class schedule

**Comment by kdahlquist** [comment]
I am unavailable at the following times:
Mondays 1:00-2:00 (although this can possibly be moved)
Tuesdays 9:30-11:30, 12:00-1:30
Wednesdays 10:30-11:30
Thursdays 9:30-1:00
Fridays 3:00-5:00

**Comment by kdahlquist** [comment]
A reminder to @ahmad00m, @Sarronnn and @ntran18 to post any unavailability outside of your class schedule here so that we can plan our Spring meeting time.

**Comment by ahmad00m** [comment]
My only constraints are Mondays and Fridays from 8 am rot 4 pm and 9:50 to 11:40 on Thursdays.

**Comment by Sarronnn** [comment]
My constraints are Tuesdays, Thursdays from 9am-3:30pm and Fridays 2-5pm

**Comment by dondi** [comment]
Hello—after factoring class schedules and all of the constraints posted here, we have ended up with…count ’em, _one_ slot that has not been blocked out, and only partially: Wednesdays 11:30am–12:30pm!

The partial blockout is that I have class from 9:55–11:35am on MW, so I would be able to get to the meeting by 11:40am at the earliest

@ahmad00m just to be sure, the constraints that you listed above are for when you are _not_ available in addition to class times, is that right?

If anyone has any last-minute changes to their availability, please post when you can. Otherwise we are looking at Wednesdays 11:30am–12:30pm (and I would hop on ~11:40am)

**Comment by ahmad00m** [comment]
Yes, I will be working from 8-4 on Mondays and Fridays, so I'm unavailable during those times.

**Comment by Sarronnn** [comment]
Hi! I have class at 12:20pm on Wednesdays

**Comment by dondi** [comment]
Oh my you’re right—I mistranscribed that when reading off PROWL. It’s actually even tighter: 12:15pm

We might be forced to do the following then:
* Limit the all-hands meeting to ~30–40 minutes
* Hold separate meetings for more specific subgroups

**Comment by kdahlquist** [comment]
I can get the meeting started at 11:30.  We can work out the finer details when we meet this coming Wednesday.

**Comment by kdahlquist** [comment]
We found the "magic hour"!
