### ISSUE TITLE
protein-protein interaction UI refinements

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#1028]
@kdahlquist has reviewed this and edited this comment.

- [x] generate network modal should look the same as for the GRN, except change the labels
    - I think this is done
- [x] export to SIF and Excel, not graphml
    - [ ]  cell A1 of the exported Excel workbook "network" sheet; does not need to say "Cols regulators, rows targets", instead it should say "Cols protein1, rows protein2"
- [ ] <s>do not color boxes with expression data</s>  Upon reflection, this is more nuanced.  The _default_ is that there should be no node coloring.  However, if the user checks "Enable Node Coloring" either from the side panel or top menu, then it should behave as if it is a GRN.  This will be a change from the current behavior on beta 7.0.2

**Comment by dondi** [comment]
These are in the `beta` branch; also, there are multiple separate issues and based on the magnitude of the issues, one or more may be large enough to become its own issue
1. Initial assignment is both @nchun2 and @ntran18 in order to pair over learning about each issue and assessing them overall
2. Third item (node coloring of PPN) may need further consideration; can consult with @kdahlquist 
3. New issues or this issue can then be assigned directly to @ntran18 (or maybe paired)

**Comment by ntran18** [comment]
Because my schedule was tight last week, I couldn't meet with @nchun2 to do this issue. We plan to meet on Friday this week.

**Comment by dondi** [comment]
Now that @nchun2 also has GRNsight running locally, maybe @ntran18 and @nchun2 can try for this this week.

**Comment by dondi** [comment]
@ntran18 is traveling this week so it may not be feasible for @ntran18 and @nchun2 to do this together for this week; however if @nchun2’s queue reaches this, it will also be OK for her to look into it on her own and report back

**Comment by ntran18** [comment]
I didn't have time to schedule a meeting with @nchun2 so I checked this by myself. 

1. Not solved: "_cell A1 of the exported Excel workbook "network" sheet; does not need to say "Cols regulators, rows targets", instead it should say "Cols protein1, rows protein2"_"

- Example from demo 1:
  
<img width="1065" alt="image" src="https://github.com/dondi/GRNsight/assets/108908370/76f222e4-e80f-41ac-9ff8-52df46b29fe7">


2. For the third checklist (node coloring). I already see that feature in the version 7.0.2 beta. However, there is different options between the top menu and the side panel. 

- Side panel:
<img width="207" alt="image" src="https://github.com/dondi/GRNsight/assets/108908370/9807903a-d6ac-415e-9121-c1acbeced713">

- Top menu:
<img width="350" alt="image" src="https://github.com/dondi/GRNsight/assets/108908370/acdd85d9-d0c4-4390-bbd5-5bd79ff86af8">

--> Users can still select top data or bottom data from the top menu, not from the side panel.

**Comment by dondi** [comment]
After @ntran18’s triage, we can go ahead and split the issues; one for the Export (which appears to have a straightforward fix) and another for the node coloring coordination (which will need some deeper thinking because protein-to-protein requires additional integration into our existing UI)

This ticket can be closed after the two separate issues have been written up

**Comment by dondi** [comment]
@nchun2 can take on the error message issue after @ntran18 has extracted it; and possibly look at the protein-protein mode issue as well

**Comment by ntran18** [comment]
Created 2 new tickets for separated issues: #1054 and #1055
