### ISSUE TITLE
Get GRNsight running locally on your machine

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#1046]
Follow the Initial Setup wiki page: https://github.com/dondi/GRNsight/wiki/Initial-Setup

Take note of any inconsistencies/missing sections (e.g., Windows-specific variants) and we can edit the wiki page accordingly

**Comment by nchun2** [comment]
I don't want to make changes to the wiki page until I get confirmation for what I am doing, but while I was following the wiki some things came up and I will note them below so I don't forget. 

- Is there a specific postgres SGL that I should have downloaded? I downloaded 15 which seems to be working I think. 
- I had to specify a path in order for the psql command to work which was not in the documentation. 
- The sudo command does not work for Windows terminal. I used `runas` instead, but I don't know if that is a suitable replacement.
- Even when I tried to make a new password and a new user it says my password is incorrect. I have tried googling the issue and was not able to find a solution. I can't move on to further steps because the password is necessary, so I am stuck at this step.

**Comment by dondi** [comment]
- For postgres version, I don’t think we have established a fixed version yet; in general postgres historically has had excellent backward compatibility and the latest version typically suffices
    - We checked the server versions and got the following: `psql (14.6 (Ubuntu 14.6-0ubuntu0.22.04.1), server 11.19)`
    - So I think it’s safe to say that our minimum version is 11 but typically the latest version should also suffice
- Path comment—we may need to retrace to steps to work out the specifics that caused this comment; @nchun2 will look into this and update
    - It was noted that a lab notebook setup would help here, in order to be able to retrace steps when a lot of things are tried (e.g., OpenWetware)
    - @nchun2 followed a website—link will be posted so it can be reviewed
- The `runas` note is good—this should go to the wiki
- For the password question—this might be due to the way that there are now multiple passwords involved: your password as a user of the computer; the password as the owner of the postgres server; and finally the password to the database itself—this can be supplied offline

**Comment by nchun2** [comment]
I meet with @dondi  and we were able to get GRNsight running with a few tweaks to the documentation. 
- For Postgres to work I had to specify a path in the system environment variables of my laptop. In the Path environment I had to add 'C:\Program Files\PostgreSQL\15.4\bin\' and 'C:\Program Files\PostgreSQL\15.4\lib\' 
- When the -f is needed, it needs to be typed first in the command
- When I downloaded Postgre it prompted me for a password at the end of the installation process. This password corresponds to the password of the postgres user so whenever there is need for 'psql' you have to specify '-U postgres' right after so the password will be correct. 
- Windows uses the command 'py' or 'python' instead of 'python3'
- When I tried to run 'python generate_network.py' this error was given: ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'OpenSSL 1.1.0h  27 Mar 2018'. See: https://github.com/urllib3/urllib3/issues/2168 
        running 'pip install urllib3==1.26.6' fixed this
- A "UnicodeEncodeError" came up during the preprocessing step which was fixed with adding '-X utf8' to the command
- At the end when I tried to run Node this error was given: Error: error:0308010C:digital envelope routines::unsupported
         running '$env:NODE_OPTIONS="--openssl-legacy-provider"' fixed this

Dondi explained to me that these errors could be because I have a PC or because of my specific laptop so we don't know if these fixes are necessary to add to the documentation or if other issues would come up in the future. @kdahlquist If you have a lab laptop that I could borrow, he thinks it would be a good idea to run through the documentation again now with my notes, so we could make adjustments to the file for more detailed instructions that are PC specific.

**Comment by kdahlquist** [comment]
@nchun2, when did you want to work on this?  My laptop is at home, so I would need to bring it to work.  I might be able to swing by today and pick it up if you wanted to work today, but it would be easier to set a different day to work on this.  Let me know.

**Comment by nchun2** [comment]
@kdahlquist, sometime next week would work so you don't have to be rushing back and forth. Could I work on it Monday afternoon? I am free between 2 and 3:30 pm. I could also do Tuesday after our meeting because I don't begin class until 12 pm.

**Comment by kdahlquist** [comment]
Monday is fine.  I'll have to remember to bring it :)  Tuesday morning is the backup if I don't.

**Comment by kdahlquist** [comment]
I brought the laptop.  @nchun2 , I'll see you in my office at 2:00.

**Comment by dondi** [comment]
@nchun2 is in the middle of this process and taking notes along the way. Don’t hesitate to post screenshots to this thread in case you want to ask about something

The end goal is to see, after going through this installation procedure twice on different Windows machines, what variations/steps should be documented as part of the standard flow vs. what steps might be unique to specific machines and perhaps those steps can be listed in a side section (e.g., Troubleshooting or Notes)

**Comment by nchun2** [comment]
I have been trying to look for solutions to the following issue online, but I cannot find anything. @dondi do you know any solution to this? 
![Screenshot (1)](https://github.com/dondi/GRNsight/assets/122498296/b7778d62-0d21-483f-abb1-1bc9419cb022)
This is the last step, and up until now the issues have been similar.

**Comment by dondi** [comment]
I have been unable to find solid leads on this—there’s no reference to `options.cwd` in our code (that I could find). The closest thing I could spot is this issue from 2018, resolved in 2022 😮 https://github.com/nodejs/node/issues/22630

The discussion appears to hint that the issue is version-related, so the best I can think of is to double-check versions between the two machines to see if there are any mismatches

**Comment by nchun2** [comment]
@dondi I reinstalled Node so now both my computers and Dr. Dahlquist's are running the same version, but when I reran the command it gave me a new error (node:internal/modules/cjs/loader:1080 throw err;). I followed this website's guidelines (https://bobbyhadz.com/blog/javascript-cannot-find-module-loader-js) to fix it and I think it helped, but now I am getting the following error. 
![Screenshot (2)](https://github.com/dondi/GRNsight/assets/122498296/e9955ac2-7a0e-4ebb-ae33-3361f3758d6a)
![Screenshot (3)](https://github.com/dondi/GRNsight/assets/122498296/8361ee89-7e98-473a-83ec-3bf95cf7a727)
I checked online to find solutions, but I haven't been able to find anything useful.

**Comment by dondi** [comment]
@nchun2 the first error, `EADDRINUSE`, is very likely due to an existing GRNsight server that is already running on the machine. I would recommend looking at all of your command-line windows to make sure that there isn’t another one that’s still executing. If you can’t find one, go to the Task Manager (<kbd>Ctrl</kbd>-<kbd>Alt</kbd>-<kbd>Del</kbd>) and terminate any instances of _node_ that you might see

The second error about `google.analytics is not a function` may or may not be a side effect to the first one—let’s resolve `EADDRINUSE` first then see if the second one still shows up after that

**Comment by dondi** [comment]
To check the version of a command, add `--version` after the command name:

    node --version
    npm --version

**Comment by dondi** [comment]
If execution issues persist @nchun2 will arrange to meet up with @dondi so that they can troubleshoot the systems in person

**Comment by nchun2** [comment]
If you have an error installing google analysics, delete the node-modules folder from the GRNsight folder and then redo the npm install command. Make sure no instances of node are running during this from task manager. 

If you get the following error use < npm install --save-dev parallelshell@3.0.1>
TypeError [ERR_INVALID_ARG_TYPE]: The "options.cwd" property must be of type string or an instance of Buffer or URL. Received function wrappedCwd
    at normalizeSpawnArguments (node:child_process:576:11)
    at spawn (node:child_process:754:13)
    at C:\Users\kdahlqui\AppData\Roaming\npm\node_modules\parallelshell\index.js:104:17
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\Users\kdahlqui\AppData\Roaming\npm\node_modules\parallelshell\index.js:100:6)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12) {
  code: 'ERR_INVALID_ARG_TYPE'

Doing the above might cause the following: 
Error: Cannot find module 'C:\Users\kdahlqui\Desktop\GRNsight\node_modules\parallelshell\index.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []

This error could be fixed by deleting node-options from inside the GRNsight folder. Then call <npm update> and npm run start-dev should work
