### ISSUE TITLE
Disclaimer for lack of node-coloring PPI support

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#1071]
As a stopgap before working on #1068, we should include a disclaimer that we are displaying gene expression (mRNA-level data) and not protein-level data somewhere in the UI

**Comment by dondi** [comment]
Immediate task would be to prohibit changing the network mode for an existing graph because as of now, the change of mode makes the graph incorrect

Instead of disabling the dropdown, informational text in the style of the Species indicator should be used
* In the current framework this will require including both options in the markup but selectively hiding/unhiding the right one
* Future frameworks may be able to modify the app content dynamically, rendering or omitting the corresponding element as needed

**Comment by kdahlquist** [comment]
This issue is superseded by #1080 where we have decided to enable node coloring with PPI networks.  However, adding a warning may still be appropriate.  For example, when a PPI network is loaded, default to disable the node coloring, but allow the user to enable it.  When they enable it, a warning modal can appear that says "You are displaying mRNA-level expression data on a protein-protein interaction network."

In the future, we can consider allowing the user to upload protein-level expression data as an Excel workbook, but that is beyond the scope of this semester.

**Comment by dondi** [comment]
Closing since #1080 addresses this issue more fully
