### ISSUE TITLE
Update network database with new data from Intermine/SGD

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#1089]
It's becoming time to update the network backend database from Intermine/SGD.  Note that the previous versions were updated in 3/08/2022 and 3/07/2023, so targeting the beginning of March 2024 would keep us on track for yearly updates.

**Comment by kdahlquist** [comment]
Also the PPI database which was last updated 3/29/2023

**Comment by ntran18** [comment]
I found the script for updating the network backend but not for PPI. I will test my local database first and then update the production database. However, this task might not be finished before Tuesday's meeting.

**Comment by ntran18** [comment]
I don't know how to connect to production database. This is for network database, I'm able to get my local database updated

`DB_URL="postgresql://postgres:@https://grnsight.cs.lmu.edu/server/postgres" python3 generate_new_network_version.py
`
![image](https://github.com/dondi/GRNsight/assets/108908370/06a64bf2-5bd7-4f26-a897-24457c729f5d)
--> This error means I didn't provide the port?

`DB_URL="postgresql://postgres:@grnsight2.cfimp3lu6uob.us-west-1.rds.amazonaws.com/postgres" python3 generate_new_network_version.py`
![image](https://github.com/dondi/GRNsight/assets/108908370/fff5879b-382b-4cc6-9aa0-786a0a5b2e4b)

--> The arrow suggested that I didn't provide password

**Comment by dondi** [comment]
Yes I’ll have to recall how to do this 😅 …I suspect this will involve ssh tunneling

**Comment by dondi** [comment]
We’ll need to review the existing documentation for information about:
* Loading the production database
* Updating version information so that the new data set appears in addition to existing versions (2022/2023 for GRN; currently just 2023 for PPI)

Once we have this information ready (or possibly written if we don’t locate existing documentation), @dondi can sit with @ntran18, @ceciliazaragoza, and @akaiap to show them how to access the production database via ssh tunnel

**Comment by ntran18** [comment]
I updated the network database; however, protein-protein interaction still needs the script to update the network. The script for protein-protein interactions just downloads data from the internet and adds it to the table. If I populate new data to the data, it violates some genes already present in the table.

**Comment by dondi** [comment]
During a meeting with @ntran18 and @ceciliazaragoza, @dondi went over the process of creating an SSH tunnel in order to communicate with our production database server, which is within a private AWS network. This was how the production database got updated; further @ntran18 wrote up a wiki page documenting this technique: https://github.com/dondi/GRNsight/wiki/Database-Update-Instruction#update-network-database-in-production-database

**Comment by dondi** [comment]
@ntran18 will review where we left off here (looks like mainly a PPI question and not GRN) to determine next steps. However, we will not wait on this issue for a production release

**Comment by ntran18** [comment]
#1077 Have the instructions to update the database. I will have a session with @dondi to update the database, then the issue should be fixed.

**Comment by dondi** [comment]
Effectively updated the database as of v7.1.1 release
