### ISSUE TITLE
Importing new files has some delays

### ISSUE THREAD

**Issue by ntran18** [dondi/GRNsight#1098]
Importing new files has some delays. For example, if you load an error file and want to reload another file, it still shows the previous error file, which needs to be re-uploaded.

**Comment by ntran18** [comment]
I investigated this issue only in Chrome, not Safari. So the problem happens because of the web browser.

**Comment by dondi** [comment]
Verified that this is a Chrome-only issue (Firefox does not manifest the problem either)

However due to Chrome’s popularity, it will be worth tracing the specific divergent behavior that Chrome is manifesting which cases the file selector to appear twice. Once we pinpoint that, we can determine if there is a way to address the divergent behavior without also regressing the other browsers

**Comment by ntran18** [comment]
The root cause was that when the user clicks on "Select New File," it triggers ".upload".click(). But the class upload is bound to two Open File buttons: one in the sidebar and one at the top bar, which trigger the file selector twice.

**Comment by ntran18** [comment]
[Database Missing Info.xlsx](https://github.com/user-attachments/files/17739080/Database.Missing.Info.xlsx)

**Comment by dondi** [comment]
@ntran18 clarified how to replicate the issue and the fix was confirmed during the 11/13 meeting on beta 7.1.7
