### ISSUE TITLE
Rewrite spreadsheet controller based on new criteria for a valid adjacency matrix

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#151]
In order to have a solid error catching framework, we need a clear set of criteria that define when a raw .xlsx file contains a valid adjacency matrix.  Right now, the only "pre-flight" checks are for the existence of the "network" and/or "network_optimized_weights" sheets.  In the final version, these rules are simply two of a potentially more expansive set.

In code, we would then capture these rules as validator functions which would examine the raw parsed .xlsx for these criteria.  When a criterion fails, a corresponding error message is generated.  We still need the existing code in case we encounter an issue that we had not previously foreseen.

Overall, the checking framework would now have three layers:
1. The raw .xlsx parser (not our code): if this fails, then the uploaded file is not even a valid .xlsx to begin with, and we can bounce out right away with an error.
2. The parsed .xlsx, *prior* to turning it into a graph: this is where our criteria would be checked.  Right now, we are checking for errors *as we assemble* the graph; in this framework, we just check for conditions and do not yet try to build a graph data structure.
3. Building the graph data structure: this is where we have most of our error-checking code at the moment.  We can still keep this because this code will catch loopholes or unforeseen cases.  However, it is possible that some of the checkers here can move to layer 2.

**Comment by NAnguiano** [comment]
I went ahead and just found and verified all of the files I identified that would cause problems. The following files threw errors and did not load:
* missing-value-both-sheets-output.xlsx - Returns the error message "An unexpected error occured."
* missing-value-network-only-input.xlsx - Returns the same error

Those two threw the most obvious errors, as no graph loaded.
The files with the value replaced with a space display a repressor bar where the space was instead of ignoring it or throwing an error. These were the files:
* value-replaced-w-spaces-both-output.xlsx
* value-replaced-w-spaces-net-op-only-output.xlsx
* value-replaced–w-spaces-net-only-input.xlsx
* value-replaced–w-spaces-net-only-output.xlsx

I wasn't sure what the proper response was supposed to be for the files with the text data-type (the 12 files that start with text-data-type in the folder matrix-modifications), but they all appeared to display properly. @anuvarsh, could you verify that they are responding properly or improperly?

**Comment by NAnguiano** [comment]
I fixed the errors in missing-value-both-sheets-output.xlsx and missing-value-network-only-input.xlsx while changing formatting and clarifying wording in the spreadsheet controller, as I found that the place where the error in them occurs was not reporting errors properly. However, the remaining three files (extra-data-random-cell-both-output.xlsx, extra-data-random-cell-network-only-input.xlsx, and extra-data-random-cell-network-optimized-only-output.xlsx) still throw the error "An unexpected error occurred."

**Comment by kdahlquist** [comment]
Any further issues with particular spreadsheets are more properly their own issues, so we are going to close this now as it is done and moved to the master branch.
