### ISSUE TITLE
Documentation of test cases for new adjacency matrix requirements

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#156]
related to #151

**Comment by anuvarsh** [comment]
Unit test for all files of this type have been written and are passing.

**Comment by anuvarsh** [comment]
Accidentally closed this thread while closing all of the test case issues.

**Comment by anuvarsh** [comment]
@NAnguiano just found a bug in the spreadsheet controller of an instance where the genes were being compared as case sensitive, and it went uncaught for so long because there are no test-files for this situation. Asymmetric case for the same genes is one of the new test sheets that we need to make as a result the new spreadsheet controller.

**Comment by anuvarsh** [comment]
I updated the [Errors Glossary](https://github.com/dondi/GRNsight/wiki/Errors-Glossary) to include all of the current test files. I also tried to incorporate as many of the instructions that Dahlquist mentioned earlier in a list into this document, but I put everything into a table format so some things didn't apply. Please review and let me know what you think!

**Comment by anuvarsh** [comment]
I also went ahead and created a [Warnings Glossary](https://github.com/dondi/GRNsight/wiki/Warnings-Glossary) and added the code that already exists for it. I have yet to include any test files since we have not created test cases for warnings as of yet.

**Comment by kdahlquist** [comment]
I'm going to close this because I'm just not going to get to this. I'm labeling it with "backlog" to indicate I'll come back to it if I have time.
