### ISSUE TITLE
Review versions of libraries on which GRNsight depends

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#177]
Some time has passed from our initial use of libraries like `node-xlsx`, `express`, etc. It would be useful to look at compatibility with the latest versions of these libraries.

**Comment by kdahlquist** [comment]
Task sequence:
* Audit the `require` lines in the node JavaScript files to determine which 3rd party libraries we use for sure.
* Document these requirements on a wiki page.
* Update to the latest released versions of these libraries one by one.
* Test.
* Depending on result, decide what to do.

(rinse and repeat for the client side: jquery, d3, bootstrap, and whatever else we load via a `script` or `link` element on the actual app page)

**Comment by kdahlquist** [comment]
Investigate the use of a requirements file in node which helps set up a node environment automatically.

**Comment by NAnguiano** [comment]
We're not sure how to figure out what version of googleapis is being used.

Also this is a reminder to myself that I need to ask Dondi about the google analytics thing.

**Comment by NAnguiano** [comment]
Node-xlsx completely breaks everything if updated to the latest version (0.5.1). It fails all 53 tests.
Mocha updated without errors to version 2.2.5.
Multiparty updated without errors to version 4.1.2.
Cors updated without errors to version 2.6.0.
Chai updated without errors to version 2.3.0.
Stylus updated without errors to version 0.51.1.
Updating express made it so that neither server nor web-client apps could run. Trying to run either resulted in the following error:
>throw new Error('Most middleware (like ' + name + ') is no longer bundle
>            ^
>Error: Most middleware (like logger) is no longer bundled with Express and must be installed >separately. Please see https://github.com/senchalabs/connect#middleware.
>    at Function.Object.defineProperty.get (/Users/Melmel/Documents/GRNsight/node_modules/express/lib/express.js:89:13)
>    at Object.<anonymous> (/Users/Melmel/Documents/GRNsight/web-client/app.js:16:16)
>    at Module._compile (module.js:460:26)
>    at Object.Module._extensions..js (module.js:478:10)
>    at Module.load (module.js:355:32)
>    at Function.Module._load (module.js:310:12)
>    at Function.Module.runMain (module.js:501:10)
>    at startup (node.js:129:16)
>    at node.js:814:3

Jade updated without errors to version 1.10.0.

**Comment by NAnguiano** [comment]
[Here](https://github.com/dondi/GRNsight/wiki/Library-Requirements) is a wiki page with the current libraries and versions we are using.

**Comment by dondi** [comment]
You can use `npm list` to get a full dump of the NPM modules that you have installed at a given location. You will get an ASCII-level dependency tree showing the installed modules and their versions. When I do this on my copy, I get Google APIs version 1.1.1.

**Comment by dondi** [comment]
FWIW here is the GitHub site of that Google API library for Node: https://github.com/google/google-api-nodejs-client/

According to their [releases page](https://github.com/google/google-api-nodejs-client/releases), they are up to v2.0.4. Not sure if `npm install` will be in-sync with that though.

**Comment by dondi** [comment]
Agreed that moving to the latest node-xlsx and express versions can be done later due to immediate incompatibilities. For now, just download the latest versions that *will* work with GRNsight. Next step would be to see what the newest versions of these models provide; we can then decide if we should just freeze on a specific version, or plan on investing the time to achieve compatibility later.

**Comment by anuvarsh** [comment]
When gaining access of the servers, I realized that in addition to the libraries already mentioned on the wiki, Moment also needed to be installed. Luckily, the latest version of Moment works with GRNsight. The wiki was updated accordingly.

**Comment by kdahlquist** [comment]
@anuvarsh has verifed that a clean install of just the documented libraries and versions will get GRNsight running.  The current list is on the wiki. https://github.com/dondi/GRNsight/wiki/Library-Requirements

Suggestions:
* Put in code that actually installs the library.
*  instead of saying latest as of a certain date, look up the release dates of the versions you have up here.
*   Note different types of libraries, ones that break above a certain version versus not.
*   we need to decide on a timeline for when we check for updates.

When the wiki has been fixed up, put review requested and we'll close it after that.  We need to open new issues for node being broken #204 and for periodic library review at milestones in development (going from v1 to v2, for example, or on a yearly basis).

**Comment by anuvarsh** [comment]
I updated/added information about all of the libraries as mentioned in the previous comment. The only concern is that the version of Express that we are using actually predates their logging of releases on GitHub. I am going to try to do more digging, but as of now, I wrote that it was released before 3/4/2015.

**Comment by anuvarsh** [comment]
Google was helpful! The release date was found and amended on to the wiki. Reassigning for review.

**Comment by dondi** [comment]
Good and thorough here, a new dev shouldn't have a problem starting up now.
