### ISSUE TITLE
Establish glossary of errors, esp. explanations and suggestions

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#182]
Gather current errors in the code into a wiki page to serve the dual purpose of planning the entire space of errors and messages + supplying documentation for users.

**Comment by NAnguiano** [comment]
Initial version posted here: https://github.com/dondi/GRNsight/wiki/Errors-Glossary

**Comment by anuvarsh** [comment]
I updated the [Errors Glossary](https://github.com/dondi/GRNsight/wiki/Errors-Glossary) according to what @kdahlquist mentioned in #156.

I also went ahead and created a [Warnings Glossary](https://github.com/dondi/GRNsight/wiki/Warnings-Glossary) and added the code that already exists for it. I have yet to include any test files since we have not created test cases for warnings as of yet.

**Comment by anuvarsh** [comment]
Updated the "Error List in Code" section to a link that sends us straight to the actual errorList in the spreadsheet-controller.

**Comment by dondi** [comment]
Code list was updated; additional error cases were written on the blackboard. Follow-up tasks include:
* Transcription of comprehensive error list into the wiki
* Separate the error list into a distinct file, for `require` inclusion into _spreadsheet-controller.js_. This will also allow the wiki to link directly to it without depending on fragile line numbers.
(This is also in the spirit of issue #207)
* The "check color" constraint will initially be human-tested, but with the adoption of a browser-size testing framework, can be automated later

**Comment by kdahlquist** [comment]
I'm going to close this because I'm just not going to get to this. I'm labeling it with "backlog" to indicate I'll come back to it if I have time.
