### ISSUE TITLE
@NAnguiano will do code walk-through with @anuvarsh

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#190]
At the beginning of the summer @NAnguiano will do a code walk-through with @anuvarsh to get her up to speed on all the GRNsight code.  After the first two weeks of SURP, @anuvarsh will be taking over as the lead developer for the summer.

**Comment by kdahlquist** [comment]
As part of the walkthrough @NAnguiano should transfer control of the runtime server processes to @anuvarsh. (i.e., ssh, screen, node, environment settings, etc.)

**Comment by anuvarsh** [comment]
Nicole and I went through all of the code minus the .jade files because we assumed I wouldn't be going near those files this summer. If that is not the case, we can go back and look at them some time before she leaves. We also went through ssh and Nicole showed me how to restart the server. However, we are not going to pass the reigns until Nicole leaves on Thursday.

**Comment by kdahlquist** [comment]
Go ahead and go through the jade code just in case.

**Comment by NAnguiano** [comment]
I went ahead and went over the jade code with anu as well.

**Comment by NAnguiano** [comment]
Code walkthrough complete. Closing this up!
