### ISSUE TITLE
Display GRN metadata/statistics in green status bar

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#200]
- Number of nodes
- Number of edges
- Potentially other values

**Comment by dondi** [comment]
An initial attempt at this has been pushed to the beta branch. @anuvarsh please refresh the servers when you can so that @kdahlquist can take a look for Saturday. One question I had was whether to label the node counts as "nodes" or "genes." This issue says "nodes" but our demo files say "genes" and genes are what the nodes are anyway. In any case, once beta has been updated let me know how things are. Thanks!

**Comment by kdahlquist** [comment]
Let's have the label say "nodes".  While our demo files do indeed have genes in them, others might use GRNsight to visualize protein networks or even some other thing.  I think it's better to use the generic "nodes" here while our filename says genes because it is referring to genes.

**Comment by dondi** [comment]
OK, the label is just “nodes” now. Should be visible whenever an update is done on the live server.

**Comment by anuvarsh** [comment]
Just restarted the beta server, should be live on beta

**Comment by kdahlquist** [comment]
I like it!  I'm going to go ahead and close this.

**Comment by kdahlquist** [comment]
Actually, now I'm going to be a stickler and insist that you update the last modified date on the beta page, too.  :)

**Comment by dondi** [comment]
OK done :)

**Comment by kdahlquist** [comment]
verified and closing.
