### ISSUE TITLE
GRNsight *demo* uploads should not count at all, even the first time

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#201]
It appears that selections from the *Demo* menu are also counted, but only once (i.e., first time during a session). In actuality, even that one should not be counted at all.

**Comment by anuvarsh** [comment]
After uploading a series of Demo files, I have not been able to replicate the upload count behavior. The behavior may have been hypothesized because the activity monitor shows a bar for any and all activity on the website. Therefore, if someone just opens the website or switches tabs, the activity monitor shows a bar. It is possible that we may have been confusing a /GRNsight or /GRNsightbeta page hit as a demo file upload. 

I also went ahead and uploaded a series of regular networks from our data-samples folder and found that every upload was recorded on the activity monitor regardless of whether or not I refreshed the page, or how quickly I uploaded the file. 

However, I did notice that after uploading a file from our data-samples, Google Analytics thinks that 2 people are live on our website according to the activity monitor, while I am fairly certain this is not the case because both hits were from LA, and the activity matched the actions I was taking. If this is case, is it possible that we are falsely incrementing our page hits with our upload counter?

**Comment by dondi** [comment]
Yes, this is to be expected. Google has its own notion of a "user" when doing analytics; when someone does an upload, we are sort of doing a custom hit and so without knowing how Google internally represents a user, by default we "define" a new user when we record an upload.

**Comment by kdahlquist** [comment]
demo uploads don't appear to bump up the count. @anuvarsh tested this several times.  Since this is not an issue, we are closing
