### ISSUE TITLE
Separate test.js into smaller, more cohesive source files

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#207]
The overall test.js file has grown to a point where characteristics like common values for certain sets of files and a shared library of test helper functions would improve the quality of the code.

**Comment by anuvarsh** [comment]
The test.js sheet has been split into 5 separate files. The test.js file holds all of the functions that tests for different error codes. The other 4 files hold tests with test files according to the category that the file belongs to in the test-files folder. The test functions in test.js were made public so that the other sheets could access them.

**Comment by dondi** [comment]
Looks good! This becomes just on-going now where you should feel free to split things up again if they get large once more.
