### ISSUE TITLE
Time data type in matrix results in large network size error

### ISSUE THREAD

**Issue by anuvarsh** [dondi/GRNsight#211]
The test file adjacency-matrix-modifications/data-types/data-type-matrix-time-output.xlsx results in a network size error because the program reads 224 edges. I created a few more test files and the results were as follows:

data-type-matrix-time-output.xlsx: network size error with 15 genes and 224 edges.
data-type-matrix-time-input.xlsx: network size error with 15 genes and 225 edges.
data-type-matrix-time-single-cell-output.xlsx: 15 genes and 20 edges. Graph did not appear.

All test files are available in the beta branch.

**Comment by dondi** [comment]
The trick with this issue (as with issue #212) is that, *natively*, date and time values are actually still stored as numbers. Thus, it was not enough to convert them into numbers directly via `+`, because they are numbers to begin with. Instead, the trick was to turn them into a string first via `"" + cell`, and *then* try to convert that string into a number, `+("" + cell)`. The string conversion turns date and time stamps into dates and times, which *then* do not convert into numbers properly. With the above commit, all unit tests pass once more.

**Comment by dondi** [comment]
Oh also, I sort of invented some warning text for this type of issue. This will likely need some revision.

**Comment by anuvarsh** [comment]
I ran the unit tests and double checked on local host, and everything seems to be working great. This is now live on beta. Closing.
