### ISSUE TITLE
All negative weights results in black edges and colored blunt edges

### ISSUE THREAD

**Issue by anuvarsh** [dondi/GRNsight#213]
The graph-tests/all-negative-edges.xlsx resulted in the following graph:

![image](https://cloud.githubusercontent.com/assets/8509674/8172808/b68cae18-1379-11e5-81a5-52b3ffbdf7eb.png)

The sheet has 14 genes and 14 edges from -1 to -14. The edges appear to be black, not grey, and the ends appear cyan.

**Comment by kdahlquist** [comment]
Yikes!  I'm glad we checked :)

**Comment by dondi** [comment]
Just noting here so I don’t forget; this might be part of the issue:

https://github.com/dondi/GRNsight/blob/beta/web-client/public/js/graph.js#L52-L60

Note that the graph is considered “unweighted” if the maximum and minimum positive weights are the same. But if all of the weights are negative, then the graph *should* be weighted but it will not be labeled as such (because the “minimum” and “maximum” positive weights—both none—are the same).

Might be a part of the problem.

**Comment by anuvarsh** [comment]
After discussion with @kdahlquist, we decided that instead of just looking at the data within the sheet, we want the program to color the network based on the name of the sheet (i.e. The 'network' sheet should return a black network no matter what). This means that if we detect network optimized weights data in the network sheet we should return an error explaining that the network sheet has network optimized weights data. The other option is to display a warning that explains that the network sheet has network optimized weights data and display the graph without weights.

**Comment by dondi** [comment]
This looks fixed to me, given the above commit. "all-negative-*" files look correct to me; will need to verify.

**Comment by anuvarsh** [comment]
This was crossed checked with all of the "all-negative-*' files and it looks correct. Closing.
