### ISSUE TITLE
Catch localized representations of numbers in adjacency matrix

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#215]
Different regions will represent numbers differently; ideally GRNsight should be able to handle these transparently. Temporarily, we can report it as an error with a note that it might only be a number formatting issue.

**Comment by anuvarsh** [comment]
The error message has been put in place and is now live in beta. However, when adding this test, I noticed that the error messages count the rows/columns like arrays (starting at 0), while the average user would most likely count their rows and columns starting at 1. Because of this, when the error message says row 4, column 2, the average user will look at the wrong cell.

**Comment by anuvarsh** [comment]
I temporarily hard coded the error messages to number the rows and columns from 1.

**Comment by anuvarsh** [comment]
After talking to @kdahlquist, we decided to use the cell names according to Excel (i.e. C5) instead of row/column numbers when reporting errors. This change is now live on beta.

**Comment by anuvarsh** [comment]
Because the spreadsheet controller doesn't know what is "inside" the matrix and what is "outside", at the first instance of a NaN, it would return an error and not present the graph. Though this was helpful when we had NaN's "inside" the matrix, when the controller detects a NaN outside of the matrix it also returns an error and doesn't show the network despite the fact that there is no problem with the matrix (i.e. dCIN5GendronModel1.xlsx was failing to upload again). 

For this reason, I removed the NaN error completely, and just refactored the already established NaN/undefined warnings to return the cell number of the NaN. Because when there are special characters in a cell, xlsx treats them as special characters, I don't know how else to detect that there might be a number formatting issue.

**Comment by kdahlquist** [comment]
What happens if there is a NaN as a gene name?

**Comment by anuvarsh** [comment]
@kdahlquist There is a separate warning message for missing source/target genes that is returned prior to checking any matrix data.
