### ISSUE TITLE
Write SURP 2015 Abstract and PowerPoint Presentation

### ISSUE THREAD

**Issue by anuvarsh** [dondi/GRNsight#216]
Start it on the wiki. Explain what GRNsight is, but narrowly focus on what we accomplished over summer. 

Use one of the previously made GRNsight PowerPoints as a starting point, and update as necessary.

**Comment by anuvarsh** [comment]
The SURP abstract is available here: https://github.com/dondi/GRNsight/wiki/SURP-2015-Abstract

**Comment by anuvarsh** [comment]
I talked to Dr. Daniel Krause and he said we should aim for 250 words for the abstract.

**Comment by dondi** [comment]
Looks good to me :)

**Comment by kdahlquist** [comment]
I made some additional edits after @anuvarsh and I worked on it earlier.  I think it's basically done.  @dondi, will you please review again as it is different than what you last looked at.

**Comment by dondi** [comment]
I took a look and the increased emphasis on testing as the focus of SURP work is a really good improvement. I made a really small change (“a Chai” should be “the Chai” because it is a specific project and not a category of projects) but otherwise it is good to go (if it hasn't already gone). Presumably the slightly-above-250 word count will not be a problem.

**Comment by dondi** [comment]
Presumably we can close this when everything is submitted, so reassigning...

**Comment by anuvarsh** [comment]
The abstract is complete, and the PowerPoint presentations (the abridged and long versions) have been completed and are ready for tomorrows lab meeting!
