### ISSUE TITLE
Pageview counters displaying the wrong numbers

### ISSUE THREAD

**Issue by NAnguiano** [dondi/GRNsight#229]
The GRNsight Jekyll conversion has officially been pushed!

However, due to the way that Jekyll renders the static site, the pageview counters are now all displaying the same number on each page. This is because even though the files in the repo are identified as unique names (about.html, beta.html, etc), each file is actually being generated into a folder that contains an index.html. As a result of this, I believe the pageview counter is displaying the page views for index.html instead of each individual page.

**Comment by dondi** [comment]
Hmmmm, yes, we will want to maintain the prior URLs in order to keep the right Google Analytics counts. I think what is happening is that *new* counts have been started for the pages because they are now called _index.html_ (with corresponding path).

This is fine if we don't mind the counts being reset, but I think at this relatively early stage we want to maintain our prior counts. Thus, ideally we should go back to the _filename.html_ structure for our website.

As far as I know, with the right configuration this can be done with Jekyll. Check this page out, and look under the "Named HTML files" section. Follow whatever instructions you find for achieving that structure (which, as far as I can recall, was our original structure, yes?): http://jekyllrb.com/docs/pages/

Once the original structure comes back (i.e., _filename.html_ vs. _index.html_) then the counts should come back also.

**Comment by NAnguiano** [comment]
Yup, it just required a change in the configuration file to revert it back to the original file structure. The pageview counts have been restored for each of the pages.

**Comment by dondi** [comment]
Nice; the simple solutions are always best :)

**Comment by dondi** [comment]
One thing I've noticed—didn't the home and beta pages have upload counts, too? You'll need to find a way to have the footers inject that. Maybe use YML Front Matter or have those pages use a subclasses layout whose only difference is that added upload count element.

**Comment by NAnguiano** [comment]
Oh yep, they did. I just totally forgot to include those. I'll get those back in ASAP. Should be easy enough to do.

**Comment by NAnguiano** [comment]
Ok, the upload counters have been returned to the homepage and the beta page.

**Comment by dondi** [comment]
Examined and verified.
