### ISSUE TITLE
Submit proposal to 2016 NAR Web Server Issue

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#249]
The deadline for submission of a 1-page proposal for the 2016 NAR web server issue is December 31.  Instructions are on this page:

http://www.oxfordjournals.org/our_journals/nar/for_authors/submission_webserver.html

**Comment by kdahlquist** [comment]
@dondi , here is information that I need to complete the one-page summary.

* The number of passing unit tests.
* An estimate of the number of individuals outside of the authors' group who have been involved in the testing.  I have drafted this statement (we will just replace the dates and counts with the data you give me.  I think it's OK to have it be from today or thereabouts, even if I don't submit it until the deadline on Thursday):

The GRNsight server has been running since 20 March 2014.  The software has xxx passing unit tests.  A Google Analytics page view counter was implemented on 18 September 2014, and a file upload counter was added on 13 April 2015.  From these start dates and as of 28 December 2015, the GRNsight home page has been accessed 1811 times, and 1259 files have been uploaded and viewed with GRNsight.  Of these 1259 files, xxx were uploaded by users outside of our group.

* are there any academic citations for D3?  One of the requirements is "complete citations for previous publications of the method or the web server"
* could you comment on issue #250 regarding the privacy statement I drafted?

**Comment by kdahlquist** [comment]
I think I found the paper for D3:

http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=6064996&tag=1

Bostock, M., Ogievetsky, V., & Heer, J. (2011). D³ data-driven documents. Visualization and Computer Graphics, IEEE Transactions on Visualization and Computer Graphics, 17(12), 2301-2309. DOI: 10.1109/TVCG.2011.185

**Comment by kdahlquist** [comment]
Is this a good paper for Node.js?

http://sq4ya5rf2q.scholar.serialssolutions.com/?sid=google&auinit=S&aulast=Tilkov&atitle=Node.+js:+Using+JavaScript+to+build+high-performance+network+programs&id=doi:10.1109/MIC.2010.145

Tilkov, S., & Vinoski, S. (2010). Node. js: Using JavaScript to build high-performance network programs. IEEE Internet Computing, (6), 80-83. DOI: 10.1109/MIC.2010.145

**Comment by kdahlquist** [comment]
What about this for the Express Framework?

http://link.springer.com/chapter/10.1007/978-1-4302-5861-2_12

Ihrig, C. J. (2013) The Express Framework.  In Pro Node.js for Developers, Apress, pp. 189-204.

**Comment by anuvarsh** [comment]
We currently have 136 passing unit tests when running the tests on beta. On the master branch, we have 134 tests.

**Comment by dondi** [comment]
Working backwards through the comments…

* The D3 and Node.js references are good scholarly references. The D3 one is particularly apt because Bostock is himself the developer of D3. Not as familiar with the folks behind Node.js so can't attest whether the authors are also the developers, but it looks good either way.

* The Express one looks good though is only a chapter in a book. This one has Express in the title, and would serve as a good citation for both Node.js and Express (http://shop.oreilly.com/product/0636920032977.do):

Brown, E. (2015) Web Development with Node and Express. O'Reilly Media.

...These O'Reilly "animal" books have a strong reputation as definitive tech resources for whatever language/technology they're about.

> My editorial observation: they should add some exposition to the wording for "citations"—for open source software, the authoritative reference is frequently the project website itself (e.g., expressjs.com, nodejs.org, d3js.org). The definitive developer documentation is there, and in GRNsight’s case these are the actual sources that were used in developing the application.

**Comment by dondi** [comment]
I've commented on issue https://github.com/dondi/GRNsight/issues/250#issuecomment-167742042

**Comment by dondi** [comment]
And finally, I’ve checked in with Google Analytics, and as of end-of-day on 2015-12-28, our statement would read (also integrating @anuvarsh’s response on unit tests—I’ll use just the master branch):

*The GRNsight server has been running since 20 March 2014. The software has 134 passing unit tests. A Google Analytics page view counter was implemented on 18 September 2014, and a file upload counter was added on 13 April 2015. From these start dates and as of 28 December 2015, the GRNsight home page has been accessed 1820 times, and 1259 files have been uploaded and viewed with GRNsight. Of these 1259 files, 45 were uploaded by users outside of our group.*

The latter number was derived by this procedure:
1. Log into Google Analytics as GRNsight.
2. On the sidebar, select Behavior then Overview.
3. On the list of URLs shown, click on /GRNsight/upload.
4. Under *Primary Dimension: Page*, choose Secondary Dimension > Users > City.
5. The resulting table shows the /GRNsight/upload breakdown by city.

Unfortunately, “Los Angeles” as a city cannot be broken down further, and that one accounts for 1214 of the uploads. Conservatively, that’s where 45 came from—1259 – 1214.

![screen shot 2015-12-29 at 12 22 56 am](https://cloud.githubusercontent.com/assets/382242/12031574/69fc8936-adc2-11e5-969a-9da540c42cd1.png)

**Comment by kdahlquist** [comment]
It's submitted!

**Comment by kdahlquist** [comment]
I received an acknowledgment of our submission via e-mail, see below:

Dear Author,

This is to acknowledge receipt of your proposal for the 2016 NAR Web Server Issue. 

The Web Server Issue receives several hundred proposals and manuscripts. Due to the crush around deadlines, authors should be patient about responses from the editor. Reply to proposals will typically be made by mid-February.

For proposals given approval, the manuscript submission deadline will be 3 weeks after the date of the approval email or 31 January 2016, whichever is later.

Sincerely,

Gary Benson
Executive Editor
Nucleic Acids Research

**Comment by kdahlquist** [comment]
We were rejected, transcript of e-mail below:

Dear Dr. Kam,

I regret to inform you that your proposed submission is not suitable for the NAR Web Server Issue.  I'm not convinced that your visualization tool adds significantly to the capabilities of existing tools.  Thank you for considering Nucleic Acids Research and I hope that you will consider sending us manuscripts in the future.  


Sincerely,
Gary Benson
Executive Editor
Nucleic Acids Research
