### ISSUE TITLE
Add a Privacy Policy to GRNsight web site as required by our use of Google Analytics

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#258]
Our use of Google Analytics and their terms of service requires us to have a Privacy Policy on our web site.

http://www.davemulder.com/2010/07/01/using-google-analytics-wheres-your-privacy-policy/

The author of that blog has a policy that we might modify:

http://www.davemulder.com/privacy-policy/

I like how he provides links to opt-out (I'm not saying we should write our own, but that we could link to the Google plugin for opting out).

Another one I found is here:  http://www.istat.it/en/privacy/google-analytics-disclaimer

We can add the text that we wrote for the NAR submission:  " Every user’s submitted data are private and not viewable by anyone other than the user. Uploaded data reside as temporary files and are deleted from the GRNsight server during standard operating system file cleanup procedures."

We should probably create a new web page for the full policy and then add the link to our footer on every page.

@dondi, you probably have experience with this, can you advise on some language, we should probably attend to this ASAP.

**Comment by dondi** [comment]
@dondi and @kdahlquist will determine the final language, after which @mihirsamdarshi will execute the change.

**Comment by dondi** [comment]
I looked around a bit and it seems that a lot of sites leave the details to a link:

<img width="1048" alt="screen shot 2016-03-13 at 11 34 04 pm" src="https://cloud.githubusercontent.com/assets/382242/13736740/8b5cc4d6-e974-11e5-9c58-889f9e258fa1.png">

Of course our version (if we adopted this style) would not mention ads nor other services because we don’t do those, so it would read more like this:

> This site uses cookies from Google to analyze traffic.  Information about your use of this site is shared with Google. By using this site, you agree to its use of cookies.

…then, a “Learn More” link. The screenshot above actually went to this Google page on cookies:

https://www.google.com/policies/technologies/cookies/

Anyway, just adding this to the set of possible options for now.

**Comment by mihirsamdarshi** [comment]
Has there been an update to the specific wording we want for the privacy policy on the website, and whether we want a banner over the top directing users to the policy?

**Comment by kdahlquist** [comment]
I think I am a reluctant "yes" to the banner; I remember discussion at the meeting where @mihirsamdarshi said it was required by the EU.

There isn't any update on the wording.  I don't think I will have time to think about this for at least another week, sorry.  Let's hold off on implementing the banner until then.

**Comment by kdahlquist** [comment]
OK, I've had a chance to look this over and reflect upon it.  What @dondi suggested above for the banner, i.e.,

> This site uses cookies from Google to analyze traffic.  Information about your use of this site is shared with Google. By using this site, you agree to its use of cookies.

and the "Learn more" link out to the Google page here:  https://www.google.com/policies/technologies/cookies/ is fine for the banner.  I'm going to add a little bit of explanation to our Privacy statement on the About page explaining that we are counting pageviews and uploads to track usage of our services.

**Comment by dondi** [comment]
@mihirsamdarshi Would you happen to have the slideup/popup/banner code that you showed us during the semester for the privacy statement? I’ve scoured your commits on the repo and could not find it. Now that the statement is finalized, this can be implemented.

**Comment by dondi** [comment]
OK, a preliminary version of the banner is now active on the website. Note that it appears only once; it uses a cookie to track whether it has appeared. To avoid having to manage cookies manually, you can test this functionality using "Incognito" or "Private" browser windows (Chrome's and Firefox/Safari's terms, respectively). This type of browser window can be opened from the File menu on a Mac; on Windows the menu structure is different but the command should be there (i.e., "New Incognito Window" or "New Private Window").

In these windows, cookies only last as long as the window is open. Thus, in the same window, you will get the expected behavior of having the banner appear only once, then never again. However, when you _close_ the window and reopen another incognito or private window, that cookie is thrown away and the banner will reappear.

**Comment by kdahlquist** [comment]
If I click the "Learn more" link, the banner is dismissed, presumably because of the behavior you describe.  But I don't think it should be dismissed until someone clicks "Got it".  If you change the URL to open in a new tab/frame, would it not be dismissed?  If that will work, I think we should change it.

**Comment by kdahlquist** [comment]
I think I have a preference for the banner to say our statement from the Privacy policy:

This site uses Google Analytics to count pageviews and file uploads to demonstrate usage of our software to interested parties such as our employers and funding agencies. Information about your use of this site is shared with Google. By using this site, you agree to its use of cookies.

It's not too much longer and gives them the info they need, will it fit?

**Comment by dondi** [comment]
OK I'll see what I can do with the revised message. Also for the "Learn More," I'll send it to a different window. That should keep it open. It goes away right now because hitting Back counts as a reload, and by then the browser already thinks you've seen it. Linking to a new tab/window will keep it around.

**Comment by dondi** [comment]
OK, new tab/window version is up.

**Comment by dondi** [comment]
And now the new language is up also. I tweaked the sizing a bit so despite being longer I think it still looks OK.

**Comment by kdahlquist** [comment]
Looking good.  I'm closing this.
