### ISSUE TITLE
Explore cytoscape.js functions on known test graphs

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#260]
Now that cytoscape.js is functional, we need to explore what it can give us with simple graphs.  At our next meeting we'll report back and talk about what we want to implement and options.

**Comment by mihirsamdarshi** [comment]
We tried to make cytoscape.js account for directed graphs using the eles.dijkstra() function. 
http://js.cytoscape.org/#eles.dijkstra

However, the directed boolean doesn't seem to work. It was also referenced in this issue. 
https://github.com/cytoscape/cytoscape.js/issues/993

The administrator opened the issue, but then closed it, presumably without fixing it.

**Comment by mihirsamdarshi** [comment]
We can't seem to figure out how to set the directed function for many of the functions we have been testing.[ Attached is the documentation](http://js.cytoscape.org/#eles.dijkstra) for the `dijkstra` function.

Take a look at our code and let us know if we're setting it wrong. 

`  var dijkstra = cy.elements().dijkstra("#f", true);
            console.log(dijkstra.distanceTo("#a"));`

**Comment by dondi** [comment]
What does your code look like when doing that? Are you supplying a weight function too? Which graph(s) have you tried?

The issue that you reference does point to some commits which purportedly fix the bug, but I don't know the code well enough to anticipate the result. First we need to establish a case with clear expectations for what this computation should return. After that, we can potentially follow the code to see if our expectations align with the code’s behavior.

**Comment by dondi** [comment]
Oops, I just realized, you had code right there. So you aren't setting a weight function. It might be good to visit the actual Djikstra code to see if it is handling the lack of weight function correctly.

**Comment by dondi** [comment]
I looked at the code more closely (particularly as highlighted by this commit: https://github.com/cytoscape/cytoscape.js/commit/72f6a98c883e07d61add01b059c4b92275cbd466) and can confirm that you can't "skip" the weight function argument. Insert a `null` in there and see what happens:

        var dijkstra = cy.elements().dijkstra("#f", null, true);

**Comment by anuvarsh** [comment]
var dijkstra = cy.elements().dijkstra("#f", function(){return 1;}, false);
    console.log(dijkstra.distanceTo("#b"));

With the above code, we were getting accurate directed graph shortest paths. After updating this code to reflect @dondi most recent comment, we are also getting the correct shortest path. The mistake we were making was completely ignoring the "weight" parameter instead of setting it to 1 or null.

**Comment by anuvarsh** [comment]
Unit tests have been created to check data conversion from GRNsight to Cytoscape, shortest paths, and betweenness centrality of all of the nodes. However, when manually checking the betweenness centrality of a couple nodes, @mihirsamdarshi and I got different answers than what the cytoscape function returned. Not sure if this is a miscalculation on our part or an implementation problem. The following are the discrepancies:

For node `c`:
Undirected, we calculated 6 but the function returns 2.
Directed, we calculated 3 but the function returns 2.

For node `e`: 
Undirected, we calculated 6 but the function returns 2.

For node `f`: 
Undirected, we calculated 4 but the function returns 0.

**Comment by dondi** [comment]
Are you counting paths that start or end with the node in question? I don’t think those are included. Outside of that, it might be useful to list the paths you calculated, then make sure that the paths you listed truly are the shortest ones.

If you omit paths where the node is the start or end, for `f` for example it would make sense that the function returns 0, because nothing passes “through” `f` to get to another node.

A good way to intuitively check your answer is to rearrange the graph (in GRNsight, of course!) so that the nodes lie on a grid (assuming unweighted). I’m including a screenshot for *graph-stats-demo.xlsx* arranged as such. Here you can see it makes sense that nothing goes through `f`. Also, for `c` directed, notice that only `ecb` and `ecba` are the shortest paths through it, so the answer of 2 looks right.

<img width="567" alt="screen shot 2016-04-17 at 7 29 54 pm" src="https://cloud.githubusercontent.com/assets/382242/14592386/ce756678-04d2-11e6-940a-d5133a258171.png">

**Comment by kdahlquist** [comment]
We have finished with this phase, next steps will be outlined as new issues.
