### ISSUE TITLE
Search engine optimization for GRNsight web site

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#277]
We want to do some things to optimize the GRNsight home page so it is found by search engines.
* add search metatags
    * gene regulatory network 
    * gene regulatory network visualization
    * +/- web app
    * automatic graph layout
    * adjacency matrix
    * add others here
* possibly other techniques

**Comment by dondi** [comment]
After doing some reading, the final approach taken for this was to use [Google Search Console](https://www.google.com/webmasters/tools). This entailed:
- Adding a verification file to the site
- Generating a sitemap (fortunately this can be [automated by Jekyll](https://help.github.com/articles/sitemaps-for-github-pages/))
- Waiting for indexing/analysis to arrive (not yet arrived as of this writing)
[Traditional keyword tags are no longer used by search engines](https://www.youtube.com/watch?v=jK7IPbnmvVU) because it is too easy to “cheat” with them. Instead, intrinsic content is examined more closely. One tag that _is_ useful, however, is the `meta description` tag. [This web page](http://cohlab.com/blog/write-best-meta-page-description.html) discusses its value.
- As it turns out, [GitHub Pages has support for this also, among other features](https://help.github.com/articles/search-engine-optimization-for-github-pages/). As an initial configuration, the site-level [documented here](https://github.com/jekyll/jekyll-seo-tag#usage) were then set up, and can be refined continuously as Google Search Console supplies on-going data on search characteristics. (particularly differentiation of these attributes for specific pages)

Having taken these actions, some time is needed for engines to capture and index the new content. The intent is to now use [Google Search Console](https://www.google.com/webmasters/tools) to monitor this activity.

**Comment by kdahlquist** [comment]
Need to add 155 descriptions to each page.  See beta page for how to do this.

**Comment by kdahlquist** [comment]
I went ahead and added the metadescriptions to each page, but now the About page is broken.  I can't tell that there is anything wrong with the code, but the page isn't styled anymore.  @dondi, can you take a look?  Sorry.

**Comment by dondi** [comment]
OK, I was able to fix it. You'll love the root issue: it's the apostrophe problem all over again! But this time, it's the _colon_ because as you can see, in this file format, the colon serves as the separator between the attribute name `description` and its value. The solution is special notation to deactivate recognition of the colon—you will see it now in _about.html_.

**Comment by kdahlquist** [comment]
Urgh--I thought it might be something like that, but I thought it might have been the comma's.  Silly me.  Maybe we just shouldn't have punctuation at all.  Thanks for fixing it.  I'm closing this just for the satisfaction of closing something, even though we are going to look at it again when some data has been collected by Google in a few weeks.
