### ISSUE TITLE
Mouseover edges not displaying weights on Safari, Chrome, Firefox on OSX

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#284]
From Reviewer 1 (#278):

"However, the only platform for which mouse over on links revealed the underlying weights was firefox on windows 7. Neither safari, chrome not firefox on OSX or Chrome on windows 7 showed the weights."

We need to investigate this and fix.

**Comment by kdahlquist** [comment]
We are using a web page attribute called title=

There is no obligatory, standardized action of what to do with a title.

When we first developed GRNsight, the default was to display as a tooltip, but now as browsers have diverged and new tools like Bootstrap are available, it is doing this less and less.

We need to programmatically, intentionally build that in now with new code.

**Comment by kdahlquist** [comment]
Presumably this option would go under the Edit > Preferences menu item.

**Comment by kdahlquist** [comment]
Bootstrap tooltip utility doesn't work with SVG.  We do not have the option of using a premade HTML tooltip library.  At the time, we used the easier option of using "title", but now we have to roll our own.

**Comment by kdahlquist** [comment]
https://codepen.io/recursiev/pen/zpJxs

**Comment by dondi** [comment]
As we discussed, I will start looking into this issue for now while import/export testing finishes up. However I will pre-empt this and switch immediately to import/export bug-fixing once we know the full scope of what those fixes are.

**Comment by kdahlquist** [comment]
Are you going to have a chance to look into this now?

**Comment by dondi** [comment]
Yes, I'll get back to this. I started some uncommitted code and will return to this while the import/export testing is being done.

**Comment by dondi** [comment]
I think this will be one of those functionalities which will need a lot of trial & error and tweaking, but for what it’s worth I put something up for review. Beta version is bumped to 1.17, and this branch is derived from `import-export`. That way we can release _just_ `import-export` if we want (in which case it would be 1.16) or if we release both, we go to 1.18.

In any case, it’s there. It has some issues, all of which would increase the code if addressed so I figured this is a good point to take stock:
- The weight labels don’t float above the entire graph because they are drawn alongside their associated edges. Thus, some labels will appear to be other under nodes and edges. This would be by far my biggest critique of the approach used here ("CSS hover," per the link above).
- Hovering is also tricky, but at least it is reliable. The hover detector is quite exact about when the mouse is over an edge, so thin edges require better mouse targeting. But at least there is no delay in appearance, and once the mouse is over a "hot" spot, the weight label is fairly stable.
- Positioning was the source of a lot of trial and error for me. I settled on a computation that puts the label roughly in the centroid of the polygon bounded by the edge. Self-referring edges have the weight appearing directly below them. There is currently no bounds-checking.
- Other visual attributes are probably subject to some trial and error too (e.g., font, size, color).
- The preference to keep the weights visible all the time has not been implemented, but I know how to do it when it’s time to do that. The issue here is that, depending on the technique used for the basic weight functionality, the technique for making them visible all the time will also vary.

OK, I’ll let that sit where it is for now, and maybe try another layer of refinement tomorrow. Likely we will need to discuss this on Wednesday, or maybe even try some things live.

**Comment by kdahlquist** [comment]
So here are my initial responses:

>The weight labels don’t float above the entire graph because they are drawn alongside their associated edges. Thus, some labels will appear to be other under nodes and edges. This would be by far my biggest critique of the approach used here ("CSS hover," per the link above).

Yeah, this was the first thing I noticed.  It's close to being a deal-breaker because if you can't read the weight because it's under another node or bunch of edges, it kind of defeats the purpose of having this feature.  How is it decided which edge is on top when two edges cross?  Or for that matter, two nodes?

>Hovering is also tricky, but at least it is reliable. The hover detector is quite exact about when the mouse is over an edge, so thin edges require better mouse targeting. But at least there is no delay in appearance, and once the mouse is over a "hot" spot, the weight label is fairly stable.

I would say that this now harder with the new implementation than it was with the older tooltip.  What I'm noticing is that my cursor is not staying as an arrowhead, which is required to trigger the display of the weight.  Instead, it is shaped like the insert text line.  In this form, it does not trigger the display of the weight.  I have to move it around to get it to change to the arrowhead and it's not clear what makes it change.  Getting it to perform on shorter edges is considerably harder than for longer edges.

>Positioning was the source of a lot of trial and error for me. I settled on a computation that puts the label roughly in the centroid of the polygon bounded by the edge. Self-referring edges have the weight appearing directly below them. 

The current positioning is fine with me.  I think this only becomes an issue if/when all edges are displayed at once and we need to make sure that the user knows which weight goes with which edge.  In the absence of being able to see that, I don't have a recommendation.  The position of the self-referring edges is fine with me.

>There is currently no bounds-checking.

I'm not sure what you mean by this, but it did make me look to see what behavior happened when nodes and edges were near the bounding box.  I was unable to get the weight to display when the edge was thin and the two nodes were at the top of the bounding box.  For example, take demo 4 and put genes REB1 and GTS1 at the top of the bounding box and far enough apart so that the edge is curved and very close to the bounding box.  If I trace this edge with my mouse, I don't see a weight display at all, even if the cursor is an arrowhead.

>Other visual attributes are probably subject to some trial and error too (e.g., font, size, color).

Your initial choices on this look OK to me.  What stands out is that the edge weights are in bold and the node labels are not, which really makes the weights "pop" with respect to the nodes.  This is OK when we are only looking at one weight at a time; we do want them to "pop".  However, this might need to be revisited when we display all weights at once.

>The preference to keep the weights visible all the time has not been implemented, but I know how to do it when it’s time to do that. The issue here is that, depending on the technique used for the basic weight functionality, the technique for making them visible all the time will also vary.

OK.  We'll probably need to discuss doing something "quick and dirty" in response to the reviewers with the understanding that we will need future tweaks, or leaving it alone.

**Comment by kdahlquist** [comment]
By the way, did you verify the original bug that edge weights were not displaying on Chrome and Safari?  I just fired up Chrome to see the new changes in beta and saw that the tool tips _are_ displaying for v1.12.1 on Chrome.  Are they displaying for you?  What about Safari?

I thought I had previously verified the bug myself, but now I'm not sure.

**Comment by dondi** [comment]
I’ve found inconsistent behavior. Last night, I noticed that the original weights implementation was working on my locally-run GRNsight in Chrome, but they did not work off the public GRNsight website. I saw some StackOverflow questions that hinted that putting an element in an `iframe` affects the functionality.

With respect to the caveats of the existing implementation, I’ve been mulling assorted ways to address them and have come up with a possible approach _if_ one behavioral change is acceptable: Would it be OK if a mouseover makes _all_ weights appear instead of just one? Allowing this behavior will permit a particular implementation approach that will put all of the weights on top of all other elements (kind of like in their own layer), without requiring too much additional code.

I have also come up with a potential approach for expanding the "hot zone" for hovers, but that might not be necessary if a single hover actually shows all edge weights.

For the bounds checking, what I meant was that the default weight tooltip positioning calculations don't take the drawing area's boundaries into account, meaning that when close to the edges, sometimes the edge weights end up outside of the drawing area. That’s why you didn’t see those weights.

Anyway, let me know what you think about the "all weights appear on any hover" change and I can proceed accordingly.

**Comment by kdahlquist** [comment]
I'm not opposed to that solution, per se, but the devil is in the details.
* I wonder if it might be too distracting when simply moving your mouse over the screen to have the weights flash on and off, as they will end up doing with this solution.  In this case, I think that we would need to immediately implement the three options below:
    * weights appear on mouse hover
    * turn off weights
    * turn on weights
        * These options would of course be available from the menu, most likely Edit > Preferences
        * But it should probably just be available from the display, maybe the text "Mouse over edges..." would be replaced with three radio buttons giving the options.
* We would definitely need to play around with font, size, color for the weights so that they don't overwhelm the display.  Immediately, I'd recommend unbolding them and making the font a little smaller, say 50% of the node label font for starters.  I think black with the white shadow is OK for color for now.
* We have to make sure that the placement of the weight values is unambiguous.  Here are two screenshots where the edges of RAP1 to RPH1 and HSF1 are near each other.   It looks like the value for RAP1 to RPH1 is actually the value for RAP1 to HSF1.  I think that the weight values need to clearly bisect the edge, which I know is difficult because we have curved edges, but I think that is more clear.

So I guess my conclusion is that given these requirements are met, I'm OK with all edges appearing on hover.

**Comment by dondi** [comment]
OK, I’ll proceed with trying this out. Like you said, the devil will be in the details. We might not know how this fully feels until it is up.

**Comment by kdahlquist** [comment]
Actually, upon re-reading our documentation and manuscript, I think the menu item should go in the Format menu (for this and #285).

**Comment by dondi** [comment]
So in the end I managed to let the weights on top of all nodes and edges, but still appear individually. It took a little more code but not as much as I initially anticipated, so that’s the version that is up now. The "hot" zones over the edges have also been expanded so it is easier to mouse over the thin ones.

I didn’t refine things further pending validation of this updated overall approach, but things can proceed if this looks acceptable.

**Comment by kdahlquist** [comment]
I've verified that these work now on both Firefox and Chrome on Windows 7.  I think it looks pretty good.  We can discuss whether to close this or do more tweaking at our meeting a little later.

**Comment by kdahlquist** [comment]
With the new way of implementing this, @dondi make the weight appear near the mouse pointer, like the tooltip used to do.

Further tweaks to the styling can be done later.

**Comment by dondi** [comment]
OK, got this done, but in doing so I concluded that this makes #285 a touch more complicated than originally anticipated. With the weight now appearing under the mouse when a mouse crosses an edge, the option of "show all weights" becomes more complicated to implement because the weights would then need to be repositioned plus the mouse-based positioning logic would need to be turned off.

The position-calculating code is there, but additional code is needed to switch between that and mouse-based positioning. There is essentially more logic and condition-testing involved and at this point I’d rather play it risk-averse so that we can get to a release sooner rather than later.

You can try out the new positioning now in the beta version.

**Comment by kdahlquist** [comment]
Looking good.  My only comment is that when the weights appear, the arrowhead changes to the insert cursor, but I can live with that.  The weight tracks with me tracing the edge with my mouse and even responds correctly when edges cross (momentarily displaying the other weight).

It's good to know that #285 is in the wings, but I agree, it's late and we still have a lot of tasks to get done for submission.  I will close this one now.

**Comment by dondi** [comment]
OK, the cursor has been changed; you can just reload the beta page to see it.

**Comment by kdahlquist** [comment]
Looks good!
