### ISSUE TITLE
Option for showing or hiding all weights

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#285]
From Reviewer 1 (#278):

"I would like to see an option on the tool for showing or hiding all weights."

This is related to issue #284.  What I think this means is that you would click a menu option or button and all of the weights would display without mouseover and then would be hidden again by turning the option off.  Once they were off, we would have to decide whether they could still be displayed upon mouseover or not (probably still display).

I think this a good idea; I have no idea how easy it would be to implement.

**Comment by kdahlquist** [comment]
This is related to #284.  Since we will need to code weights intentionally, this could be implemented at the same time.

Need to decide where to place the weight, middle of edge, near arrowhead?

**Comment by kdahlquist** [comment]
This is an "if there's time" task.  We need to prioritize the tasks needed to submit the revised manuscript.

**Comment by kdahlquist** [comment]
@anuvarsh will meet with @dondi to get this started.

**Comment by anuvarsh** [comment]
I met with @dondi and we outlined a basic game plan about how to start this project. The first step will be to create a new menu item that allows users to either always show or always hide weights. After reading and following Bootstraps navbar tutorial, I will go ahead and start working on the menu item.

**Comment by anuvarsh** [comment]
It appears as if Bootstrap CDN is down, so no changes in code can be observed for functionality. After reading the Bootstrap tutorial, however, I feel fairly confident about completing the menu item soon after Bootstrap CDN is back.

**Comment by kdahlquist** [comment]
@anuvarsh needs to cherry pick commits from display-weights branch on her computer because @dondi deleted the display-weights branch already.

**Comment by anuvarsh** [comment]
Both the menu option and the side bar options have been implemented. I am currently working on the code that changes the selection at both locations if the selection changes at a single location.

**Comment by anuvarsh** [comment]
Both the menu options and the sidebar options for showing/hiding weights select simultaneously. Now working on adding the functionality that actually shows/hides the weights.

**Comment by dondi** [comment]
@anuvarsh can restore some of the code from https://github.com/dondi/GRNsight/commit/4415f86b9a4ba853fbf1e0bc5b204f3190b06124 which replaced the original "always always on" weight behavior to the one that is mouse-driven. She will need to apply a condition that this code only takes effect if "always on" has indeed been selected.

**Comment by dondi** [comment]
@anuvarsh also asked about avoiding a reload whenever the setting is changed. This is actually something that can be written up separately because it will benefit other options that we currently set.

There is however an approach that is _specific_ to mouse weights which can avoid the reloads. The decision is that, after @anuvarsh is able to complete the always-show automatic repositioning functionality using her current approach, @dondi will guide her through a refactor that then eliminates the need for reloading _for mouse weights only_.

General restructuring to enable this on a broader scale is an issue in and of itself. @dondi will try to write it out sometime.

**Comment by anuvarsh** [comment]
Using dondi's old commit where weights are unconditionally shown (after keep weights on top of all things) and restore that code. Add if-statements that wrap around the weights information according to which menu option (always show, always hide, etc.) is selected.

**Comment by anuvarsh** [comment]
After restoring @dondi's code about showing weights, I am still unable to make them always show up. Currently going through and trying to debug, but not really sure where I should be looking.

**Comment by anuvarsh** [comment]
I will read through [Three Little Circles](https://bost.ocks.org/mike/circles/) to get more information about D3. This should help my understanding of how graph.js works overall.

**Comment by dondi** [comment]
@anuvarsh and @dondi met on Tuesday late afternoon and we hashed out the code to wrap this up. @anuvarsh will give it a cleanup pass then we can potentially move this issue to Review Requested.

**Comment by anuvarsh** [comment]
@dondi suggested that I turn the weights options under Format into radio buttons instead of using check marks in order to reduce the amount of code required to implement this functionality. I began coding it in, but I am finding that it isn't actually reducing the amount of code for this functionality by a significant amount. I can push the changes I have made so far so we can discuss the preferred appearance of the weights settings in the Format menu.

**Comment by kdahlquist** [comment]
@kdahlquist vetoed radio buttons in the Format menu.  @anuvarsh will revert back to the checkmarks and then mark this review requested.

**Comment by kdahlquist** [comment]
Cosmetically, make the font smaller for "Hide/Show Edge Weights".  Move the radio buttons closer together and closer to the header.

**Comment by kdahlquist** [comment]
All done, @kdahlquist needs to review.

**Comment by kdahlquist** [comment]
I finally had a chance to look this over.  Here are my comments:

The capitalization of the text accompanying the radio buttons should be in sentence case, not all word capitalized.

For example, Show With Mouse Over should be "Show with mouse over" and similar for the other two choices.

Also, changing the radio button selection makes the graph redraw.  I can imagine a situation where someone has painstakingly moved all the nodes and then decides to show/hide the weights and all of their work gets erased.  So, changing that radio button should not cause a redrawing of the graph.

This relates to @eileenchoe 's comment on #326 about states related to showing/hiding weights.

**Comment by anuvarsh** [comment]
I moved the respective the weight's label code within the tick function in graph.js, and that seemed to partially fix the problem. The css labels are not being removed properly after exactly 3 changes in weights visibility options, and the css that the graph gets stuck on a different option every time. Furthermore, the weights continue to show with mouse over when the "always show" option is selected. This is not a problem with the "never show" option. 

In order to address these issues, I looked at how the CSS tags were added and removed to each element, but I don't see a problem there. Glyphicon and radio button selections are synced up within the same if-statement and both of those are functioning as expected. I experimented with moving just the "mouse over" code outside of the tick function but that didn't help either.

I'm going to continue to try to debug, but if anyone has any ideas about where I should look next, I will gladly take your advice! My gut tells me there is something wrong with the ways the tags are removed, but I can't find evidence of that problem within the code just yet.

**Comment by anuvarsh** [comment]
Ok so, I can confirm that it is because the CSS tag isn't being removed without a refresh. Working on debugging this now.

**Comment by dondi** [comment]
This has turned out to be more complicated than expected due to the complex control flow of the graph layout algorithm used by D3. However, @dondi suggested an approach where the mouse listener that displays the weights dynamically can be refactored into one that reads the current setting on the spot. i.e., Instead of conditionally installing a mouse listener that always shows weights dynamically, the mouse listener can instead be a _permanent_ one that itself conditionally decides if weights should be shown.

**Comment by kdahlquist** [comment]
@anuvarsh has all showing and all hiding working, but now upon mouseover, the weights flash.  So needs to consult with @dondi some more.

In the interest of moving on, @kdahlquist says spend one more week on it to see if you can get it to work.  If not, then the user can access the weights by saying show them all and we can temporarily disable the mouseover option.

**Comment by anuvarsh** [comment]
I met with @dondi and we worked out a solution to the flashing weights. Pushing the solution to my branch and issuing a pull request now. I'm going to wait to merge the pull request with the live beta version until next week so I can make sure I'm not messing with anyone else's code.

**Comment by anuvarsh** [comment]
I actually went ahead and completed the pull request yesterday because GitHub told me there were no merge conflicts. Because everything is uploaded and all of the tests are passing, I'm going to go ahead and close this issue.

**Comment by kdahlquist** [comment]
I'm sorry @anuvarsh; I know you were excited to close this one, but I'm re-opening and labeling with review requested.  I want to see with my own eyes the fix on the beta server live before this is closed, especially since I was the one who reported the bug with changing the viewing of the weights causing the graph to reload.

**Comment by kdahlquist** [comment]
I have now verified with v2.0.2 on beta that this functionality is working.  Closing the issue now--thanks for your patience.
