### ISSUE TITLE
Make GRNsight package accessible via BioJS registry

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#286]
From Reviewer 2 (#278):

"Bioinformatics web tools like GRNsight are published in the literature but they are not made accessible via a centralised repository like the BioJS registry. I would thoroughly recommend authors to make accessible their tool via the BioJS registry. The requirements for making a package accessible through the BioJS registry are minimal:

- The source code has be made available via GitHub
- It has to be made available in the Node.js Package Manager (NPM), the package manager for JavaScript
- The "biojs" keyword has to be included in the "package.json" file of NPM"

This seems straightforward, we should look further into the requirements and make this happen.

**Comment by kdahlquist** [comment]
Refer to issue #231

**Comment by dondi** [comment]
I started this by signing out for an npm account, which I have acquired for myself. While reading about how to upload a package to npm, I encountered the concept of an “organization,” which serves as an umbrella that can group related packages together:

https://docs.npmjs.com/orgs/what-are-orgs

My question is: What do you think serves as the better basis for this organization—our overall group (“LMU Bioinformatics”) or the project (“GRNsight”)? I know that for the moment, GRNsight is really the only one which is a fit for npm, but from a publishing/attribution point of view, does it better to release:

- The GRNsight package under a “GRNsight” organization
- The GRNsight package under an “LMU Bioinformatics” organization
- Or any other scheme that you might think works best for our purposes

**Comment by kdahlquist** [comment]
Well, let's think of it this way, our license (and masthead) describes GRNsight as a joint project of the LMU Bioinformatics and Biomathematics Groups.

With the creation of the LMU Bioinformatics group on GitHub, I think we intended that future projects would go under that umbrella.

So, I think we should probably go with LMU Bioinformatics Group, if there's a chance (however small) that we would have a different javascript project in the future.

What do you think?

**Comment by dondi** [comment]
Got it, yes, I was thinking along those lines but just wanted to double-check. I think the reminder that we already attribute GRNsight that way, plus the GitHub organization, seal the deal for me. I’ll proceed with "LMU Bioinformatics Group" as the organization.

**Comment by dondi** [comment]
As noted by email, it turns out that the organization option is a paid one, so we will forego that.

**Comment by dondi** [comment]
GRNsight (current version 1.12 as of this writing) has been published to NPM: https://www.npmjs.com/package/grnsight

It’s very rudimentary and definitely needs more documentation, but it’s there. I did a trial installation via _npm install grnsight_ and the files downloaded and ran correctly. However this was accomplished because I was familiar with the software and knew what to run and how to run it.

The reality is that an outside user would only need to do this if they wanted to run their own instance of the GRNsight web service and/or web client. All other users would just access the website that is already up and running. In any case, it is now on _npmjs_.

**Comment by dondi** [comment]
…and, as it turns out, publishing on _npmjs_ got it onto the BioJS registry automatically.

**Comment by kdahlquist** [comment]
So I checked it out on npmjs.  We should probably include some kind of longer readme.  How about copying over the text from the About page with a note that says typical users will just use our web site and that you would only need to npm install if you wanted to set up your own GRNsight server.

Also, for the keywords, I suggest adding "network", singular, and "visualization" as separate keywords in addition to "network visualization".

I tried out the "Test GRNsight in your browser" and that doesn't work, but I'm not sure that we are expecting it to.

Also, why is the license showing up as ISC instead of BSD? #19 That licensing got transferred over to the biojs registry as well.

**Comment by dondi** [comment]
As partially expected, npmjs does not allow just publishing "on top" of the same version, and so GRNsight is now publicly labeled as 1.12.1. The updated README, it turns out, is read at publish time, so that is an automated process. Keywords and license have been corrected. You can see it at the same URL indicated above.

**Comment by kdahlquist** [comment]
OK.  If we end up further patching 1.12, we should increment the versioning to 1.12.2 so as not to overlap with this new version.  I'm closing this now.

**Comment by dondi** [comment]
Yes, and actually I applied a v1.12.1 to this incarnation of `master`. May not merit a full-blown release but at least it shows up on GitHub officially.
