### ISSUE TITLE
branch clean-up

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#289]
We talked about this yesterday, but I thought maybe it needs to be an issue.

Note that I was doing clean-up of the documents folder on the master branch (posters and talk slides).

I forgot that we had the peerj branch and just put up the response to the reviewers on master instead of the peerj branch (sorry)

I was doing some investigating of BioTapestry and created a SIF version of our 21-genes_31-edges_Schade-data_input.xlsx demo file but I'm not sure where to put it.  I'm going to hold off until you figure out the branch merging strategy.  I assume that it will go into a subdirectory of the test-files directory, but am just not sure which branch.

**Comment by dondi** [comment]
I looked into our branch tree and noted the following:
- The `peerj` branch was actually merged into `master` on June 15 with no new commits since, so actually it’s OK that the response to reviewers went to `master`
- Contrary to my recollection, `graph-statistics` was actually branched from the bigger `beta` branch rather than `master`. In-keeping with our discussion about thinking of our revisions as a “hot fix” to `master`, that means this functionality will stay separate for the moment.

**Comment by dondi** [comment]
In-keeping with the “hot fix” mentality, I’ve concluded that the way I’d like to proceed is to apply each self-contained change as its own small, transitory branch, to be branched from `master` then merged back in short order, once finished. As an initial instance, I used this approach in preparing for NPM publication. The work was done in a branch called `npm-prep` then merged into `master` once the needed work was finished.

**Comment by dondi** [comment]
I’ve now started an `import-export` branch, and have added the manually-build _.sif_ files there.

**Comment by kdahlquist** [comment]
Do we need the Peerj branch anymore?  It might be simpler to just commit manuscript documents to master since the documents directory is pretty separate from any of the other code.

**Comment by kdahlquist** [comment]
peerj branch is deleted.

@dondi can branch new graph-statistics from master and find just changes from graph-statistics branch that pertain to graph statistics and semi-manually put them on the new branch. #262.
