### ISSUE TITLE
Merge graph-statistics with beta branch and deploy beta code on the beta web site

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#293]
As discussed in #262, merge graph-statistics with beta branch and deploy beta code on the beta web site

**Comment by dondi** [comment]
OK, `graph-statistics` has been merged into `beta`, and the web app in http://dondi.github.io/GRNsight/beta.html now includes the Graph Statistics tab at the bottom (when a GRN is loaded).

**Comment by kdahlquist** [comment]
Shouldn't beta now be 1.15 or at least 1.13.1?  This version is distinct from the 1.13 that was there before.  I think I was saying yesterday that I would like beta to increment each time we deploy a new version on beta to indicate that it is a new version.  Also, the last modified date on the page needs to be updated.  I could make these changes (on gh-pages) myself, but need agreement on the version number and I'm not sure whether something also needs to be changed in the code.

I have comments on the actual functionality, but I'll post that under the appropriate issue #262.

**Comment by dondi** [comment]
Oh actually I should have mentioned this—when I restarted the beta deployment I noticed that the previous one wasn't actually on the `beta` branch, but `master`. Thus, it’s unclear whether 1.13 genuinely pertained to a genuinely distinct version at all. Thus I just left it alone. We can bump to 1.15 though, since regardless of what 1.13 might have been, it’s true that graph statistics only landed in beta yesterday.

**Comment by dondi** [comment]
Given that we are prioritizing export/import and are viewing that as a "hot fix" to `master`, versioning is a little more complex than usual. But here's my proposal for it:
- 1.13 —We are moving on from this. As mentioned earlier, the changes in this version are unclear, but because this has been the published beta version for a while, I think it’s best that we just go forward.
- 1.14 —Because 1.13 is largely abandoned without a release, I suggest we skip this release number as well.
- 1.15 —The current export/import development beta. Because development is happening in distinct branches, this version does not have the graph statistics functionality that was posted earlier.
- 1.16 —The intended release version for when export/import reaches a satisfactory state.
- 1.17 onward —The next prioritized functionality will get this number. It may be graph statistics, or it may be one of the other functions in response to the PeerJ review.

This proposal does put the current GitHub `beta` branch in an as-yet undetermined version number. The additional wrinkle to the current development roadmap is the possibility that the graph statistics functionality will be cherry-picked away from `beta` directly into `master`, with `beta` then becoming the pure “overhaul refactor” work-in-progress. The intent is that the versioning plan above accommodates our current priorities plus the development plans that have not yet been fully established.

**Comment by kdahlquist** [comment]
Your versioning plan makes sense.  I'm going to go ahead and close this now.
