### ISSUE TITLE
Change demo labeling to reflect true filenames

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#308]
From Isue #301 

We might want to rethink what the default name for the demo files are when you export them. Currently, the name has the #, (, ), commas, and space characters in them because that is what we call them in the menu. For people who want to pipe files to different programs, this is going to make them cringe (as it did me). Any chance we can customize this so that the actual file names that the demos have in our test-files directory are used instead (which only have hyphens and underscores)?

So what we will do is get rid of the customizations to the display of the filenames of the demo files in the menu bar to revert to the actual filenames and that will be an easier fix than to keep the customizations.

**Comment by dondi** [comment]
This change has been made and is now available on the beta v1.15 page. This actually took surprisingly longer than anticipated due to some unforeseen wrinkles. Interestingly, the code changes made to do this had an effect on the reload mechanism too, which is why both changes ended up landing in a single commit.

**Comment by kdahlquist** [comment]
Confirmed and closing.
