### ISSUE TITLE
How to link to subsections within Documentation page

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#316]
I tried to link to a couple of different subsections in the Documentation page, but I don't know quite how to do it since it is not working.

See in Section 1c, I added one link to section 1a and two links to section 3a.

Can you check it out and see what I'm doing wrong?  Also, check out what I wrote to make sure it is consistent with what you are implementing.

**Comment by dondi** [comment]
One more attribute is needed: `data-toggle="collapse"`. I’ve added this to the links you mention above.

However, this behavior is not perfect. The link does open and jump to the subsection with the given ID, but _only if its containing section is already open_. If the section is closed (e.g., Section 3 when the user clicks on the link to Section 3a), there is a jump but the containing section is still closed.

I suspect that we are going beyond the intended behavior of this Bootstrap collapse feature here; additional code may need to be added to the documentation page so that opening a section also opens all of its parent sections (if they are still closed).

**Comment by dondi** [comment]
Some notes on the content in Section 1c:
* "Node names must be 12 characters or fewer." —The import code does not enforce this yet; it’s one of the checks that needs to be refactored out of the current GRN-loading code.

…OK, actually, that’s the only note I came up with :) The rest of the information looks good 👍 , and as of the latest deployed beta, this behavior should now be available.

(details later in the other issues)

**Comment by kdahlquist** [comment]
Thanks.  I'll start another issue about section opening, but give it a low priority, in case we want to deal with this later.

I'm going to leave the node names must be 12 characters or fewer because even if we are not enforcing it now, the intention is to enforce it in the future and we may as well signal to users that they need to use short node labels.  I've put a reminder in issue #300.
