### ISSUE TITLE
Opening a web page section should also open all of its parent sections (if they are still closed).

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#317]
Opening a web page section should also open all of its parent sections (if they are still closed).

This was noticed on issue #316 when linking within the Documentation page.  It's a low priority for now, but I'm posting it as an issue so we don't forget about it.

**Comment by dondi** [comment]
It turns out that there is code for doing that already available:

https://github.com/dondi/GRNsight/blob/gh-pages/assets/js/main.js#L73-L83

Despite this, it does not consistently work in the Documentation page, as described in #316. So this task is less about writing new code and more about determining why the Documentation page links don't behave consistently, then making fixes as needed.

**Comment by kdahlquist** [comment]
Backlogging this feature request and closing.
