### ISSUE TITLE
Tasks for release v1.18

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#323]
- [x] merge display-weights branch into master
- [x] tag that version as v1.18
- [x] create draft release item on Github repository
- [x] publish GitHub release item
- [x] publish release to GRNsight home page (update version number and modified date)
- [x] increment beta to v1.19 (update version number and modified date)
- [x] update npm (check to see that BioJS updates)
- [x] screenshot for Fig 4
- [x] update Istanbul test coverage
- [x] Google Analytics pick up numbers
- [x] update about page
- [x] write news item

**Comment by dondi** [comment]
…well, release item is created but still in draft form https://github.com/dondi/GRNsight/releases/tag/untagged-42c03dc1512f68a09455

**Comment by kdahlquist** [comment]
I tweaked the language a bit, but I think it's a go when you are ready.

**Comment by dondi** [comment]
Bleagh just realized that npm _requires_ a minor version, even if it is zero (i.e., v1.18.0 and not just v1.18). Oh well; stuff was already tagged and released publicly, and this did require a commit, so we are nominally on v1.18.1 where the only change is this version adjustment.

https://www.npmjs.com/package/grnsight

**Comment by kdahlquist** [comment]
You couldn't have incremented it to v1.18.0?  Just wondering.

**Comment by dondi** [comment]
Yes, I technically could have, but then the tag/version state would have been weird. Semantically, v1.18 is the same as v1.18.0. But adding the ".0" would have required a commit, and then I would have had to either move the v1.18 tag up or made the new commit a v1.18.0, both of which didn't sit right with me (the former because the tag had already been published; the latter because then we would have had v1.18 and v1.18.0).

So in the end I figured it was most reflective of the history of stuff to just declare a v1.18.1, where, in a meta sort of way, the reason for the change was to just edit the _package.json_ file to reflect v1.18.1.

I don't know, I guess I just got hit with an extra dose of meticulousness today :-P

**Comment by kdahlquist** [comment]
I get it.  It's ironic that npm is requiring the third number by the MATLAB compiler excludes it!

**Comment by dondi** [comment]
I guess that means MATLAB won’t find its way to npm anytime soon :-D

**Comment by dondi** [comment]
Unit test and Istanbul numbers have been updated, and can be found in the text-only revised manuscript and ...Table1... files, respectively.

**Comment by kdahlquist** [comment]
Confirmed.  I rounded the table percentages to only one digit and pushed.  Cross that task off...

**Comment by dondi** [comment]
I figured it would be safer to post the latest analytics numbers here rather than editing into the paper, since you may be working on it (I just copied the text and revised the updated values):

> From these start dates and as of 12 August 2016, the GRNsight home page has been accessed 2349 times, and 1652 files have been uploaded and viewed with GRNsight. Of these 1652 files, an estimated 148 were uploaded by users outside of our group.

As a reminder for how to acquire these numbers: once logged in to Google Analytics:
1. Adjust the query date range to start from September 1, 2014 (actually any date before September 18 will do)
2. Go to Behavior > Overview; /GRNsight shows the home page access count
3. /GRNsight/upload shows the file upload count
4. Click on /GRNsight/upload then choose "City" as the Secondary Dimension; we are counting all uploads that are _not_ from Los Angeles as being outside our group

**Comment by kdahlquist** [comment]
Thanks.  I am still working on the manuscript.  I think I've got the intro and biological interpretation sections the way I want them.  Still need to work on the discussion and FAIR.  I've added these numbers and pushed what I've got so far.  I'd like your take on my new intro if you have a chance.

**Comment by dondi** [comment]
OK, I gave the latest Introduction a once-over. The whittling down of downloadable applications vs. web applications is a good broad stroke; then the specific disqualifiers for the chosen applications sounds like sufficient due diligence to me. Plus the additional circumstances that drove our final track come out a lot stronger.

One early flag that came to me was the mention of the Pavlopoulos survey which came out in 2015, yet we started in 2014. This was clarified a few sentences later when it was stated that the survey as of 2015 is representative of what we faced in 2014. So in the end that was fine.

One phenomenon that might be worth mentioning is the way flexibility/power in software frequently incurs the cost of additional complexity. This is a corollary of "one thing well" and is, for example, one reason why Cytoscape did not fit our needs. That statement would need a citation though and that is tough to come by because it is almost taken for granted among experienced software developers. [This blog post](http://boxesandarrows.com/complexity-and-user-experience/) has a good statement of the principle, but I'm not sure if it would be a proper reference for the paper:

> The best products don’t focus on features, they focus on clarity. Problems should be fixed through simple solutions, something you don’t have to configure, maintain, control.

This really distills how GRNsight (which can open a working, non-trivial demo with a single click) differs from Cytoscape.

**Comment by kdahlquist** [comment]
Thanks for this.  I'll try to add it to the discussion as another way to state the one thing well.  We did reference a blog post for one thing well, so I'm not averse to using another one here.  We've got a pretty high number of URL citations anyway because of the links to code and documentation, etc.

**Comment by kdahlquist** [comment]
Moar tasks:
- [ ] update version at Elixir,
- [ ] update version at bioinformatics.ca
- [ ] update version at bioinformatics.org
- [ ] we probably need to create a wiki page listing tasks for release so we don't keep having to write up this issue from scratch each time (especially as the task list grows...)

**Comment by dondi** [comment]
I updated the version at Elixir, but it seems that "update" actually means "make a copy with the new data." So now GRNsight has one entry each for v1.12 and v1.18. Should I delete the former?

**Comment by kdahlquist** [comment]
Yeah, I guess we should delete it because it is no longer available.  That sucks, though, in terms of having a "history" with the site.  We can mention it to the developers as an issue.

**Comment by dondi** [comment]
OK, v1.12 entry has been deleted. I agree, their chosen behavior is not what I (nor most users) would expect.

**Comment by dondi** [comment]
The [release procedure wiki page](https://github.com/dondi/GRNsight/wiki/Release-Procedure) has been created. This link has also been added to the wiki home page.

**Comment by kdahlquist** [comment]
I updated the release wiki page because we don't actually need to update bioinformatics.org or bioinformatics.ca pages.

**Comment by kdahlquist** [comment]
I reported the version issue with Elixir to the developers.  I think that's the last "open" thing about this issue, so I'm closing.
