### ISSUE TITLE
iframe doesn't display if https is used instead of http in home page web address

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#327]
This is something weird that I discovered when checking the proofs of our manuscript.

One of the URLs in the paper used https instead of http for the GRNsight home page address.

When you do this, the page comes up, but the iframe is blank (no menu bar, sliders, bounding box).

I'm not sure if this matters or not (I'm going to ask them to fix the proofs), but I'm reporting it, in case we can fix it.

**Comment by dondi** [comment]
Yes, I can explain this. The latest browsers implement a rule that an https website must only use https resources. Our internal web client at grnsight.cs.lmu.edu serves up just http, while GitHub Pages can serve up both http and https. Due to this relatively new browser rule, we should stick with http across the board. Ideally we should also turn off https for GitHub Pages so that people don't stumble upon that URL too, but I'm not sure if that can be done.

**Comment by kdahlquist** [comment]
I'm going to drop this to a priority 1.

**Comment by kdahlquist** [comment]
Note that @NAnguiano reported this in #439, which she then closed because it was a duplicate of this one.

**Comment by kdahlquist** [comment]
Now duplicated by #688. Closing this one.
