### ISSUE TITLE
Merge branches

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#332]
* @anuvarsh is going to cherry pick #285 from local display-weights branch into issue204 branch.
* then merge issue204 into beta
* then @mihirsamdarshi will make new branch from beta to work on the test refactoring

**Comment by anuvarsh** [comment]
After speaking with @dondi, we decided that it will most likely be more efficient to just rewrite the code instead of cherry picking in this current situation. For that reason, @NAnguiano is free to merge issue204 with beta, and I will rewrite my code afterwards.

**Comment by NAnguiano** [comment]
Before completing the merge, I'm going to first make sure beta's tests are passing so that I have a clean base to work with when I make the merge. 

When I run a fresh npm install then make test, 46 tests fail. 

In warnings-adjacency-matrix-modifications.js, the function invalidDataWarning is listed as not being a function. This causes 9 tests to fail, as they get "TypeError: test.invalidDataWarning is not a function". I checked in test.js and it's not listed there. Adding that in should fix that issue. I can add it myself, but I think this is better left to @anuvarsh  and @mihirsamdarshi, since they're a bit more familiar with the testing framework than I am.

Additionally, in errors-gene-name-modifications.js, all of the special characters are returning the error "TypeError: Cannot read property 'id' of undefined". This causes 30 tests to fail. In the console when running the test, when the tests fail, it says an error along the lines of: "The selector `#ACE2&`is invalid". The error appears to be coming from cytoscape, as it's erroring in the graphStatisticsReport section of the spreadsheet controller, specifically on the line "shortestPath: dijkstra.distanceTo("#" + network.genes[j].name, null, true)" (and the error is initially thrown in cytoscape). I'll have to put in some sort of error handling for this so that this can be avoided. 

When the invalidDataWarning and the special character failed tests are removed, that leaves only 7 tests failing, 5 because they take too long to run on my computer and 2 because of assertion errors (both show 0 warnings when they should show 225). I'm going to work on fixing the two assertionerrors for now.

**Comment by anuvarsh** [comment]
The invalidDataWarnings have been fixed. For some reason, part of the warning function was hidden within invalidDataTypeError. I took out the portions of the function that were related to the warning and recreated the test function for the warning. Furthermore, in the spreadsheet controller, the warning was named invalidMatrixDataWarning, so I renamed the warning function in test.js to match for the sake of consistency. 

The two assertion errors @NAnguiano mentioned above are associated with the data-type-header-date-*.xlsx adjacency matrix. This sheet is not causing any errors or warnings because spreadsheet-controller is overlooking the data type assigned to the cells in the matrix. The unit tests written for these sheets, however, are looking for these cells to cause errors, and are therefore failing. We now know why the tests are failing, and how to fix this issue, but the conversation has become whether or not spreadsheet-controller should be detecting the different data types and, if so, creating an error or warning for them.

**Comment by anuvarsh** [comment]
On that note, I think it might be worthwhile to at some point make sure that all of the variable names for the error and warning functions are good representations of whatever they are testing because as our testing suite has grown, several of these functions now have variable names that are very similar to each other.

**Comment by NAnguiano** [comment]
The merge has been done.

**Comment by kdahlquist** [comment]
There is one true beta!
