### ISSUE TITLE
Network loads with black edges and cyan blunt end markers

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#355]
Here is the spreadsheet from @Nwilli31.  When it loads in GRNsight it has black edges and cyan blunt end markers on some of the edges.

The sheet name is "network" but has real number values for the adjacency matrix (instead of just 1, 0).  I guess we don't have a case testing for this.

If we really wanted to help the user, we would detect that there is a sheet called "network" and that it had numbers other than 1 or 0 in the matrix and then issue a warning that it will just use black edges and pointed arrowheads and if the user wants colored edges s/he would have to change the name of the sheet to network_optimized_weights.
[dCIN5_network_14-nodes_25-edges.xlsx](https://github.com/dondi/GRNsight/files/605195/dCIN5_network_14-nodes_25-edges.xlsx)

**Comment by kdahlquist** [comment]
Maybe this one should be tackled by our syntactic error team of @mihirsamdarshi , @ebachoura , and @eileenchoe .

**Comment by kdahlquist** [comment]
Assigning this to @mihirsamdarshi.  As noted above, a syntactic test needs to be written for the Excel importer to take care of this case.  Work with @ebachoura and @eileenchoe to define what the equivalent syntactic test would be for GraphML and SIF, respectively

**Comment by kdahlquist** [comment]
This is priority 0.5, after @mihirsamdarshi finishes with #386.

**Comment by kdahlquist** [comment]
@anuvarsh says that these tests exist, but since further work has been done since then, something must have changed.

**Comment by anuvarsh** [comment]
These files technically exist in test-files>sheet-modifications>wrong-sheet-name-input/output, but they are a several random and unnecessary sheets in the file. Perhaps these files should be reworked/simplified so only network or network-weighted sheets exist so we can confirm that the changes in those sheets are the only things being tested.

**Comment by dondi** [comment]
@mihirsamdarshi has just started and has been able to replicate the issue. He will experiment with some changes or additions to the test files and @dondi suggested that he looked at references to the `stroke` property in _graph.js_.

**Comment by mihirsamdarshi** [comment]
it seems that the issue originates in the actually _graph.js_ file, in the lines that depend on the normalized weights for the ends of the edges. I'm working on it still.

**Comment by kdahlquist** [comment]
What is the update on progress on this issue?

**Comment by mihirsamdarshi** [comment]
Sorry, I was trying to test again before I opened a pull request, but localhost won't initialize on my computer, and I've spent the majority of yesterday and today trying to get everything, and diagnose that problem so it wouldn't happen to me again.

**Comment by mihirsamdarshi** [comment]
fixed, created pr

**Comment by NAnguiano** [comment]
@mihirsamdarshi I posted on the pull request, but there's something funky happening with arrowheads and bars. Arrowheads don't seem to show up period - and bars only show up when they have a weight that would turn them grey.

**Comment by NAnguiano** [comment]
The reason it's not working is because the bars and arrows use a very specific id structure. The options are: 
```
#arrowhead_StrokeWidth<#>
#repressor_StrokeWidth<#>
#repressorHorizontal_StrokeWidth<#>
```
The <#> portion contains the stroke width number. Optionally, you can add _selfReferential after the first portion if it's a self-referential loop. If the weight is below 0.05, it adds an additional tag at the end: minimum. In edges over that weight, minimum evaluates to the empty string, so it makes no change to the id. In edges that are under 0.05, minimum becomes "gray". SO you end up with ids like:
```
#arrowhead_StrokeWidth<#>gray
```
Right now, you're changing the value of minimum to be black for every single edge that isn't under a weight of 0.05. Since the id of the form `#arrowhead_StrokeWidth<#>black` doesn't exist, it displays nothing instead of the arrowhead/bar it's supposed to show.

Should be a relatively easy fix. I can help if it gets complicated.

**Comment by dondi** [comment]
After considering that the root cause of the error is the mislabeled worksheet tab, the fundamental issue in the code turns out to be making the assumption of weights based on that tab name rather than the data content. The visual anomaly occurs when weighted data are entered into a tab with the incorrect name.

The other imports (SIF, GraphML) actually make the decision of weighted vs. unweighted networks based on the _content_ rather than an external factor like the tab name. The proposal is to shift the spreadsheet importer to also do this: check the weight values and if the weights are all 1s and 0s, we conclude that the graph is unweighted; otherwise we conclude that it is weighted. This will then drive whether the graph is rendered in color or not.

However, it is still important to remind the user of the expected format for the spreadsheet, so if the data analysis indicates a certain type of GRN but this type does not match the tab name, GRNsight will issue a warning that indicates the discrepancy.

@mihirsamdarshi will refine/validate this proposed behavior with @kdahlquist before moving forward with finishing up the fix for this issue.

**Comment by kdahlquist** [comment]
So, right now, GRNmap *output* workbooks contain both a "network" and a "network_optimized_weights" sheet.  We decided long ago that when both sheets were present, the "network_optimized_weights" sheet prevails.  I am assuming that this behavior is still going to occur under the revised system?  So these would be the conditions:

* workbook only has "network" sheet with 0's and 1's: render with black/pointy edges
* workbook has both "network" and "network_optimized_weights" sheet or just a "network_optimized_weights sheet" with real numbers: ignore the "network" sheet and render in color
* workbook only has "network" sheet with real numbers: give a warning to the user and render in color or render in black?
    * I kind of think it should be rendered in black.  We told the user if the worksheet was named "network" that it would render in black and that if she wants color, she should name it "network_optimized_weights".  Discussion?
    * We could implement the option that's the reverse of rendering weighted graphs as unweighted and give the user to render unweighted graphs as weighted so that she could toggle between them.  Of course in the case of all 0's and 1's, they would just all show up as magenta with the same thickness, so it's really a choice between black and magenta there.
* workbook has both "network" and "network_optimized_weights" sheet, but the "network_optimized_weights" sheet just has 0's and 1's: give a warning to the user and render with black/pointy edges or render in color (all would be magenta and the thickest pointed edges)
    * current behavior would be to render in color (just tried it, attaching file); I think rendering this in color is the right choice.  If the user really wanted it in black, s/he could select the menu option to display weighted networks as unweighted.

[network_optimized_weights_0-1.xlsx](https://github.com/dondi/GRNsight/files/901439/network_optimized_weights_0-1.xlsx)

**Comment by kdahlquist** [comment]
Met with @mihirsamdarshi and made the following decisions:

* workbook only has "network" sheet with 0's and 1's: render with black/pointy edges
* workbook has both "network" and "network_optimized_weights" sheet or just a "network_optimized_weights sheet" with real numbers: ignore the "network" sheet and render in color
* workbook only has "network" sheet with real numbers: give a warning to the user and render  in black.
    * We told the user if the worksheet was named "network" that it would render in black and that if she wants color, she should name it "network_optimized_weights".
* workbook has both "network" and "network_optimized_weights" sheet, but the "network_optimized_weights" sheet just has 0's and 1's: give a warning to the user and render in color (all would be magenta and the thickest pointed edges), which is the current behavior.

This is based on the fact that we have documented to the user that a "network" sheet means unweighted and a "network_optimized_weights" sheet means weighted.

**Comment by mihirsamdarshi** [comment]
Currently making progress on this issue, was not able to work on it a lot over Easter break due to familial and a canine commitment.

**Comment by mihirsamdarshi** [comment]
Currently added the code that specifies the conditions and behaviors specified in @kdahlquist's comment, I just have to make the warnings now

**Comment by dondi** [comment]
@mihirsamdarshi was having issues with making the warning appear; @dondi and @NAnguiano provided guidance for how to do that. @mihirsamdarshi will also implement a unit test then issue a pull request when this is ready.

ETA for the pull request is April 27 Thursday night.

**Comment by mihirsamdarshi** [comment]
Since creating the warning, while running through the pull request checklist, I'm having a lot more trouble than I anticipated this taking, I am trying to get this issue done by tonight.

**Comment by mihirsamdarshi** [comment]
ok, well I fixed the issue with the spreadsheet, but I turned all the unweighted values pink. Time to fix that.

**Comment by mihirsamdarshi** [comment]
I fixed it y'all. Just need to make the test now, I have a meeting to attend, however I intend to have this all done by the ETA of tomorrow night.

**Comment by NAnguiano** [comment]
To summarize what I said on PR #457:
- 4 test failures (I confirmed that the one timeout is because my computer is slow)
![screen shot 2017-04-27 at 7 59 43 pm](https://cloud.githubusercontent.com/assets/6444156/25512640/19c226ba-2b84-11e7-8422-b3146d72f816.png)
- Loading the file in the original post of this issue states it causes 25 issues, but nothing shows up in the warnings modal
![screen shot 2017-04-27 at 8 07 23 pm](https://cloud.githubusercontent.com/assets/6444156/25512795/33bfe074-2b85-11e7-877a-b074fd609527.png)
- The network_optimized_weights_0-1 file is giving no errors or warnings

**Comment by mihirsamdarshi** [comment]
Ah, I see, in the JSON, 24 warnings for incorrectly named sheet show up, however, none of them are showing up in the modal. I'll also work on the 4 test failures, which are weird because I didn't touch code that should have affected those tests, and they had been passing on my machine.

**Comment by NAnguiano** [comment]
I found and fixed the issues causing the tests to fail. I commented on some weirdness I noticed in #417. Most of the failures were actually caused by the new check finding graphs that were improperly structured. So I think all that remains is the modal issue.

**Comment by kdahlquist** [comment]
What is the status of this?  Are we tabling it or trying to include it in the next release?

**Comment by mihirsamdarshi** [comment]
All tests now pass, and the pull request is ready for merge

**Comment by dondi** [comment]
@mihirsamdarshi I have requested changes, but they are all style-driven things so should be easy to apply.

**Comment by kdahlquist** [comment]
As noted as a comment on PR #458, this needs to be on hold due to potential merge conflicts that we don't have time to resolve by tomorrow.

**Comment by kdahlquist** [comment]
I was finally able to review this one.  The bug is fixed that originally started this issue.  There is one case that is described above that triggers a Warnings modal:

* workbook only has "network" sheet with real numbers: give a warning to the user and render in black. 

The warning is triggered, but there are no specific warnings given, it only has the general language, which will be confusing to the use because there is no stray data.

@NAnguiano noted this in a comment above, so I won't reiterate it.

I'm throwing it back to @mihirsamdarshi to fix.  This should take priority over the grey threshold work, but not the merging of the branches.

**Comment by kdahlquist** [comment]
beta 2.1.5 doesn't have this fix, it needs to get put back.

**Comment by kdahlquist** [comment]
At the meeting, we decided that the user should only get one warning (instead of for all edges) about having a wrong sheet name.

**Comment by mihirsamdarshi** [comment]
got the warnings to show up, now working on getting only one warning to show up

**Comment by kdahlquist** [comment]
I've looked at this with the original file that caused the opening of the issue and that file is now rendered properly according to our decisions as to the behavior and the warnings show up properly.

_However_, there is a different issue when you have a "network_optimized_weights" sheet with all the same weight values.  I will open a separate issue for that.
