### ISSUE TITLE
npm install GRNsight

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#361]
We want to be able to "npm install grnsight"

First step is to review documentation on the wiki and set up your development environment.

https://github.com/dondi/GRNsight/wiki/Library-Requirements

**Comment by dondi** [comment]
Some background on this task: GRNsight is sort of an unconventional `npm install` because it is a web app. Most of the time, it suffices for a user to visit the GRNsight website in order to use it. `npm install` is for parties who are interested in running their own instance of GRNsight's servers.

Thus the overall intent of this task is more about documenting and clarifying what it means to "npm install GRNsight." This may include some research on other existing npm packages which are also web servers like GRNsight or looking at places to include documentation that will help clarify what it means to install GRNsight via npm.

**Comment by dondi** [comment]
Regarding the wiki page on Library Requirements: the npm install page for GRNsight, https://libraries.io/npm/grnsight, appears to extract those dependencies automatically. This might be something good to look into in the future, so that the Library Requirements page does not need to be maintained.

**Comment by ebachoura** [comment]
After a fresh install of GRNsight (after npm install in all three locations), Eileen and I both got errors that moment was not installed with the rest of the modules.

**Comment by eileenchoe** [comment]
@ebachoura and I have successfully set up our development environment. 
We updated the **Running the Applications** wiki page to reflect the most current process for npm installing the dependencies and running a local version. @NAnguiano updated this today in beta, so that npm install only needs to be done once in the GRNsight directory. @ebachoura tested this and it is working.
Additionally, the **Library Requirements** have been reviewed and edited to reflect the most current versions.

**Comment by ebachoura** [comment]
There is no documentation currently describing that GRNsight is available via <code>npm install grnsight</code>. @eileenchoe and I think that it may be appropriate to dedicate a wiki page (possibly under the "Instructions" section) describing what it means to "npm install grnsight" for developers who are interested. We have tested npm install grnsight, and have noted a few additional steps that are required to fully run a local version of grnsight using this method, as opposed to the process described on the **Running the Applications** wiki. 

Upon research, we've identified a similarly scoped project, [Dalliance (a genome viewing application)](github.com/dasmoth/dalliance) which is also a web app available via npm install. Instructions for developers to run a local version of this web app is documented [here](https://github.com/dasmoth/dalliance). Dalliance uses almost the exact same structure as GRNsight, meaning that, to be a developer, you must git clone Dalliance, npm install at the root, and then you can run your own developer environment. We didn't find any web apps that used 'npm install _______' to install a dev environment of their app.

**Comment by kdahlquist** [comment]
Long story short, please write the documentation (icing on the cake). (in the meantime, please fix up the home page of the wiki)

**Comment by kdahlquist** [comment]
@kdahlquist and @dondi need to confer on this one one more time because I can't remember the conclusion for this one.

**Comment by dondi** [comment]
For later confirmation, I think the first paragraph of @ebachoura most recent comment above will suffice for this. The Dalliance example that was found only talks about running the web servers locally for development purposes. Our `npm install grnsight` version actually _can_ run as local web servers without developer intent. So I think a description and explanation along the lines of @ebachoura’s first paragraph will be the way to go.

To be discussed with @kdahlquist further before confirming this as a task…

**Comment by kdahlquist** [comment]
OK.  Let's try to settle this task on Monday.

**Comment by kdahlquist** [comment]
@NAnguiano needs to update wiki https://github.com/dondi/GRNsight/wiki/Running-the-Applications with new way of installing and team needs to sign off on issue #414.
