### ISSUE TITLE
Need multiple GRNsight servers to show current work (beta, gamma, delta, etc.)

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#388]
@kdahlquist and @dondi talked about this and didn't resolve it, but we have an issue that @anuvarsh has control of the beta server so if anyone else wants to push something to beta, it has to go through @anuvarsh .  I had the idea of just having multiple "beta" servers called "gamma", "delta", etc. so that different subgroups working on different forks could put something up on the server for testing and comment.  @dondi mentioned the idea of virtual servers, but I'm not sure how that would work technically.  Would @dondi please comment so we can figure this out soon?

**Comment by dondi** [comment]
So my understanding of this was actually that this is addressed by the new workflow in #382. Whenever a team member gets to a milestone that is ready to show, they would merge their work into `beta` then ask @anuvarsh to refresh the `beta` deployment. This does not incur the need for additional servers (virtual or otherwise) and stays consistent with how #382 allows multiple forks with periodic merges into the on-going `beta` branch.

**Comment by kdahlquist** [comment]
The problem with this is that @anuvarsh is the bottleneck for refreshing the server and it makes it harder to work asynchronously.  Maybe we could have a "gamma" that @NAnguiano owns so that things can move a little faster?

**Comment by dondi** [comment]
I can set something up where the beta files are something that everyone can update. That would mean giving everyone a common user (like `grnsight-beta`?) and then anyone can just login as that user when there is a need to refresh the beta. Would that address the issue?

**Comment by kdahlquist** [comment]
Yes, that sounds like a great solution!  Let us know when you've had a chance to do it.

**Comment by dondi** [comment]
OK let me see if I can rig it up sometime this weekend.

**Comment by dondi** [comment]
OK, a `beta` user has been created (I dropped the `grnsight` figuring it’s redundant) and have transitioned the servers to now be running off that account.

To be able to login, I need to be given an SSH key that is properly installed on an intended `beta` user's computer. Once I have installed that key, one can connect as `beta` with this command:

    ssh beta@grnsight.cs.lmu.edu

The repository clone is in the _GRNsight_ directory. All other activities remain the same, consistent with [what’s in the wiki](https://github.com/dondi/GRNsight/wiki/Server-Setup):
- Update the branch as needed by doing a `git pull`
- The servers are running in separate `screen` sessions
- `screen -r` to examine/restart the processes as needed

Because @anuvarsh’s key was already in the system, she should be able to successfully do `ssh beta@grnsight.cs.lmu.edu`. So actually @anuvarsh, you would be a good person to do an initial test to verify that you can get in as the `beta` user and see the screen sessions and processes.

For everyone else, the GitHub guide is a pretty good one for generating SSH keys: https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/

…just replace the very last step about adding the SSH key to GitHub with “give the public key to @dondi” :)

**Comment by anuvarsh** [comment]
Did the initial test and I was able to access both of the current screen sessions and processes.

**Comment by kdahlquist** [comment]
Has @NAnguiano then pushed her version to the beta server so I can see it live?  The beta page says it was updated in September of last year.  It would be great to be able to see the features in advance of the meeting tomorrow morning #389.

It seems like we need another checklist so that we know that all developers have taken the necessary steps to access:

- [x] @anuvarsh 
- [ ] @NAnguiano 
- [ ] @mihirsamdarshi 
- [ ] @yshin4 
- [ ] @eileenchoe 
- [ ] @ebachoura

**Comment by dondi** [comment]
Everyone but @mihirsamdarshi did this (and got shown how to update and restart the servers) on Thursday evening, so I checked them all off but one.

**Comment by mihirsamdarshi** [comment]
Reviewed all changes

**Comment by kdahlquist** [comment]
This can be closed, then.
