### ISSUE TITLE
Make the arrowheads larger for unweighted and thinnest weighted edges: fix tips going behind nodes

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#392]
Since the GRNmap team is using GRNsight extensively, one thing I've noticed is that the arrowheads for the unweighted and thinnest weighted edges are actually pretty small and hard to see.  We have trouble distinguishing whether an edge is incoming or outgoing from a node.  The arrowheads will need to be larger for these cases; I don't think we will need to enlarge the ones for thicker weighted edges.

**Comment by yshin4** [comment]
@kdahlquist 

I made a change so that the small arrowheads look bigger for: 
1. the thinnest ones for weighted graphs and
2. all the unweighted graph
and the result looks as below. First, two images are how it was before, and last two are after the change I made is applied. Please tell me if there should be any other modifications regarding this issue. 


Before
![image](https://cloud.githubusercontent.com/assets/16246811/24937653/ffb182b0-1ee6-11e7-90ca-a7684639f5c9.png)
![image](https://cloud.githubusercontent.com/assets/16246811/24937657/08361784-1ee7-11e7-80aa-452b5dc4a11b.png)

After
![image](https://cloud.githubusercontent.com/assets/16246811/24937666/14901e12-1ee7-11e7-855f-a2ac7749ec61.png)
![image](https://cloud.githubusercontent.com/assets/16246811/24937669/1e1a4ef8-1ee7-11e7-832d-a93145d622f7.png)

**Comment by kdahlquist** [comment]
This looks good.  The final test will be when I can see this "live" on beta.  I note that in the screenshot above that the self-regulatory arrowheads are no longer centered, though.

There are some test files that were set up to display all the possible edge widths for a weighted graph.  You should use those when making adjustments so that you can see how what you are doing affects all of the possible end markers.

These files are actually a little too complicated to hone in on the specific issue involved, so I edited the one called "check-self-referential-widths.xlsx" to show how to construct a test file that facilitates checking just the widths.

I'm attaching the modified file here, with a screenshot of its output
[check-self-referential-widths.xlsx](https://github.com/dondi/GRNsight/files/917890/check-self-referential-widths.xlsx)

![check-self-referential-widths-output-v1 18 1](https://cloud.githubusercontent.com/assets/6463867/24980204/1ef651a0-1f8c-11e7-9d9e-dd4f8bab9325.jpg)


 plus one I made for labels of all possible lengths of I's and W's.

[I-and-W_unweighted.xlsx](https://github.com/dondi/GRNsight/files/917893/I-and-W_unweighted.xlsx)

I further note that I think we have 14 bins for widths (but I'm not sure), so I just started with 14 and incremented the width size down by integers until I got to decimal places.  I'm not sure exactly if this strategy is hitting all the bins, but this is the idea.  As you can see, the grey edges actually turned up as two different widths, one slightly thicker than the other.  We probably need to fix this  so that all grey edges have the same width.  I'll begin another issue for this one.

**Comment by yshin4** [comment]
Note for me: 
making arrowheads larger is done.
However, still have to work on 1. centering the arrowheads and 2. #437 from on.

**Comment by yshin4** [comment]
@kdahlquist Thank you for the super useful files.

![image](https://cloud.githubusercontent.com/assets/16246811/25161281/efd079f8-246f-11e7-95bf-1de48dcd2d9f.png)

This is how it looks after I modified the number values.

**Comment by kdahlquist** [comment]
These look centered to me now.  However, it looks like the very tip of the arrowhead (the point) is getting a little hidden behind the node box, when the exact tip should just touch the box.  This is more pronounced when the edges/arrows get smaller, like smaller than G08 or H07.

**Comment by kdahlquist** [comment]
I looked at the version now live on beta.  I like the size of the arrowheads now.  However, the think I commented on above is definitely happening.  The very tip of the point should just touch the box edge (behavior currently on master), but on v2.0.5 on beta, the arrowhead tip is going underneath the box, not just for self-referential, but for node-to-node edges.  This is probably an artifact of making the arrowheads bigger.

This shows the value of me being able to look at something live.

**Comment by kdahlquist** [comment]
@yshin4, this issue is a lower priority than #318. I labeled it for the next release because the work you have done to this point will be included even if we need to do some further tweaks later.

**Comment by yshin4** [comment]
Note for me when I return: 

The position of the arrowheads can be modified by changing the refX attributes of the marker in the graph.js file. Depending on how high or low the value is the tip of the arrowheads gets either hidden beneath the box or gets off centered from the self pointing circle (stroke)

**Comment by kdahlquist** [comment]
De-labeling this "for next release" because we've reached a stopping point for now.

**Comment by yshin4** [comment]
After talking to dondi, it seems like there is no algorithmic function in svg that would fix the issue. For such reason, I am changing the refX and refY for arrowheads on self referencing nodes. It is a tradeoff between centering the arrowhead and making their tips not go underneath the box. I am tweaking the values manually to minimize off-looking arrowheads and to balance  the arrowheads so that it can be centered while having the lease amount of tip go underneath the box.

**Comment by yshin4** [comment]
Posted a merge request.

**Comment by kdahlquist** [comment]
I've reviewed this as well.  Like with #318, I just want to make sure that the appropriate test files have been committed before closing.

**Comment by yshin4** [comment]
pushed.

**Comment by kdahlquist** [comment]
My comment is the same as for #318.  What test files should I be looking for on the beta branch?

**Comment by dondi** [comment]
Completed, with test files, and now on the `beta` branch.
