### ISSUE TITLE
Implement preference for hard or adaptive drafting board size

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#396]
If the user has set a hard drafting board, then we are done--i.e., the nodes will bump up against the boundary and that's OK (current GRNsight behavior).

If the user has set a _adaptive_drafting board, then when the user loads a GRN, @NAnguiano will implement an algorithm that detects when nodes hit the edge of the drafting board and will expand it gradually (Issue #398).

**Comment by NAnguiano** [comment]
This is fully functional on my fork.

**Comment by kdahlquist** [comment]
Adding "review requested" and assigning to @kdahlquist.  Will close once pull request #415 is accepted and the functionality is live on beta.

**Comment by kdahlquist** [comment]
So, the radio buttons for fixed/adaptive are greyed out in Firefox (upon loading GRNsight beta) so I can't change them (adaptive is chosen).  The version of Firefox I have is 52.0.2 (32-bit).  

The buttons are available for selection in Chrome until I load a graph, then they are greyed out.  Reloading the page makes them available again, but that has the unpleasant side effect of wiping out my graph.

@NAnguiano and I discussed this in our meeting today; I think we agreed that it would be desirable for the user to be able to switch between them after a graph is loaded.  Going from fixed to adaptive should be no problem, but moving from adaptive to fixed is a problem if there are parts of the graph outside the viewport.  I suggested that a warning should appear when going from adaptive to fixed that the graph would have to reload and did the user really want to do that.

@dondi, please feel free to chime in on this design decision.

I'm taking off review requested and adding bug until the Firefox thing is fixed.

**Comment by NAnguiano** [comment]
I recall us having this issue in firefox before, particularly when it came to it storing the previous values of the sliders after the page was reloaded. I think I remember how it was fixed, so I'll get to fixing that now.

**Comment by kdahlquist** [comment]
I'm not sure which issue to put this comment on, so I'll put it here.  It relates to resizing the viewport/drafting board when the viewport/drafting board is fixed.

For example, if I choose the option of a drafting board fixed to the viewport, and a small viewport and then load a graph, it behaves properly--the nodes stay within the boundaries of the viewport.

However, if I then select medium or large for the viewport, only the viewport changes size, not the drafting board, even though the drafting board size should be fixed to the viewport size.  I.e., changing a fixed viewport/drafting board from small to medium should give me more room to move things around on the board.  It is not doing this now, it is actually acting like I zoomed out and showing me the grey box.

It is obviously a problem if you start with a large bounding box/viewport that is fixed and try to go smaller.  We wouldn't want to allow genes to go outside the boundary in that case.

There is a lot of "devil in the details" for this.  We need to be sure that we've thought of every permutation of the order in which you can select adaptive/fixed, size choice to make sure it is behaving consistently with expectations.

**Comment by NAnguiano** [comment]
The bounding box on fixed graphs now resizes when you choose a different graph. I'm in the process of allowing a switch between hard and adaptive after a graph has been loaded now.

**Comment by NAnguiano** [comment]
Ok, on my fork you can now switch between fixed and adaptive.

**Comment by kdahlquist** [comment]
Any timeline on when #395, #396, and #399 will be updated on beta?

**Comment by dondi** [comment]
Outside of the labeling/visual suggestions that I posted in #411, the interaction I see in beta 2.0.3 feels OK to me. The only other change I might consider, but then again this might complicate things unnecessarily, is to actually make the two sizes distinct in the UI: i.e., "Graph Boundaries" can be small, medium, large, and "Viewport" can also be independently small, medium large.

If this distinction is made explicit, then "Fixed" can now be interpreted to mean that there _are_ graph boundaries to begin with. "Adaptive" means that there aren't any graph boundaries.

With this alternative model, the UI would work something like this:
- Viewport Size behaves like it does now
- Instead of Adaptive vs. Fixed, we can instead have a checkbox that says "Restrict network boundaries." When this checkbox is not selected, the behavior is the same as having chosen Adaptive in the current version.
- When this checkbox is checked, the behavior is the same as having chosen Fixed in the current version. The change is that checking this checkbox will now also display choices for Graph Boundaries size—also Small, Medium, and large.

So the only functional change of the above suggestion is that it now becomes possible to have a large boundary within a small viewport, or other combinations. This brings us close to the "box within a box" approach that we see in apps like Adobe Illustrator.

Again I'm just throwing this out there as a possible tweak to how we present the user interface; I think the functionality is where it should be. The issue I'm tossing about is how to present this functionality to the user and what terminology to use, so that the user understands the interactions between these two concepts as intuitively as possible but also with flexibility on how to configure the graph's display.

**Comment by kdahlquist** [comment]
I like @dondi's alternative model for the UI.  It clearly separates the choices for the viewport/bounding box and the interaction between them.  To recap and combine the ideas with #411:

* Viewport size behaves like it does now (three choices, small, medium, large that are automatically selected based on browser detection.
    * Add to this, an option to  "Fit to Window (w x h)" —Choosing this option will lock the right and bottom of the viewport to the exact boundary of the browser window, and will resize as the window resizes.
    * Question: what does @dondi mean by "w x h", those literal letters or substituted with the size of the browser window at that instant.  Are those values needed and doesn't that make things a little complicated?
* Instead of Adaptive vs. Fixed, we can instead have a checkbox that says "Restrict network boundaries." When this checkbox is not selected, the behavior is the same as having chosen Adaptive in the current version.
    * Except that the label should say "Restrict graph bounding box to viewport" to use our preferred lingo.
    * When this checkbox is checked, the behavior is the same as having chosen Fixed in the current version. The change is that checking this checkbox will now also display choices for Graph Bounding Box size—also Small, Medium, and large.

It occurs to me that once we finally settle all this out, we definitely need a list of permutations for selecting the options so that we can systematically go through the possible options to see if it is behaving as we want.  I could have sworn I saw a bug where the force graph parameters slider values weren't changing when I slid them, but now I don't see it.

I also think that our discussion might be easier to follow if we collapse issues #399, #411, and this one into a single issue since the are all related.

**Comment by NAnguiano** [comment]
Will be getting started on this at the next work session. I just wanted to point out this tiny thing that really highlights the impact of the fixed/adaptive change.

This graph looks like nothing special when the setting is fixed:
![screen shot 2017-04-18 at 7 55 18 pm](https://cloud.githubusercontent.com/assets/6444156/25161484/113cb0f6-2471-11e7-9bab-990db525e318.png)

But when it's adaptive? It looks like this
![screen shot 2017-04-18 at 7 51 06 pm](https://cloud.githubusercontent.com/assets/6444156/25161490/172c32c0-2471-11e7-9320-9260e27f025a.png)

I find it extremely pleasing to look at and thought you guys may enjoy seeing how much of a difference it makes :)

**Comment by kdahlquist** [comment]
Agreed!

**Comment by NAnguiano** [comment]
So I somehow managed to miss a really obvious bug in the resizing. When you go from Small -> medium then back to small, it continues rendering the graph as if it's large. So it draws it outside the viewport.
![screen shot 2017-04-19 at 11 43 01 am](https://cloud.githubusercontent.com/assets/6444156/25199955/721ec158-2501-11e7-9816-ea75e65d537a.png)
I'm pretty sure this wasn't happening before. Either that, or I somehow just managed to really miss something. So I'll be fixing this up ASAP.

Additionally, there's a bug where if you do things in the following order: 
Load Graph -> Set Fixed -> Change Size -> Set Adaptive -> Change Size -> Set Fixed
It results in a bounding box of the wrong size. Like this small small bounding box that appears as a medium bounding box.
![screen shot 2017-04-19 at 1 15 54 pm](https://cloud.githubusercontent.com/assets/6444156/25200247/7557e506-2502-11e7-9d51-35a649d6953b.png)
I initially thought that it was drawing the former size shown, and in a lot of cases it is. But I've had a few times that I managed to have it display bounding box sizes that were weird hybrids of the two sizes - like the width of the original size with the height of the actual size. Either way, this also needs to be fixed.

So I'll make some headway on these two bugs as well as implementing all of the above changes today at the work session.

**Comment by NAnguiano** [comment]
I think everything on this issue is done and included in PR #459.

**Comment by NAnguiano** [comment]
@ebachoura @eileenchoe You guys are up now to break my code! The main permutations that would need to be checked are around the Fixed/Adaptive checkbox, as well as the size changing. My initial thought tells me that zooming/scrolling won't be a big issue until I refine and fix the zoom and scroll functionality (#399), but the stuff from #411 and #396 is fair game.

**Comment by kdahlquist** [comment]
There's a lot of good times to be had by loading a demo and just clicking and unclicking the "restrict graph to viewport" check box a lot.

So, let's ask it this way, what is the intended behavior?
* Default behavior is to have it unclicked, i.e., adaptive bounding box--I'm OK with this choice.
* Does checking/unchecking the box automatically trigger a reload?
    * Clearly, if the graph has moved beyond the viewport (unchecked) and the box is then checked, it's going to have to reload to get it inside the box again.  This appears to happen.
    * Even if the graph has not moved beyond the viewport, going from unchecked (adaptive) to checked (fixed) appears to trigger a reload.  I think this warrants discussion.  I'm open to the idea of checking/unchecking always triggering a reload for simplicity's sake, but in this case  it seems unnecessary since the graph is already entirely within the bounding box.
    * However, if we go the other direction from checked to unchecked (fixed to adaptive), should this automatically trigger a change?  I think, yes, in this case as well since the graph may not have fully relaxed before.
        * This is where it gets interesting, though.  If I go from checked to unchecked (fixed to adaptive) while the graph is still in the process of relaxing, the graph will indeed start drifting beyond the confines of the bounding box.
        * However, if I go from checked to unchecked (fixed to adaptive) after the graph has settled and stopped moving, unchecking the box does not do anything, even if all the nodes are smushed up against the bounding box.  Here, I think there's an argument to be made for triggering a reload automatically in this instance.

So, I leave it for class discussion to reverse a couple of behaviors I've observed: i.e.,
1. If the graph is entirely within the bounding box, going from adaptive (unchecked) to fixed (checked) should not trigger a reload since the graph is already inside the box.
2. Going from checked (fixed) to adaptive (unchecked) after the graph has relaxed and stopped moving should still trigger a reload.

I note that I was just looking at the action of checking/unchecking the adaptive/fixed box and not the interaction with scrolling/zooming/viewport size.  The size was detected to "small" on my laptop and I didn't mess with that.

@dondi or anyone else care to weigh in?

**Comment by kdahlquist** [comment]
OK, another observation.

There seems to be a slight tendency for an adaptive graph to drift downwards instead of upwards.  By playing around with the sliders, I can eventually get the graph to go off the top of the viewport, but when it is just loading, it seems to want to go down instead of up, in fact leaving "white space" to the top of the viewport, in favor of drifting beyond the viewport at the bottom.

Just something I've noticed.  Not really sure that this is even an issue.

**Comment by NAnguiano** [comment]
It doesn't actually reload - the force just restarts. So any locked nodes will remain locked. They'll just be pushed by the bounding box back in bounds if they were locked out of bounds. It seems to reload because the dramatic change in force and position sends all the unlocked nodes into a frenzy for a bit. Adaptive graphs are almost always larger than fixed ones (especially with the current size of our demos and on the smallest size), so it will almost always look as though it has reloaded - but if you lock a few nodes, they should remain locked.

If they've actually come to complete rest, the graph won't move when it is changed from fixed to adaptive. That's because I'm pretty sure that when the graph completely stops moving, the tick function stops running. So it doesn't actually stop and check to see if it should move. Wiggling a node around will cause the graph to "wake up" and start adapting. 

I'm hesitant to actually trigger a full reload in this situation, because should the user have locked nodes, they'll no longer be locked anymore. Since it's not reloading in the first place, I'm not sure if that changes anything. 

As for the second issue... I took a brief look and found something interesting.

The reason it drifts downwards is actually because the graph isn't able to adapt upwards or to the left. It's just really good at seeming like it is. When the bounding box increases in size, it automatically expands to the right and down - not to the left and up. In order to mimic the behavior of having it expand upwards and leftwards, I think I'd need to apply a translate as well as a width/height increase. I never actually thought about that, but I think now that I'm aware of it, I'll go ahead and implement that. Shouldn't be too difficult, with any luck.

**Comment by kdahlquist** [comment]
Thanks for the explanation.  To summarize, it's not a reload, but a re-application of the force.  So I think my questions still remeain, but just substituting applying the force instead of reloading (if that's possible).

I suspected that the top and left behaved differently, but wasn't sure.  That is something that's not urgent, so I wouldn't necessarily spend too much time messing around with it.

Unfortunately, this is going to be all for me right now, I need to head off to bed.

**Comment by eileenchoe** [comment]
Just completed about 30 min worth of permutations of the following options: (1) load graph, (2) check Restrict graph to viewport check box, (3) uncheck Restrict graph to viewport check box (4) changing viewport smaller => larger, (5) changing viewport larger => smaller (6) change from current viewport to fit to window (7) change from fit to window to another viewport size (8) reload graph. Tried at first to keep track of the permutations, but because of the combinatorial explosion, I think that verifying these permutations just takes lots of random iterations with an intent to hit all 8 of these options in a variety of ways (let me know if I'm missing some options). 

Here are some general observations:
- I haven't hit a case where the bounding box wanders outside of the viewport yet (yay!)
- I've noticed that when checking/unchecking the Restrict graph to viewport, the cursor on the zoom bar goes through some drastic changes. Is this intended behavior? This is most pronounced when you do the following: check Restrict graph to viewport check box > load graph > uncheck Restrict graph to viewport check box. 
- Fit to window works great horizontally, but its not "fitting to window" vertically, moving the zoom and controls way down the page, making it inaccessible without a page scroll. Can you make the fit to window fit the aspect ratio of the screen?

**Comment by kdahlquist** [comment]
@NAnguiano says that when the graph boundary is fixed to viewport, then the user can't zoom in (i.e., make graph bigger); as a result, what the center is on the zoom bar is different whether the option to be adaptive or fixed to viewport is chosen.

@kdahlquist says that this is fine, we just need to document this behavior.

@eileenchoe says that she's uncomfortable with being able to grab and move the graph when clicking on the "white space" surrounding the graph.  @kdahlquist is OK with this behavior, but agrees that the hand is a better icon for the mouse pointer that indicates that its action will grab and move the graph.  I note that when you hover over a node, the pointer turns into crosshairs to indicate that clicking now will just select the node and not the whole graph.

The way things work now is that scrolling or grabbing the graph moves the entire bounding box to a different relative location within the viewport.

Thus, when "restrict graph to viewport" is selected, to be true to this label, we can't allow scrolling or grabbing of the graph because that would bring the bounding box out of alignment with the viewport.
* At 100% zoom, no scrolling/grabbing is allowed
* Not allowed to make graph bigger anyway
* If graph is smaller (zoomed out), then you can scroll/grab, but you can't move the bounding box beyond the edge of the viewport (top, bottom, left, right).
    * if subsequently you do zoom in, the bounding box is going to get pushed so that it never goes outside the viewport, so that it will end up at 100% flush with all four sides of the viewport.

@kdahlquist says that fixing the zoom to come from the center and not from the upper left is not in the critical path at this point.

**Comment by kdahlquist** [comment]
All remaining tasks have been documented as individual issues, #469, #470, #471, so closing this one.
