### ISSUE TITLE
Implement viewport scrolling and drafting board scaling

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#399]
Zoom is a separate multiplier that is applied to the entire drafting board once its size is set (control is slider with a bar at 100%)
Through all of this, viewport remains constant, scrolling is the same as translating the viewport's origin and zooming is changing the scale factor applied to the drafting board.

**Comment by NAnguiano** [comment]
Zooming and scrolling is functional on my fork with the mousewheel as well as click to drag. Now to get it working with buttons.

**Comment by NAnguiano** [comment]
This is now done on my fork. The current implementation doesn't look pretty, but it works.

Since #395, #396, #397, #398, and #399 are all done, it's definitely time for another PR. Trying to figure out whether I want to add all of this code to a new PR, or just add it to the existing one. After I meet with @yshin4 tomorrow, I'll make a new one containing all of this new stuff.

**Comment by kdahlquist** [comment]
@NAnguiano, I'm in the office all Tuesday afternoon if you need me to look at something with respect to  #395, #396, #397, #398, and #399.  Otherwise, I hope that the PR can be completed and the new work up on the beta server in advance of our meeting on Thursday so I can take a look and comment.

**Comment by NAnguiano** [comment]
@kdahlquist I'm in class right now, but it gets out at 2:30. I can come by right after that. Regardless, the PR should be up tonight after my meeting with @yshin4.

**Comment by kdahlquist** [comment]
Sounds good.

**Comment by kdahlquist** [comment]
@NAnguiano and I met and she showed me the implementation on her laptop because we are waiting for pull request #415 to be accepted.

Right now, zooming is enabled, either by clicking the (+) and (-) buttons or by using the mouse wheel.
* She will turn the buttons into a slider with a marker at 100% (scale of 1) so that the user can easily return to 100%.
Right now, scrolling is enabled, either by clicking on the up, down, left, right buttons or by left-clicking anywhere within the bounding box (but not on an individual node) and dragging.
* She will turn the text on the buttons into arrows and add a button in the middle of the arrows to return the graph to center (maybe with a compass icon?).

We discussed some issues related to #398 and decided the following:

* When the viewport is set to adaptive, zooming and scrolling are enabled (as per specification)
* When the viewport is fixed:
    * zooming is enabled, but only to zoom out, i.e., scaling factors between 0 and 1.  Scaling factor of >1 is not allowed.
    * a light grey rectangle will be added around the drafting board bounding box to indicate why a user can't drag a node further than the drafting board boundary when zoomed out.
    * scrolling will also be enabled, but the user can't scroll past the viewport.

@kdahlquist will check in with @dondi at the Wednesday GRNmap coding meeting to make sure that these decisions are OK in terms of interaction design, or he can chime in on this issue.

**Comment by kdahlquist** [comment]
So, I'm seeing some unexpected behavior on beta 2.0.2 on Chrome (I can't test this on Firefox because I can't choose fixed layout, #396.

I select fixed and small viewport options.  When I load a graph, the buttons (scrolling, zooming) are not visible, but I can zoom with the mouse wheel and left-click and drag to scroll.

The grey bounding box is visible, which is good.  However, it is letting me zoom in (scale >1) which we *didn't* want, in addition to zooming out (scale 0 to 1), which we *did* want.

Labeling this as a bug now.

**Comment by NAnguiano** [comment]
You now can't zoom in on fixed graphs. 

I'm in the process of trying to figure out how to restrict panning in a way that's intuitive, so that's in progress.

**Comment by NAnguiano** [comment]
I haven't quite figured out a way to restrict panning yet, but almost everything else has been done. 

There are a few known functional and visual bugs right now, that I just need to figure out a clean way to handle:
- When you zoom in with the range slider, it doesn't zoom to the center. It instead zooms to the top right corner. This is because the center function on zoom only works on mousewheel scrolling, not regular scrolling. I'm now trying to figure out a way to imitate that behavior for the slider, without needing to do any overly complicated math that may slow it down. I found a way that I think will work, but it exists only in theory right now. I'll begin an attempt at an implementation soon.
- Because of the way that scale works, an equal scale on both sides (as in, you can zoom in and out the same amount), I believe corresponds to a scale of 0.25 to 4. I haven't yet figured out a way to make 0 the center, and have the negative and positive scales go equal distance on both sides, even though the left side would consist of only 75 steps, and the right side would consist of 400. Again, I think I have an idea for how to do this, but I need to just sit and think about it for a bit longer.

Pull request is in.

**Comment by kdahlquist** [comment]
Does a log2 transform help with the scaling?

**Comment by NAnguiano** [comment]
What behavior is expected when it comes to panning/arrow key presses when a graph is fixed? It says "scrolling will also be enabled, but the user can't scroll past the viewport." But the viewport is the entire visible area of the graph, so you can't really scroll past it. Do you mean that you can't scroll past the drafting board, so that it is always in the viewport?

**Comment by dondi** [comment]
The scrolling and zooming behavior in beta as of April 1 (v2.0.3) generally feel right to me. In fact the onscreen controls for scrolling (arrows plus center button) don't seem necessary. The zoom slider works as I would expect it, though perhaps it can be supplemented with an actual number (100%, 50%, etc.) to give the user additional information.

To address the question of "scrolling off the viewport," what if we implement a "Center Graph in Viewport" button? This would be the same as the "sun" button that is present right now, but doesn't change the zoom level. The "sun" button's current functionality can be a "Fit the Graph into the Viewport" button. These buttons can potentially release the feeling of unexpected restrictions in scrolling and zooming, but give the user an "easy out" to get things back in order with a single click.

**Comment by kdahlquist** [comment]
To respond to @dondi's comments:

* I think we still need to keep the onscreen controls for scrolling and centering.  I think that different people have different modalities for interaction and some might prefer to use the buttons in the same way that I click on the down arrow button to use the scroll bars in Word or my browser.  Clicking is useful in that it increments in a discrete unit that might be hard to control with just grabbing and moving with the mouse.
    * I would go so far as to say that we should be able to use the arrow keys as well.
    * I think that the arrow buttons need to be fatter or have a box around them, so that their click area is obvious.
    * Also, my mouse pointer icon turns into a cursor (like for editing text) when I hover over the arrow keys, which is confusing.  The mouse pointer should still be an arrowhead.
* The zoom slider definitely needs a label.  I would argue that we already have a "style" for sliders for the force graph parameters and that the zoom slider should "somewhat" adhere to this convention.  I say somewhat because we don't want to load the graph up with text, but indicating the upper and lower bound and the actual setting would be good.
* I thought we were going to have a bar indicating 100% or scale of 1 that the user could click on to return the zoom back--ah, now I see that the "sun" button returns the zoom to 100%.  I agree with @dondi that the sun button should mean to center the graph in the viewport (that's what I actually had meant before) and not affect the zoom.  A vertical bar on the zoom slider should return the zoom to 100%.
* Then, yes, I agree that it would be nice to have a single button to fit the graph to the viewport, but that one would be separate from the sun button.  To recap:
    * Sun button in middle of arrows, centers graph in viewport, but doesn't change zoom.
    * Vertical bar on slider returns graph to 100%, but doesn't change position.
    * A third button both scales and centers graph in viewport, i.e., "fit graph in viewport".  I'm not sure what the iconography for this is, maybe it's a checkbox that disables the zooming/scrolling (but that then begs the question of how it is different from a bounding box fixed to the viewport.
* In general, the scale bar needs to be moved up and to the right a little bit so there is some white space between it and the viewport edge.
* I'll make one more observation:  I use my mouse wheel to scroll on the browser page.  Every time I load a graph using the adaptive setting, I'm surprised that scrolling the mouse wheel zooms the graph when I meant it to scroll my browser.  It might take me getting used to, but another option would not be to enable mouse wheel zoom until I click within the area of the viewport/bounding box.

**Comment by NAnguiano** [comment]
The sun button now centers without changing the zoom in PR #459.

The zoom slider has been behaving really unpredictably. I'm pretty sure I'm going to need to change the way zoom is currently being done, because I'm not getting the behavior from it that I want. I'm continuing work on that, but I wanted to get the features in issues #411 and #396 out just in case this took me longer than anticipated. I am actively working on fixing that though and making those UI changes.

**Comment by kdahlquist** [comment]
I agree with the incremental PR approach.  I'll take a look at the functionality as soon as we can get the PR through our approval process.

**Comment by kdahlquist** [comment]
All open tasks have been moved into other issues #465, #466, #467, #468, #469, #470, #472, so closing this one.
