### ISSUE TITLE
Preferences on css tags, string initialization, variable declarations, and function declarations.

### ISSUE THREAD

**Issue by NAnguiano** [dondi/GRNsight#425]
So we've decided on 4 spaces.

Now on to a few last things. If anyone can think of anything else they think is a good preference to poll, let me know.

First. In naming CSS ids and classes - camel case or dashes?
![screen shot 2017-03-30 at 3 09 09 pm](https://cloud.githubusercontent.com/assets/6444156/24529976/da6a1af8-1563-11e7-87fd-749c21fabd0e.png)

Second. When you create a string (or character), do you prefer single quotes or double quotes?
![screen shot 2017-03-30 at 4 15 07 pm](https://cloud.githubusercontent.com/assets/6444156/24530016/113b70d6-1564-11e7-9099-3cc517474651.png)

Third. When you declare variables, should we allow multiple variables to be declared at once? Or require a `var` before each one?
![screen shot 2017-03-30 at 4 29 26 pm](https://cloud.githubusercontent.com/assets/6444156/24530328/0f3bda76-1566-11e7-82fe-71889c8d2877.png)
The advantage of the latter version is that if you add an additional variable, you'll always be sure there are no syntax errors. But in the former, you'd have to remember to remove the semicolon, add a comma, and then add another semicolon. I've run into trouble with the multiple declarations at once syntax before.

Fourth. When it comes to declaring functions, do you prefer the function declaration syntax, the function expression syntax, or the named function expression syntax? Or all of them?
![screen shot 2017-03-30 at 4 24 28 pm](https://cloud.githubusercontent.com/assets/6444156/24530269/ba15e71c-1565-11e7-9e25-7b30eb29a30b.png)
Here, there's actually a functional difference between these types. That is, function expressions and named function expressions can only be called after their declaration, while function declarations can be called anywhere. So if function expressions were chosen as default, you'd have to make sure they were declared above where you want to use them. However, I understand that there are uses for both of them. That being said, right now in some files, there's a mix of function expressions and declarations everywhere, with no rhyme or reason. So if we chose to do multiple, there should be some sort of convention on when we use one or the other. For example, using function expressions in most places, but using function declarations for helper functions.

Here's a [form](https://docs.google.com/forms/d/e/1FAIpQLSdwQbI06G_m0fkq2qvZBy1yiMlJMkt6EJJUrjfBNdcqwyZMjQ/viewform?usp=sf_link) for you guys to fill out. One vote only for each, please. You can also post your preferences here in this issue. 

My personal choice, in order, is camel case, double quotes, require a `var` for each declaration, and allow both. Let me know what you guys like!

**Comment by dondi** [comment]
My personal choices are:
1. Spinal case (that's what it is sometimes called BTW when you separate words with dashes—like having a "spine" across the words) —many conventions adopt spinal case for HTML identifiers (I need to locate those links though)
2. Double quotes for string literals —because I use single-quotes for string literals that are identifiers (e.g., a CSS property or a property name I am accessing with square bracket notation)
3. Individual `var`s —because as variables are added and removed, it's easier to just copy-paste complete `var` declarations than worry about whether you now have to add a comma, or add a semicolon, or add a new `var` keyword, etc.
4. Nameless function expressions —because this makes functions feel the most like any other variable, which I prefer to think of them as (i.e., I prefer to think of a function as being no different from a string, in terms of how its value can be named and passed around)

Admittedly these are not absolutes. But when I write JavaScript, that’s how I write it.

**Comment by eileenchoe** [comment]
Voted. My preferences are dashes, double quotes, individual, and function expression!

**Comment by mihirsamdarshi** [comment]
Voted.

**Comment by kdahlquist** [comment]
I'm not going to vote, per se.  However, we had a big discussion about CamelCase vs. under_score on the GRNmap team and turned up this paper which says that the under_score (or in this case, presumably the dashes) is easier to read:
* Usability study of CamelCase versus under_score:  [Binkley, D., Davis, M., Lawrie, D., & Morrell, C. (2009, May). To camelcase or under_score. In Program Comprehension, 2009. ICPC'09. IEEE 17th International Conference on (pp. 158-167).](http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=5090039&tag=1)

**Comment by kdahlquist** [comment]
@yshin4 and @ebachoura are reminded to vote on their preferences on this issue so it can be closed.

**Comment by yshin4** [comment]
Voted.

**Comment by NAnguiano** [comment]
We're doing Camel Case for variables, Double Quotes for strings, no multiple declaration of variables, and prefer function expressions. Closing this up.
