### ISSUE TITLE
SIGGRAPH 2017 Conference Poster Submission

### ISSUE THREAD

**Issue by eileenchoe** [dondi/GRNsight#426]
Submission Deadline: Tuesday, 25 April 2017 22:00 UTC/GMT
http://s2017.siggraph.org/posters-submissions

Submission Components
- [x] Summary Statement
A single-sentence executive summary that introduces the achievements of your submission (50 words or fewer - proofed - suitable for conference publicity).
- [x] Abstract
- [ ] Poster Draft (optional)
- [x] Representative Image
- [ ] Video (optional)

**Comment by kdahlquist** [comment]
@eileenchoe, please have a draft title/summary statement/abstract drafted two weeks in advance of the deadline for review.  Please note how many words the abstract needs to be in your list above.

**Comment by eileenchoe** [comment]
@NAnguiano and @eileenchoe met with @dondi to work on the abstract and get the latex formatting right. 

@kdahlquist can Nicole and I meet with you tomorrow at 12:30 (after your meeting with her at 11:30)  to over the draft?

**Comment by kdahlquist** [comment]
Yes, that works for me.  What is your word limit?  Or is it just what fits on one page?  What you have there right now is fine, but doesn't meantion SIF or GraphML, which the conference-goers might be familiar with, and also one of your major contributions as of this time.

Since version 1 is published, it can be referenced and you can talk about some of the improvements for 2.0 (unless there's really not enough room).  Generally conferences are where you present new stuff and we've done a lot to GRNsight since v1 was last released in August 2016.

**Comment by eileenchoe** [comment]
Yes, there is no word limit, but a page specification (2 pages max). Content formatting specification link is [here](http://www.siggraph.org/learn/instructions-authors) for reference.

**Comment by eileenchoe** [comment]
Finished a first pass of the abstract draft. I chose to focus on the subset of features in v2 which deal with the visualization and layout feature additions, to align with the graphics focus of the conference. @kdahlquist and @dondi can you review when you have a chance? Left "Separation of Viewport from Graph Bounding Box" and some conclusion space for @NAnguiano to fill out since this is your area of expertise :) @dondi I have a case of a runaway url that is bleeding into the second column of the first page if you could also take a look to try to figure out what in latex is causing that. Also, maketitle has a few errors I'm having trouble tracing, maybe this is causing it?

**Comment by dondi** [comment]
OK, this first comment is just about tech/errors/logistics:

* You’ll _love_ what it took to fix the `maketitle` errors (I will leave it to the diffs to show this) 😂
* URL handling is solved by loading up the `url` package, then wrapping any URLs around the directive `\url{......}`—nothing you were expected to know; just something that emerges with enough LaTeX exposure
* Even though it doesn’t show up yet, make sure the metadata is right. (I realize you probably lowered the priority on this for now, but I figured I’d note it now so we don’t forget) Make sure that entire segment after `\begin{document}` is accurate (i.e., include your email, list all of the authors, remove the sample doc authors, etc.)
* Something odd happened to the Tufte citation—it became Mulrow. Not sure how it turned out that way; Mulrow once wrote a _review_ of the book, but here we want the book itself. I’ve gone ahead and fixed it. (I used the BibTeX entry provided by the ACM Digital Library so it should be authoritative: http://dl.acm.org/citation.cfm?id=33404)

Those are all of the technical/logistical notes for now. The only to-do here is the metadata. I’ve fixed everything else.

**Comment by dondi** [comment]
Now some content notes:
* The abstract needs to reflect our new focus on v2, I think. It starts by saying “We present new features in v2…” but never quite gets there. I would suggest replacing the sentence:
    > GRNsight visualizations can be modified through manually dragging nodes or adjusting sliders that change the force graph parameters.

  …with a v2-specific sentence, maybe something like:

    > For GRNsight v2, the user was given greater control over the network visualization’s bounding box and viewport as well as the way edges and their weights are displayed.
* I think that it will be worth noting that v2 revises the default D3.js force graph layout algorithm even more than it originally did. Specifically, D3.js force graph defaults to a fixed bounding box—one of the very things that we have changed for v2. I think Section 2.1 would be a good place for it, something like:
    > The default behavior of D3.js’s force graph layout algorithm is to give the graph an _a priori_ bounding box. To accommodate the range of possible GRNs that GRNsight may display, we revised that algorithm so that the option for an adaptive, expandable bounding box can be chosen.

    (something like that…those are rough thoughts)
* I wonder if a screenshot showing the motivation for graph normalization would be useful. I’m thinking of something like two simple graphs, but each with distinctly different edge weight ranges (which can be made apparent by showing the weights). Without normalization, the thicknesses are virtually meaningless and will show how apples-to-apples comparison would be difficult. A second screenshot would then show how normalization can make the edges visually comparable. With minimal graphs, this can be made to fit within the two pages, I think. If we are really tight on room, the architecture diagram is expendable, I think, since it can be found in the PeerJ article.
* …speaking of which, we should probably cite our own PeerJ article here, to emphasize that this new abstract is clearly a _follow-up_ to that work, and not merely a rehash. Not sure where it best belongs…perhaps as a cite at the end of the first sentence of the _Introduction and Motivation_ section?

That’s mainly what I found.

**Comment by kdahlquist** [comment]
I agree with what @dondi said and would even go further in some of his comments.  I could try to help by directly editing, but I would need some guidance on what editor to use (would [Overleaf](http://www.overleaf.com) work?)

Since I can't see the metadata, I want to make sure that the author list and order is correct.  It should be:

Eileen J. Choe, Nicole A. Anguiano, Anindita Varshneya, Mihir Samdarshi, Yeon-Soo Shin, Edward B. Bachoura, John David N. Dionisio, Kam D. Dahlquist

Myself, Anu, and Mihir have affiliations with the Department of Biology and the rest of you all are affilated with the Department of Electrical Engineering and Computer Science.

* We need to have "v2" in the title, as in "New Features for GRNsight v2: a web application and service for visualizing models of small- to medium-scale gene regulatory networks"
* Like @dondi said, we need to cite the PeerJ article, and we need to be careful about self-plagiarism.  I see a lot of text that is very similar, if not identical, to that found in the published work.  Now, some of that is unavoidable, but we should try to make this a new work as much as possible.
    * There should be a citation at the end of the first sentence of the abstract.
    * There should be a citation at the end of the first sentence of section 1.
    * Anywhere where we are using language from the paper or discussing features of v1, we need to cite the paper.
*  Section 2.1 needs to be greatly expanded.  It makes a list of the new features, but does not explain why they are important (i.e., the motivation, except to say that they were requested).  For example, why did we need to make a larger viewport or make the bounding box adaptive to the graph?
    * I see that figure 1 was made using the "fixed" setting.  You can see that two nodes in the layout shown are bumped up against the bounding box/viewport.  When I layout demo 4 with the "adaptive" setting, usually something drifts outside the viewport.  Since this is actually a new feature, maybe it is something we should show in Figure 1?  Then it can be explained in the text that in v1, this graph would have been constrained, but in v2, it is allowed to fully relax.
    * This section also doesn't say anything about how the new features work.  We made design choices in terms of how we expect zooming and scrolling should work, what were they?
* For the edge weights and normalization, you need to explain more what these weights represent and why the user would want to either display or hide them.
* A little more detail needs to be provided for edge thicknesses in terms of separating what v1 and v2 does, and in terms of what is the biological explanation for the thicknesses.  I agree with @dondi that this could be shown in a simple figure; @anuvarsh made one for the LMU symposium presentation (although I would remake it so that the node boxes are not so squished)
* I also agree that we should lose the current Figure 2 in favor of the expansion of the discussion of the new features and new figure.
* You do need to reference the Figures in your text when you talk about them.  Figure 1 should be referenced when talking displaying the weights, for example.
* The legend for figure 1 needs to be revised (assuming the change to adaptive) to: "(a) The adaptive graph bounding box in GRNsight v2 allows the demo gene regulatory network to fully relax.  Zooming and scrolling options allow the user to see the entire graph when it moves beyond the viewport; (b) the user can manipulate the display of the graph through manual node dragging, and can either hide (b), or show (c) all the weight values, which display on the edges." 

There are many other places where I would suggest different wording.  Again, I could help by doing some direct editing, but need some guidance as to an editor.  Or, should I just copy the text into an issue comment or wiki and go from there?  Please advise.

**Comment by eileenchoe** [comment]
@dondi @kdahlquist thanks for the feedback. I have class until 2, so I'll be free shortly after to start going through your suggestions and making changes. @kdahlquist I'm not sure if Overleaf will work because I don't see an option to import the ACM template that is needed. I think it will be fine to copy the text into a wiki for content edits.

**Comment by kdahlquist** [comment]
I have class from now until 5:00, so I won't be 
able to work on it until about 9:00 tonight after 
my son goes to bed...Post a comment on this issue 
when you've got something for us to look at.

At 12:37 PM 4/24/2017, you wrote:

**Comment by eileenchoe** [comment]
Working on abstract with @NAnguiano right now. We've decided that Nicole will submit the abstract because for submission into the ACM Student Poster Competition, the submitter must be the primary contributor of the work. The deadline to submit is 3PM tomorrow. I have class starting at 10AM and Nicole has class starting at 11AM. We are willing to meet in the morning to finalize submission materials and submit. We are proposing meeting at 8AM. 

@dondi I've added the list of authors, but the ACM author template provided lists each author separately, this of course is taking up way too much space. Ideally, our names should be listed in a line, with a superscript denoting our affiliations, but I can't figure out a way to do this without it messing up the "ACM Reference Format" is generated beneath "Keywords." According to a FAQ post on http://s2017.siggraph.org/posters-submissions poster abstract submissions should not be color blind, so I've disabled the author blind setting.

**Comment by kdahlquist** [comment]
I would be interested in getting @dondi's take on 
this.  Eileen, since you are the one presenting 
at the conference, I'm still OK with you being 
the primary author, even though you came to the 
project late.  It is you who will be "judged" at 
the conference, sinc you are the one presenting the poster.

I'll take a look at whatever you guys have later 
tonight and make tweaks to the language as 
appropriate so that you can finalize it tomorrow morning.

At 04:02 PM 4/24/2017, you wrote:

**Comment by eileenchoe** [comment]
Included options for the sample representative image in the "representative images" folder, cropped and sized per guidelines specified [here](http://s2017.siggraph.org/representative-image-guidelines). They also request copyright info ("Please also specify copyright and image credits for each image. The file-upload manager offers an input field for this optional information."). What is the copyright for various screenshots taken of GRNsight?

**Comment by eileenchoe** [comment]
Also I was under the impression that @NAnguiano will also be attending the conference to present if the poster is selected?

**Comment by dondi** [comment]
Just a note that I am working on the LaTeX issues right now. I too was under the impression that @eileenchoe would be the presenter because we weren’t making any assumptions about @NAnguiano’s availability/eligibility after graduation. I can discuss this with @kdahlquist to look at possibilities.

Copyright info is all ours, I would imagine. The figures are all created by our group and our software.

Meanwhile I am working on the multiple-author-shared-affiliation issue. I have found some answers on the web, including ACM’s own FAQ, but have run into some wrinkles. I will report back (likely with an accompanying commit) when I have worked it out.

**Comment by dondi** [comment]
OK so I scanned the web for instructions and ultimately I settled on following this one because it has the most recent date (last published April 9, 2017): http://www.acm.org/binaries/content/assets/publications/consolidated-tex-template/acmart.pdf

Page 10 of that document acknowledges that shared affiliations can take up a lot of space, but ultimately prefers that over any kind of special formatting. I did try out various options from that document, but none of them worked well. So for now I’d say let’s just stick with this.

There _is_ one tweak that I learned from the document, and I’ll make that later; got to go for now. (specifically, they accept a separate `\department` field)

**Comment by dondi** [comment]
Technical fixes done. Going into content-reading now.

@kdahlquist In terms of editing this, I checked out how it looks in the web-based GitHub editor and it looks fairly manageable to edit the source file (_siggraph-abstract-review.tex_), especially since you’re pretty accustomed to having markup mixed in. The only disadvantage I see is that long lines are not automatically wrapped. It _is_ safe to insert line breaks though, so that can be done without issues.(LaTeX ignores linebreaks unless there’s an actual _blank_ line; it interprets those as marking a new paragraph)

**Comment by dondi** [comment]
Scratch that, I went ahead and did hard linebreaks. The file should be pretty editable within the web editor now.

**Comment by kdahlquist** [comment]
OK, I'm cool with editing on GitHub web.  However, is there a way I can compile it to see what it looks like once I've made a change?

**Comment by kdahlquist** [comment]
Also, don't forget that the GitHub web editor has a soft wrap feature (which I use all the time!).

**Comment by dondi** [comment]
The preview generation, unfortunately, will need a LaTeX rebuild. I can do that on and off this evening; not an ideal workflow but probably unavoidable if Overleaf can’t use custom templates.

Ack, I forgot about the soft wrap! I should undo the hard wrapping then…much better to work with the soft wrap. Stand by, I have to back out the commit that applied the hard wrapping…

**Comment by dondi** [comment]
OK, soft wrapping restored.

I have some pending edits; however I will pull regularly in case you are also editing. I’ll merge any conflicts and will signal when I’ve pushed a new version from my end.

**Comment by kdahlquist** [comment]
Sorry, started editing, not too much though.  I'll wait for your next comment before I work on it again.

**Comment by dondi** [comment]
That’s fine, keep working. I’ll pull before I send my own edits.

**Comment by kdahlquist** [comment]
I got Overleaf to work.  I had to

* sign up for an account
* click on Files > Upload from > Computer
* I then just uploaded the contents of the SIGGRAPH directory and set "siggraph-abstract-review.tex" as the main file in the directory tree on the left.

Theoretically, Overleaf supports direct connections to GitHub, but that didn't work for me.

Now I can at least see the whole document compiled, but I'll still make the changes in GitHub.

**Comment by dondi** [comment]
Sounds good. Let me know when you’re at a pause, then I can pull your edits and merge mine, then finally upload the combined content. I’m largely done.

**Comment by kdahlquist** [comment]
Go ahead and pull.  I just did some tweaks to the abstract and that's it so far.

To answer the copyright question, use the Creative Commons Attribution Non-Commercial-Share Alike 3.0 Unported License that we use for the website.  If you need to give a name to attribute the license to, say "The Authors".

**Comment by kdahlquist** [comment]
I looked at the .bib file and the citation to the PeerJ article is given as type {misc} instead of {article}, which it should be.  I deleted the reference to Schade from the Figure 1 legend, so we don't need that reference anymore.

Depending on how much room @dondi's changes are saving us, I think we can just get rid of the whole architecture section, streamline the intro/motivation, and still fit what we need for the new features.

**Comment by dondi** [comment]
OK, merged and pushed. The hard linebreaks had managed to sneak back in so it took a little longer for me to merge. But the soft breaks have been restored, and as far as I can tell both sets of edits are intact.

Unfortunately my changes do not gain much space; there’s not much we can do when the repeated affiliations take up nearly an entire page. I don’t know if the reviewers will take that into account.

I will make the bibliography edits now, and then the bigger cuts/revisions can proceed.

**Comment by kdahlquist** [comment]
Do you want me to wait for the bibliography or can I just start on the main text?

**Comment by dondi** [comment]
Oops, yes, the file is separate so you can get into the main text immediately.

**Comment by kdahlquist** [comment]
Do we have to say "Department of", that would save us a couple lines for the EECS people?  Likewise, maybe we need to shorten the title by a word so that we don't use that third line.  We could just start with GRNsight v2: instead of New features for...

**Comment by dondi** [comment]
All of those sound good to me.

The bibliography has been updated. Not sure if Overleaf catches that automatically, but the updated PDF reflects the changes.

I noticed that we've lost the Pavlopoulos citation. Should we bring that back in? Seems like a good indicator that we did some due diligence first. Then again, we did that for v1 so might not be as relevant here.

**Comment by kdahlquist** [comment]
I'm going to slash and burn to get this thing down to 2 pages.  Let's see what we need after that.  I actually want to work in a citation to the 2015 Bulletin for Math Bio paper, but we'll see.

**Comment by dondi** [comment]
Got it; slash and burn away ✂️🔥

**Comment by kdahlquist** [comment]
I got it down to almost 2 pages by cutting and getting rid of Fig. 2 (I just commented it out for now).  Only the references are on the third page now.  And actually, I think the only needed reference is to PeerJ.

I've got other stuff I need to do right now; I can take a brief look in the morning, but I have class to get ready for and I don't get out until 11.

**Comment by kdahlquist** [comment]
Actually, I don't think I have any more time for this.  Sorry...

**Comment by eileenchoe** [comment]
@kdahlquist @dondi thanks so much for putting time into this so late. The specification for authors does not explicitly require the department, removing this saves a few lines. I'll continue to cut it down, and get the other submission materials in place to submit tomorrow morning.

**Comment by dondi** [comment]
@eileenchoe Last bit for the night…I commented out the department and boom we are within two pages 🙂 Though now those repeated identical affiliations are really sticking out…still, I will make that ACM’s problem, not ours, again based on what is stated in http://www.acm.org/binaries/content/assets/publications/consolidated-tex-template/acmart.pdf

I cleaned up a couple of loose ends—there was a dangling figure reference from the deleted diagram plus I made the GRNmap URL appear. Good time to sleep on it and see what the morning brings for you.

**Comment by eileenchoe** [comment]
Great! Although its too bad that the normalization figure couldn't make it on there... 

Few submission related questions regarding the reviewer and keyword for our abstract:

<img width="678" alt="screen shot 2017-04-24 at 11 45 30 pm" src="https://cloud.githubusercontent.com/assets/16827883/25372016/7e444552-2948-11e7-87d2-16efa39de32d.png">
<img width="586" alt="screen shot 2017-04-24 at 11 45 46 pm" src="https://cloud.githubusercontent.com/assets/16827883/25372019/80218aec-2948-11e7-84f3-4078d57b23f2.png">

**Comment by eileenchoe** [comment]
So there was a bit of extra space after taking out the departments. By condensing a sentence here and there in the introduction and conclusion, I've managed to get Figure 2 back in and still keep it at two pages!

**Comment by eileenchoe** [comment]
Additionally, here's a draft of the 1-sentence summary statement (max 50 words):
We present new visualization and layout features in v2 of GRNsight, a web application and service for the interactive visualization of small- to medium-scale gene regulatory networks,  giving the user more control over the visual display of the weighted or unweighted network graph. (44 words)

**Comment by kdahlquist** [comment]
For the questions:
* University Professor
* most relevant keyword: Research
* secondary: display and UI/Tools/Systems

**Comment by kdahlquist** [comment]
summary is fine

**Comment by kdahlquist** [comment]
The PeerJ article is still not referenced correctly in the .bib file.  I don't have time to fix it right now, but it should have the same fields as the other articles.

**Comment by kdahlquist** [comment]
tried to fix the PeerJ citation and made two very minor edits; as long as the citation compiles correctly now, I think it's OK to submit.

**Comment by eileenchoe** [comment]
Abstract submission is complete! :) We will know mid-May if the abstract is accepted!

**Comment by kdahlquist** [comment]
Good work. Lowering the priority until we hear the good news!

**Comment by eileenchoe** [comment]
Emailed the poster coordinator, and notifications are apparently delayed and will come out by the end of the week. If accepted, final poster is due June 2nd so I'm reviewing the poster we had for the research symposium to see where we can make v2 updates.

**Comment by eileenchoe** [comment]
I heard back from SIGGRAPH last night, and unfortunately the poster was not selected for the conference. The reviewers had some good feedback that I'll share at the meeting.

**Comment by kdahlquist** [comment]
Sorry to hear that.  Go ahead and post the reviews here, if you are comfortable with that.

**Comment by eileenchoe** [comment]
Sure, here's a screenshot:
<img width="1163" alt="screen shot 2017-05-30 at 9 07 38 am" src="https://cloud.githubusercontent.com/assets/16827883/26593248/4823e64e-4518-11e7-9e73-1548ad0b0ecb.png">

No worries, it was a good learning experience! As one of the reviewers suggested, we can look into other conferences that may be better suited to present GRNsight.

**Comment by kdahlquist** [comment]
CHI 2018 is in Montreal on April 21-26: https://chi2018.acm.org/
UIST is in Quebec City, October 22-25: http://uist.acm.org/uist2017/, abstract is due July 12 for poster

Both are about interaction design.  If @eileenchoe wants to go in this direction for her 402, we could design a research project for a potential paper presentation at CHI.

@dondi and @kdahlquist will also work with @bengfitzpatrick to think about our grant proposal and what direction we would take.
