### ISSUE TITLE
Need to return error when user uploads blank file

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#428]
At the meeting Thursday, we discovered that GRNsight does not throw an error when a user uploads a blank file, i.e., a .xlsx, .sif, or .graphml file with no content.  Instead, GRNsight loads a blank graph, which correctly says 0 nodes, 0 edges at the top right.  However, we think that the user should be alerted that the file is blank instead, otherwise s/he might get frustrated trying to load the same file multiple times with only a very subtle cue that something is wrong.

Discussion ensued as to whether this was a semantic error that should be caught at the level of the semantic checker or a syntactic error that should be caught individually.

@kdahlquist suggested that the team should see what JSON is returned in each case of an empty file.  If it is the same, then it seems that it can be handled by Semantic Checker.  If not, then there would need to be individual syntactic tests.  @eileenchoe mentioned this in her post to #362.

**Comment by dondi** [comment]
Yes, I agree that this is a semantic error. Technically, an empty file is "syntactically correct"—i.e., it represents an absence of data, which is considered legal at the structural level. We are the ones deciding that for the particular context of loading a graph, putting up a zero-node, zero-edge graph is most likely an indication that something is not going as intended.

This is analogous to how we don’t consider zero, the empty string, or null/nil to be an erroneous expression per se, but depending on the context, we might interpret it as incorrect.

This choice also reduces code duplication. The semantic checker can look for a zero-node, zero-edge network and issue a warning or error, thus placing this check in one place and avoiding the implementation of this check at the level of every format that we support.

**Comment by eileenchoe** [comment]
Wrote the semantic test for this issue, which returns an EMPTY_NETWORK_ERROR when it detects that the network object has an empty genes array. I interpreted a "blank file" to mean an empty SIF file, an Excel file with a network tab which contains no data, or a GraphML file with no nodes and edges. Semantic test has been tested for all 3 file types and displays the error correctly. The files I generated can be found in test-files > semantic-error-test-files. Submitting the pull req now.

**Comment by kdahlquist** [comment]
For GraphML, the test should be like SIF, an empty file.  Since GraphML is a text format, that is how I would interpret an empty file.  The test you wrote where there were no nodes or edges in the file (but presumably the header info was intact) is a separate test.

For Excel, if there is a blank worksheet called "sheet1", which is what a new workbook file looks like in Excel, presumably triggers a different error where there is no "network" or "network_optimized_weights" sheet.

**Comment by eileenchoe** [comment]
Yes, a previous test had already been written to cover the case where there was no "network" or "network_optimized_weights" detected. However, if an Excel spreadsheet with a "network" tab with no data was uploaded no error was thrown, so I handled this scenario with the new semantic test. 

For GraphML, the importer itself has an issue with the completely empty file, so it doesn't get to the semantic checker. Handling this input would be a sub-issue of #363 because it requires some decisions about how the syntactic checker is integrated with the importer itself.

**Comment by kdahlquist** [comment]
I have reviewed this and want to suggest a slight wording change to the error message.

Instead of "GRNsight detects that an empty network has been uploaded. Please review the file and ensure that it contains data."

Say: "GRNsight detects that the "network" worksheet is empty. Please review the file and ensure that it contains an appropriately formatted adjacency matrix in the "network" worksheet.

**Comment by eileenchoe** [comment]
@kdahlquist I chose that particular wording to be file-independent since this is a semantic test. The the "network" worksheet is only specific to Excel input. Currently this error message will also be triggered for a completely blank SIF and a GraphML file with the correct headers, but no nodes and edges.

**Comment by kdahlquist** [comment]
Oops, now I realize that this is a semantic error and that we need to be more general for excel, sif, and graphml.  How about this?

"GRNsight detects that the file you uploaded is empty and does not contain any network information. Please review the file and ensure that it specifies a network."

**Comment by eileenchoe** [comment]
Ok, that sounds good. I'll make that fix and comment when I make the PR

**Comment by eileenchoe** [comment]
Included in PR #500

**Comment by eileenchoe** [comment]
Live on Beta v2.1.3

**Comment by kdahlquist** [comment]
@eileenchoe, just a quick note, when you add the review requested label to issues, please leave the other labels in place.  It still needs to have a priority label and a category label as to which aspect of the program it belongs to (testing, functionality, web site, documentation, etc.)  Thanks.

Most likely, I'll be able to review these tomorrow.

**Comment by eileenchoe** [comment]
Got it!

**Comment by kdahlquist** [comment]
So, I verified that the error message is fixed for a blank .xlsx and .sif file.  However, I tried to import a blank .grahpml file (an empty text file with the .graphml extension) and I think I crashed the beta server, or at least a demo won't load after I did that.

**Comment by eileenchoe** [comment]
Yes, I am aware of this bug. Currently this error will only get triggered if there is the appropriate graphml headers. As I mentioned above for GraphML, the importer itself has an issue with the completely empty file, so it doesn't get to the semantic checker. Handling this input would be a sub-issue of #363 because it requires some decisions about how the syntactic checker is integrated with the importer itself.

I'll restart beta right now

**Comment by eileenchoe** [comment]
Beta has been restarted.

**Comment by eileenchoe** [comment]
Fix live on Beta v2.1.6

**Comment by kdahlquist** [comment]
Since this is now fixed for .graphml (see #363), closing this.
