### ISSUE TITLE
Allow all File types to be uploaded using the "Open" dialogue

### ISSUE THREAD

**Issue by NAnguiano** [dondi/GRNsight#433]
I think we should allow all of the different file types (xlsx, sif, graphml) to be uploaded using the Open dialogue, instead of having "open" for xlsx only and "import" for sif and graphml. 

When I think "open", I think of opening a file of allowed types. When I think "import", I think more along the lines of importing prior session data.

**Comment by kdahlquist** [comment]
This is worth further discussion.  However, when @dondi and I initiated the import of SIF and GraphML feature, we distinguished import vs. open because those weren't "native" GRNsight file types.  In the future, if we add node coloring based on a GRNmap input or output workbook, the data we need would not be supported by SIF and we'd probably have to customize GraphML to support it.  Hence, in the future we might need to maintain the distinction.

In the context of session data, that would be a fourth type of open/import that is also different than the rest.  If we decide to save session data as GraphML, then it might make sense to consider our "native" format GraphML instead.  

For now, I don't think we want to change this, but we should monitor the situation to make sure we are as clear with our interaction design as possible.

**Comment by kdahlquist** [comment]
After discussion with the group, we thought that the Open menu item should have the arrow that then led to the three filetypes supported by GRNsight and that we would get rid of the Import menu option.

**Comment by kdahlquist** [comment]
We need to talk about this and either implement or close.

**Comment by dondi** [comment]
This was discussed with @mihirsamdarshi and he will take a crack at it. Sounds like a desirable change (so that the user just picks a file and doesn't have to worry about which format it's in) and potentially not too hard to implement.

**Comment by dondi** [comment]
@mihirsamdarshi is nearly done, following the game plan laid out last week.

**Comment by mihirsamdarshi** [comment]
Addressed in PR #805

**Comment by dondi** [comment]
Also pending font family fix.

**Comment by kdahlquist** [comment]
Verified fixed in beta 4.0.6
