### ISSUE TITLE
Should weights show up on weighted graphs loaded with the "default to black edges" option selected?

### ISSUE THREAD

**Issue by NAnguiano** [dondi/GRNsight#442]
I apologize for the deluge of issues, guys.

Right now, on weighted graphs loaded with the "default to black edges" option selected, the weights will show up if the "Always show edge weights" or "Show with mouse over" options are selected. 

![screen shot 2017-04-18 at 7 04 55 pm](https://cloud.githubusercontent.com/assets/6444156/25160271/f3cbf132-2469-11e7-95be-a3a199eefa69.png)

I've never actually considered what behavior is expected when that option is chosen on an unweighted graph. Is this behavior that we want, or do we want to prevent the weights from showing up when this option is selected?

I'm not sure either way (and have no preference), but it looks a little weird seeing an "unweighted" graph with weights. While writing this issue I actually found two other ones that I'm going to be making an issue on right after this...

**Comment by kdahlquist** [comment]
My initial reaction is that I would leave this one as is.  The weights can be turned on and off at will, so a user that doesn't want to display them has that option.  Since the information is there, we might as well allow the option to display it.  Maybe someone finds the colors and thicknesses distracting and just wants clean lines, but wants to peak at the weights every once in a while.

The only change I might consider is if the option to show weighted is unweighted is selected, to also default to not showing weights. 

We could solicit more opinions on this, but again, this isn't in the critical path, so let's leave it as priority 1.

**Comment by kdahlquist** [comment]
The group thought that it was OK to leave this one alone.
