### ISSUE TITLE
Use hand icon for mouse pointer when grabbing (scrolling) is allowed

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#469]
As discussed in issue #396, change the mouse pointer to a hand icon when grabbing (scrolling) is allowed.

**Comment by NAnguiano** [comment]
This one is fully done. I tested a bunch of different zoom/scroll/pan combinations and the hand seemed to always behave as intended for the most part. There were a few times it got stuck in the "grabbed" position, but that seemed to only occur when I'd grab the graph and shake it back and forth as quickly as I could. Clicking again fixes it.

**Comment by kdahlquist** [comment]
Sounds good--looking forward to seeing it.

**Comment by dondi** [comment]
Rapidly shaking back and forth is a good test for the robustness of your mouse handling. If things get stuck or awry when this is happening, that is usually an indication that the mouse cursor has left the mouse-listening area without giving that area a chance to clean up.

If the mouse listener is the individual gene node, the mouse may move faster than the gene node can move, and thus one might be left in an inconsistent state. The fix for this would be to move some mouse-listening duties to the overall container.

But I would deal with that later. Keep this one focused on just the hand icon and someone else can deal with rapid shaking some other time.

**Comment by kdahlquist** [comment]
This is confirmed in beta v2.0.16.
