### ISSUE TITLE
Don't allow grabbing/panning in area between bounding box and viewport

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#472]
This suggestion comes from @eileenchoe in response to issue #396.

"Currently clicking and dragging outside the bounding box, but inside the viewport moves the bounding box. (@kdahlquist notes that this only happens when the graph is zoomed out on a "restrict graph to viewport" setting) My intuition is that you should only be able to move the bounding box via drag and drop if your mouse is actually within the bounding box."

@kdahlquist says that this makes sense, but is not on the critical path to release.

**Comment by NAnguiano** [comment]
If I'm understanding this correctly, this is suggesting that dragging  and scrolling should be limited to only when the mouse pointer is within the bounding box, but only on fixed graphs? I may be misunderstanding what you're meaning by this, but if this is actually the case, I'm not sure I like this functionality. 

I think it would be limiting, especially when the graph is zoomed out to the max extent or when you're using a large screen. Additionally, when I'm on a fixed graph, I think it could get really annoying to constantly have to move your mouse cursor into the bounding box to move it. Most of the time, I find myself just clicking wherever my mouse pointer happens to be. I think it would be a hinderance to be forced to keep your pointer in the bounding box when you are moving - again, especially on large screens and zoomed out graphs. I also feel that it would make it difficult on large graphs and small screens for a user to move the viewport. They may accidentally grab nodes or find themselves having to look around edge weights that are spawning above nodes.

Additionally, I feel like this may cause a bit of confusion, since on an adaptive graph you could move it around no matter where you are (seeing as you can't actually see the bounding box to be able to know where to click). Having a different functionality between them is confusing. It makes sense to me to restrict zooming and limit how far the user can pan in fixed graphs and not adaptive ones, since the "fixed" label informs you that you are restricting your graph to the viewport, so you can't go any smaller than it or go outside of it. But I can't say I see the benefit in restricting the user's ability to choose where to scroll in this case. 

I'm personally a fan of giving the user as many ways as possible to interact with their graph - which is why we have options like the arrows and the zoom slider for zooming and panning along with the ability to drag and mouse wheel. This seems like an unnecessary limitation of the users ability to work with the graph.

**Comment by kdahlquist** [comment]
Sorry, this is just for fixed graphs, when zoomed out so there is a "box within a box" on the screen.

![image](https://cloud.githubusercontent.com/assets/6463867/25647722/73c6e2c4-2f79-11e7-9b6d-bb2716b51584.png)

There is a no man's land between the smaller grey bounding box and the larger viewport boundary where it doesn't really make sense that grabbing there would move the bounding box/graph.

Anyway, this is for the future with plenty of time to discuss and play with it.  I wanted to create it as an issue so that it could be worked on in the future instead of having that thread lost when the other issue got closed.

**Comment by kdahlquist** [comment]
This has been rendered moot because now the bounding box is always centered in the viewport when restrict graph to viewport is selected and scrolling is not allowed.
