### ISSUE TITLE
Bounding box sticks to edges of viewport on zoom

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#480]
Bounding box views to edges of viewport on zoom.

Conditions that cause this:
* fix graph to viewport
* zoomed out so you see a grey bounding box
* move the bounding box to the edge of the viewport
* zoom in and then zoom out and you will see that the bounding box sticks to the viewport edge.

@NAnguiano says that this is happening because she is manually setting the translate and D3 doesn't like it.  D3 remembers the point at which the user started zooming back in and it doesn't detach the graph from the viewport until you reach that point.

**Comment by eileenchoe** [comment]
Just discussed this with @kdahlquist. The change to the zoom slider which zooms with respect to the center of the viewport fixed this problem. However, grabbing and moving the bounding box when the viewport is fixed and zoom level is <100% is disabled because we are only allowing the bounding box to "grow" into the size of the viewport radially, which we've agreed is ok for now.

**Comment by eileenchoe** [comment]
Also, removing cursor grab so that the user knows dragging isn't allowed when graph is restricted to viewport.

**Comment by eileenchoe** [comment]
Live on Beta v2.1.6

**Comment by kdahlquist** [comment]
Confirmed and closing.
