### ISSUE TITLE
GRNsight should default to restrict graph to viewport

### ISSUE THREAD

**Issue by eileenchoe** [dondi/GRNsight#493]
I think that restrict graph to viewport should be a default GRNsight setting. Currently, immediately after loading a demo or file, the graph has the tendency to drift down outside of the viewport, requiring user interaction upfront just to see the graph in its entirety. If viewport restriction is the default, then the user can first see the entire graph, then choose to apply force graph parameters, and toggle the viewport restriction setting to render the final graph. Thoughts?

**Comment by kdahlquist** [comment]
I'll have to think about this one for a bit before I respond.

**Comment by kdahlquist** [comment]
I think since the last meeting we are leaning towards changing this default.  Let's finalize the decision at least at today's meeting.

**Comment by kdahlquist** [comment]
We need to talk about this and either implement or close this issue.

**Comment by dondi** [comment]
This one probably needs to be talked about at next meeting.

**Comment by dondi** [comment]
After meeting discussion, decision was to backlog this issue due to:
* No current compelling reason to fix the issue
* A different problem may need to be addressed (drift of nodes when toggling force graph)

A suggested alternative was to implement "auto-zoom" (like Photoshop) but this would be a new feature and it's also not the right time for that.
