### ISSUE TITLE
SWE Collegiate Poster/Rapid Fire Competition

### ISSUE THREAD

**Issue by eileenchoe** [dondi/GRNsight#496]
The Society of Women Engineers conference in Austin, Texas (Oct 26th-28th) has a research competition, the top 10 finalists for the poster and rapid fire (5 minute presentation) divisions will present at the conference. Best part? No abstract formatting requirement! 

I'll be attending this conference anyways so it would be great to get to present GRNsight while I'm there. 

- [x] Title of Technical Research
- [x] Author(s)  Name – acknowledge those who have participated significantly in the technical aspects of the research
- [x] Abstract – limited to 500 words
- [x] Preference for Poster, Rapid Fire or either competition (a student may participate as a finalist in only one, and may indicate their preference for one or both during abstract submission)

http://societyofwomenengineers.swe.org/images/competitions/2017_Poster_RapidFire_Competition_Packet_Final.pdf

**Submission Deadline: June 15th**

**Comment by eileenchoe** [comment]
Started drafting the abstract. There are some specific abstract scoring content requirements, so working on revising/rewording to meet the spec.

**Comment by eileenchoe** [comment]
A quick link to the abstract: https://github.com/dondi/GRNsight/blob/master/documents/abstracts/SWE%20Collegiate%20Competition%202017.md

**Comment by kdahlquist** [comment]
I did a quick read of the abstract and this is a good start.  I'll be able to make some more extensive observations later, but here are my initial thoughts:

* Unless there is a length restriction on the title, I would prefer that we go with our "branded" tagline, "GRNsight: a web application for visualizing small- to medium-scale models of gene regulatory networks" 
* You need to fit in the URL to the GRNsight home page and GitHub repository, as well as the fact that it is open source
* Give more specifics as to the new features we have actually implemented in version 2 (adaptive bounding box, zoom, scroll, hide/show weights, and setting normalization factor/grey threshold) and less on features planned for the future.  The new features are vaporware at this point and can be mentioned in the poster, but should not feature prominantly in the abstract.  We have lots of cool stuff that now exists, celebrate that.

Again, I'll chime in with more specific word-smithing in the next go around after you've made the changes above.

**Comment by eileenchoe** [comment]
Thanks!

Here's a screenshot of the scoring guidelines for easy reference. There is no length restriction on the title, but it should be "brief and descriptive." I'll have another draft with the changes you suggested prepared for review next week.
 
<img width="770" alt="screen shot 2017-05-26 at 1 56 22 pm" src="https://cloud.githubusercontent.com/assets/16827883/26512389/2cc9d1f6-421b-11e7-95ef-ac4fa47a832d.png">

**Comment by kdahlquist** [comment]
@eileenchoe, be sure to give me a new draft of this by Wednesday so that we can get it fixed up before you leave for the summer.

**Comment by eileenchoe** [comment]
The draft has been updated to include version 2 specifics and the URLs. Sorry for the delay this week has just flown by. I'm still open to modifying the title. Still thinking of a better title that is shorter than our usual abstract title.

**Comment by kdahlquist** [comment]
I'm still in class giving a late quiz.  When that's over, I'll grab a bite to eat and come upstairs to work with you on the abstract.  In the meantime, please add authors.

As for the title, I think we at least need to say:

GRNsight v2: a web app for visualizing small gene regulatory networks

Do they actually give a word length for the title?  I don't actually think our normal title is that long.  For me it is more important to be specific and clear than to be brief.

Take a look at the length of your sentences.  You have several sentences with sub-clauses that get quite long that should just be broken up into two shorter sentences.

Anyway, I'll come up and we can do some editing together a little later.

**Comment by eileenchoe** [comment]
Ok, sounds good! No, there is no word length for the title.

**Comment by eileenchoe** [comment]
Completed abstract editing with @kdahlquist. Requesting review from @dondi to give it a read before I submit it.

**Comment by dondi** [comment]
In a position to read now…feedback shortly…

**Comment by dondi** [comment]
Some notes:
- First sentence, “modeling data”—comes across as somewhat generic, plus also implies to my ears that only simulation data apply. How about “…derive insights from the data that model these networks.” +3 words.
- I think “stand-alone” can be spelled “standalone” —will save us one word, for systems that count hyphenations as multiple words.
- Looking at the scoring sheet, I think all of the rows are addressed except for the hypothesis bullet. Not sure how closely we want to align to their score categories, but that’s the one area where I couldn’t really identify a sentence/phrase that has this content. This has always been an issue with software development research: In reality the hypothesis is always the same—“The software we are building will solve our problem.” Thus it is never really needed, but for folks who are unfamiliar with that implicit view, they might look for something.
I’m not sure how to address that though. We can leave it as is, but just a caution that someone might pick on that.

**Comment by kdahlquist** [comment]
Agreed with the changes--I don't think there's anything we can do about the hypothesis thing.  It will be worse if we try to shoehorn our work into that paradigm.  If we get dinged for that, it can't be helped.

**Comment by dondi** [comment]
Sounds good—looks like we’re good to revise and submit then!

**Comment by eileenchoe** [comment]
Great, thanks for the feedback. I'll revise and submit this weekend. I'm going to put my preference for either the short talk or the poster, because I am ok with doing either.

**Comment by eileenchoe** [comment]
Submitted! Will hear back by July 31st.

**Comment by eileenchoe** [comment]
Hope everyone's summers are going well. Just wanted to give the update that I was accepted for the Rapid Fire Competition (5 minute research talk)! More details to come about presentation format, but SWE is providing registration, housing, and travel stipend for all the finalists, hooray!

**Comment by kdahlquist** [comment]
Good news! 


Kam Dahlquist Professor of BiologyLoyola Marymount University
-------- Original message --------From: Eileen Choe <notifications@github.com> Date: 7/31/17  9:22 PM  (GMT-08:00) To: dondi/GRNsight <GRNsight@noreply.github.com> Cc: Kam Dahlquist <kdahlquist@lmu.edu>, Mention <mention@noreply.github.com> Subject: Re: [dondi/GRNsight] SWE Collegiate Poster/Rapid Fire Competition
  (#496) 
Hope everyone's summers are going well. Just wanted to give the update that I was accepted for the Rapid Fire Competition (5 minute research talk)! More details to come about presentation format, but SWE is providing registration, housing, and travel stipend for all the finalists, hooray!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/dondi/GRNsight","title":"dondi/GRNsight","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/dondi/GRNsight"}},"updates":{"snippets":[{"icon":"PERSON","message":"@eileenchoe in #496: Hope everyone's summers are going well. Just wanted to give the update that I was accepted for the Rapid Fire Competition (5 minute research talk)! More details to come about presentation format, but SWE is providing registration, housing, and travel stipend for all the finalists, hooray!"}],"action":{"name":"View Issue","url":"https://github.com/dondi/GRNsight/issues/496#issuecomment-319263783"}}}

**Comment by eileenchoe** [comment]
Bumping priority on this issue. I will have the presentation ready by Wednesday. I've copied the scoring guidelines for reference:

<img width="762" alt="screen shot 2017-10-16 at 7 33 26 pm" src="https://user-images.githubusercontent.com/16827883/31644072-ecffdd14-b2a8-11e7-84e4-0d7c508f4fee.png">

**Comment by eileenchoe** [comment]
Draft of SWE presentation uploaded to documents folder.

**Comment by eileenchoe** [comment]
Presentation on Saturday went well, and final draft of the presentation has been uploaded to master!
