### ISSUE TITLE
Merge normalization branch with beta and deal with merge conflicts

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#497]
At the Hangout last Thursday, we discussed that it was an immediate priority to merge the normalization branch with beta and deal with the merge conflicts so that we could get this out of the way.  (I'm sorry, I don't remember which direction that the merge was supposed to go).

We forgot to talk about it in the meeting today, but this needs to be done right away before completing the other tasks.  We want a unified beta branch to work from for the rest of the coding period this summer.

**Comment by kdahlquist** [comment]
@eileenchoe and @mihirsamdarshi, what is the status on this?  We want to take care of this sooner rather than later.

**Comment by mihirsamdarshi** [comment]
We were holding off on this until we finished both of our new features because merging right in the middle would slow development seriously and would result in two unnecessarily long merges instead of only one big one.

**Comment by dondi** [comment]
@mihirsamdarshi’s normalization fork has been merged into the original normalization branch, so there should no longer be any barriers to proceeding with this main merge.

**Comment by eileenchoe** [comment]
Started the merge process. 

There are six conflicting files right now, the only one with serious merge issues is graph.js. At the time that the normalization branch was made, I think that Nicole had been trying a few things for her viewport/bounding box/zooming changes, which she ultimately decided to go a different direction with, however this initial work was preserved on the normalization branch and is now being confused with Nicole's and my new code as well as Anu and Mihir's work for normalization. 

 Also, the automatic merge is not being consistent with taking the new formatting done post lint. In server/controllers/semantic-checker.js and graph.js large sections still have 2 spaces instead of 4... @mihirsamdarshi and I are planning to just go through line by line for graph.js to sort out the conflicts. Any general suggestions on how to go about this merge @dondi?

**Comment by dondi** [comment]
Thanks for the update @eileenchoe —FWIW no surprises there. My main advice here is to remember that what you’re really after from the `normalization` branch is precisely just @mihirsamdarshi and @anuvarsh’s work. For all else, `beta` can take precedence. So I would just have that mindset, to prioritize `beta` in all cases except where the code is the actual normalization/gray level functionality.

And remember you can always test things locally before committing the merge. Make sure to have GRNsight running so that you can reload the latest merge-in-progress to manually verify that nothing is broken. You can always back out of a merge-in-progress if you want to start over. And even when you commit to a merge, even then it isn’t permanent until you actually _push_ the merge to GitHub.

So you have a lot of checkpoints to make sure that things are going well. Stay methodical and keep in mind that `beta` can "win" in all conflicts except for the ones that directly involve normalization and gray level code.

**Comment by eileenchoe** [comment]
Ok got it!

**Comment by mihirsamdarshi** [comment]
Basically what we ended up doing was going through graph.js and all the other files and combing them line by line for changes. When we went to merge the pull request we realized that the changes would have deleted a lot of files, so we decided to just copy all the files we had fixed, and copied them onto my fork to create a Pull Request.

**Comment by kdahlquist** [comment]
This is done!
