### ISSUE TITLE
bug when changing viewport size when fixed

### ISSUE THREAD

**Issue by eileenchoe** [dondi/GRNsight#508]
While working on #468 I came across this bug, and realized that it also happens on beta. The sequence is: Load Graph > check "Restrict Graph To Viewport" > Change Viewport Size.

It's pretty serious since a whole bunch of these errors come up, and the graph disappears from the viewport except for a singe node at the upper left hand corner. 

I'll be trying to fix this as I work on #468.

<img width="341" alt="screen shot 2017-05-25 at 2 31 36 pm" src="https://cloud.githubusercontent.com/assets/16827883/26471550/ef7edc2a-4156-11e7-8332-48694fe0aefb.png">

**Comment by eileenchoe** [comment]
Fixed. Will merge with PR for #468 since I'm still working on other changes for that issue

**Comment by eileenchoe** [comment]
Fix live on Beta v2.1.6

**Comment by kdahlquist** [comment]
I followed the instructions described in the bug report and didn't see a problem.  One thing to note for later, the last instruction "Change viewport size" is a little ambiguous; it would be better to say "Change viewport size from small to large", for example because that is a specific sequence.  For example, my monitor defaulted to medium, so I would change from medium to small or medium to large.
