### ISSUE TITLE
SCCUR conference on Saturday, November 18

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#522]
Mark your calendars for the Southern California Conference for Undergraduate Research on Saturday, November 18, all day from ~8:00 AM to ~6:00 PM.  http://www.sccur.org/

Abstracts are due October 5.

**Comment by yshin4** [comment]
@ebachoura can we work on the abstract during our Monday work session? What time will you be free?

**Comment by ebachoura** [comment]
@yshin4 If Eileen and I finish Toal's python homework before Monday, then I should be free after 9. Otherwise, are you free to work Tuesday night?

**Comment by eileenchoe** [comment]
Link to [Eileen's Abstract](https://github.com/dondi/GRNsight/wiki/SCCUR-2017-Abstract-(Eileen-Choe))

**Comment by eileenchoe** [comment]
@kdahlquist Took a closer look at the requirements for the oral presentations. On the submission page, it states that "research proposals without data are not appropriate for oral presentations." Additionally, a Research Results document must be submitted (250 words) for the oral presentation.

I was going to focus on the Client Side Testing Script Generator, SIF Syntactic Test Suite, and this semester's work on the d3v4 port and generalized data structure for Excel import (since I will be able to make progress on these tasks by the conference). Do you think that the poster session might be a more appropriate venue for this abstract as well? The submission page says that poster submission is suitable for research proposals and research with preliminary data.

**Comment by eileenchoe** [comment]
Also here are the abstract requirements for quick reference: 
The submission's title
The abstract (up to 250 words)
A list of keywords (10 maximum)

**Comment by kdahlquist** [comment]
I guess I can't see these guidelines because they are behind the login?  GRNsight is a mature project, so I think it is very appropriate for a oral presentation.  If it were just vaporware at this point, then it wouldn't qualify, but since we have a product, I think it is fine to present it orally.

You should begin with the v2 feature set.  GRNsight 2.0 has not been presented in this venue, so it is entirely appropriate to discuss it; you are presenting on behalf of the group.  You could then use the v2 feature set to motivate the Client Side Testing Script Generator and SIF Syntactic Test Suite and mention node coloring as future directions.

**Comment by eileenchoe** [comment]
@kdahlquist Yes, those guidelines were in the submission form. Sounds good, I'll do that!

**Comment by ebachoura** [comment]
Link to @yshin4 and @ebachoura's abstract: [Jen & Eddie's Abstract](https://github.com/dondi/GRNsight/wiki/Jen-Shin-&-Edward-Bachoura's-Abtract-for-SCCUR)

**Comment by kdahlquist** [comment]
Abstracts have been reviewed and revised; go ahead and submit, lowering the priority without closing in case reviewer feedback requests revisions.

**Comment by eileenchoe** [comment]
I submitted my abstract!

**Comment by yshin4** [comment]
Submitted poster abstract as well.

**Comment by kdahlquist** [comment]
@ebachoura @eileenchoe @yshin4 Start drafting the poster and presentation for review by November 7. This will give us around a week to review then print these.

**Comment by kdahlquist** [comment]
@yshin4 and @eileenchoe need to register by tomorrow.  I know that @eileenchoe is out of town--can this be taken care of for her?

**Comment by yshin4** [comment]
I registered on Tuesday and I can do that for @eileenchoe as well. I will ask her if she already registered or not first since she said she will do it on Tuesday when we met Monday.

**Comment by kdahlquist** [comment]
Great!  Thanks!

**Comment by eileenchoe** [comment]
Yes huge thanks to @yshin4 for registering for me yesterday!

**Comment by dondi** [comment]
Notes on poster/presentations:
* @eileenchoe's presentation is up-to-date due to SWE but can now expand to provide more details
* @yshin4 and @ebachoura's poster should change the Future Work section into a Conclusions section that summarizes their respective finished accomplishments of the past few months (visual label/edge tweaks for @yshin4; full SIF and GraphML support + error/warning details for @ebachoura; normalization factor too)
* @yshin4 and @ebachoura should review recently-closed issues in case there is anything else worth mentioning

**Comment by yshin4** [comment]
Edited Future Work to Conclusion and added a summary of my work.
@ebachoura said he would:
1. Add to a conclusion about GraphML.
2. Update Google analytics.
3. Update test numbers.
in future.

**Comment by ebachoura** [comment]
Alrighty I'm done!

**Comment by eileenchoe** [comment]
My talk is scheduled for 9:30 AM - 9:45 AM at Room 9-247! Ran through my presentation at the meeting today, will make edits to practice at the meeting next week.

**Comment by kdahlquist** [comment]
I'm reviewing the poster and have some comments:

1. The GRNsight screenshot that is the centerpiece of the poster is out-of-date (it's version 1 and we are on version 2 now).  Nothing is being said about the viewport/bounding box options, scroll and zoom, display of edge weights, or the normalization factor.  The section on "Sophisticated Architecture" can be removed to make room for discussion of new features.

2. The Acknowledgments need to be modified to thank Nicole, Anu, and Mihir.  References to financial support for Nicole and Anu need to be removed.

3.  All references must have corresponding citations in the body of the poster.

4.  Under the section "Improved Visual Performance" there is a weird extra bullet point that is side-by-side instead of down.

5.  Instead of saying "repressed end marker" say "blunt end marker".

**Comment by eileenchoe** [comment]
Uploaded final presentation draft to the documents > presentations folder.

**Comment by yshin4** [comment]
![image](https://user-images.githubusercontent.com/16246811/32863602-ecd0e890-ca10-11e7-8b01-006c4a477cf8.png)

For @ebachoura and my session.

**Comment by yshin4** [comment]
This is for myself and @ebachoura.

- [ ] The GRNsight screenshot that is the centerpiece of the poster is out-of-date (it's version 1 and we are on version 2 now). Nothing is being said about the viewport/bounding box options, scroll and zoom, display of edge weights, or the normalization factor. The section on "Sophisticated Architecture" can be removed to make room for discussion of new features.

- [ ] The Acknowledgments need to be modified to thank Nicole, Anu, and Mihir. References to financial support for Nicole and Anu need to be removed.

- [ ] All references must have corresponding citations in the body of the poster.

- [ ] Under the section "Improved Visual Performance" there is a weird extra bullet point that is side-by-side instead of down.

- [ ] Instead of saying "repressed end marker" say "blunt end marker".

**Comment by kdahlquist** [comment]
What is the status on the poster?  I'm guessing that @ebachoura hasn't made the changes above?  

If the poster is not finished by 4:00, then it will need to be printed by CS instead of BIOL.

**Comment by ebachoura** [comment]
We finished changes, but due to time constraint, we already emailed it to be printed. We will let you know further progress.

**Comment by dondi** [comment]
done!
