### ISSUE TITLE
eslint runs inconsistently

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#535]
We have discovered that eslint is reporting different results on different systems:
- With @ebachoura and @yshin4, who are on Windows 10, eslint reports errors as expected
- With @eileenchoe, who is on macOS, eslint appears to run but does not report any errors
- With Travis, eslint is reporting a dependency error for a module that is listed as an eslint dependency

We need to resolve this so that everyone gets the right linting output.

**Comment by kdahlquist** [comment]
@dondi will try this on his development setup and report back.

**Comment by kdahlquist** [comment]
@eileenchoe will check her eslint configurations to see if one might be unexpectedly interfering with another.

**Comment by dondi** [comment]
I also saw the "no errors found" on my end, so started digging into the `eslint` command line. It turns out that the wildcards need to be quoted on Unix-based environments, because those asterisks are pre-expanded by the shell: https://eslint.org/docs/user-guide/command-line-interface

I’ve submitted a PR with this change: https://github.com/dondi/GRNsight/pull/536

Ironically of course, the PR is broken because now the checks are actually working! I might have to fix all of the listing errors now, for real 🙃 Or, we accept this into `beta` with the errors, then fire up another task to fix them. I’m seeing 2483 problems reported 😱

**Comment by ebachoura** [comment]
@dondi asked me to run some linting tests and the results are a bit odd.

So I started on Dondi's branch and I ran the linter and found no errors. I was surprised and I checked my own branch and found the same result, no linting errors.

This was really weird because just a few days ago I ran the tests and got 321 linting errors. I realized that another thing that changed in the last few days was my bash application. I just switched to Bash on Ubuntu on Windows. Both of the "npm run lint"s were done in this Bash on Windows and they returned 0 linting errors, but when I switched back to Git Bash and ran the linter, there was 321 errors for both my branch and Dondi's. Hope this helps!

**Comment by dondi** [comment]
Thanks @ebachoura for testing my branch. Curiouser and curiouser indeed. What I can now confirm is that I _don't_ get line break errors—I really do get some legitimate listing problems. Here is a sampling, _for just one file_!

```
/Users/dondi/Documents/Main/Code/git/GRNsight/web-client/public/js/graph.js
    16:1   error  Line 16 exceeds the maximum line length of 120     max-len
    48:1   error  Line 48 exceeds the maximum line length of 120     max-len
    56:18  error  'i' used outside of binding context                block-scoped-var
    62:18  error  'i' used outside of binding context                block-scoped-var
    62:18  error  'i' is already defined                             no-redeclare
    62:25  error  'i' used outside of binding context                block-scoped-var
    63:50  error  'i' used outside of binding context                block-scoped-var
   101:23  error  Missing space before function parentheses          space-before-function-paren
   106:9   error  'manualZoom' is assigned a value but never used    no-unused-vars
   135:20  error  Missing space before function parentheses          space-before-function-paren
   202:23  error  'maxScale' is not defined                          no-undef
   207:39  error  'maxScale' is not defined                          no-undef
   220:31  error  Missing space before function parentheses          space-before-function-paren
   226:14  error  'getMappedValue' is defined but never used         no-unused-vars
   226:28  error  Missing space before function parentheses          space-before-function-paren
   242:17  error  'currentPoint' used outside of binding context     block-scoped-var
   245:17  error  'equivalentScale' used outside of binding context  block-scoped-var
   246:64  error  'currentPoint' used outside of binding context     block-scoped-var
   249:17  error  'equivalentScale' used outside of binding context  block-scoped-var
   250:65  error  'currentPoint' used outside of binding context     block-scoped-var
   252:31  error  'equivalentScale' used outside of binding context  block-scoped-var
```

And indeed I am still getting 2483.

Given this behavior, @eileenchoe I am curious about what you see if you run lint on my branch. (`dondi`)

**Comment by dondi** [comment]
Meanwhile, Travis reports 322 errors. Wut??? https://travis-ci.org/dondi/GRNsight/builds/280681110

I’m curious to hear what other error counts people are getting—this is the `dondi` branch, so pull and give it a try…

**Comment by dondi** [comment]
Ah, some progress: my system is now consistent with Travis, 322 errors.

The issue was that I had a _coverage_ folder in my repository (I guess from an earlier run of Istanbul?), and that folder had _.js_ files in it as well. Removing that folder took me back to 322 errors.

So, that aspect is resolved. The mystery now is @ebachoura’s 321 vs. Travis and my 322. We’ll see what we get when additional data come in.

**Comment by dondi** [comment]
@ebachoura As for the weird Ubuntu Bash behavior, try to re-pull that repo then re-checkout `dondi`. Then report back when you can. Thanks!

**Comment by dondi** [comment]
_coverage/_ has been added to the _.eslintignore_ list. For anyone trying this out, make sure to pull `dondi` again to make sure that you get this update.

**Comment by eileenchoe** [comment]
@dondi running `npm run lint` on the `dondi` branch on my machine yields 322 errors, which is consistent with what you are getting and what Travis is getting.

**Comment by dondi** [comment]
OK, thanks @eileenchoe! So @ebachoura and @yshin4, let’s see if we can get consistency for you guys too, on the `dondi` branch. @ebachoura, make sure that your repository on Ubuntu Bash is freshly pulled and on the `dondi` branch. @yshin4, do the same on whatever command line you use regularly.

We appear to be converging on 322 linting errors. Once we’re all consistent, I can merge this with `beta`. To minimize conflicts, let’s temporarily accept these failed builds and merge `beta` into our working branches. One or more of us can do “lint-fix-only” commits on `beta`, which the others would then merge into their branches a little at a time.

Then we can all be _really_ happy when we go green again!

**Comment by ebachoura** [comment]
I pulled Dondi branch and ran lint and I got 322 linting errors, so it looks like I am on board with Eileen, Dondi, and Travis. @yshin4 Could you pull Dondi's branch and then run lint and post how many errors you get.

**Comment by yshin4** [comment]
I pulled dondi branch and linter gave me 322 errors as well.

**Comment by dondi** [comment]
OK, looks like we’ve converged on consensus…if this is OK for you guys, I’ll push this to beta. I’ll see if some errors can be fixed along the way too.

**Comment by dondi** [comment]
Also I just realized, @ebachoura you might want to audit the original clone where you were seeing the discrepant numbers. You might have had lingering commits or other files that were skewing the results. It might be best to manually transfer any work that you knew you were doing into a fresh clone.

**Comment by dondi** [comment]
OK, this has been merged with `beta`; no release for this one because it only affects how listing is checked. However, Travis does report errors now so "linting-only" fixes will be desirable going forward. I’ll write up a new issue for that.

**Comment by dondi** [comment]
The follow-up issue is #538; also, now is a good time to pull and merge `beta` into our individual branches.
