### ISSUE TITLE
Implement GraphML XSD validation

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#541]
@ebachoura work on #363 has revealed that other errors may get through because they are actually schema validation errors. To avoid too much custom coding, we will explore implementing GraphML XSD validation because the XSD does exist anyway (http://graphml.graphdrawing.org/xmlns/1.1/graphml.xsd).

We can try this out to see whether this provides benefits. It remains an open question whether it is widely followed to begin with.

**Comment by igreen1** [comment]
After digging around for a while trying to understand xsd, it appears it was already implemented.

In the import and export,
`xsi:schemelocation = http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd`

@igreen1 can change this to the 1.1? There doesn't appear to be significant changes, though, and changing the scheme might cause unforseen issues, so probably best to avoid.

**Comment by dondi** [comment]
@igreen1 I think that line identifies _which_ XSD is supposed to be followed but I haven't seen evidence that there is an actual _check_ on whether the XML file follows that format.

Ideally there's an easy-to-use function that performs this check. Then we would write code that intercepts the result of this check and reports an error if needed.

**Comment by igreen1** [comment]
#74c292d theoretically fixes this, but it is untested (see below). 

Most of the time @igreen1 spent this week was on the following:

When attempting to test the solution, a bigger bug was found. I will wait until our meeting to open a issue thread as its possible it is a user error. The files used are created by:
1. Open demo graph
2. Export demo graph as unweighted or weighted graphml (File > Export Data > To graphml)
3. Open the downloaded file (File > Open File > select the file)

On my local server, when these files are added, the server shows `POST /upload-graphml 400` which implies an issue with the upload function. The name does NOT update. Clearly, the upload has entirely failed and GRNSight is continuing like it didn't happen.This happens on BOTH igreen1 branch and beta branch, which indicates the issue is not with the most recent igreen1 commit. Testing on the main branch doesn't make sense since it doesn't have the prerequisite features. Other than failing to upload, no other issues arise and I can continue to use GRNSight without issue.

On the remote beta, when files are added, the name DOES updates but the graph does not. Cause is opaque because of lack of server logs. After attempting to upload, the program breaks a lot. The side panel no longer appears to affect the graph (tested most the functions I believe). The graph can no longer be exported. Print to file does still work, though. The problem can be 'reset' by opening a demo, which updates the graph correctly and makes the sidebar work again. Probably, the unsuccessful opening of the uploaded file is causing unforeseen behaviour.  

On the remote main release, I am unable to test the import as it is generally less robust and doesn't support the features in question.

**Comment by dondi** [comment]
@igreen1's investigation has revealed a tech debt bug from last year, which has been captured as #886. This bug now pre-empts this one, but after #886 is addressed, we can go back to this.

Another potential loose end is the local server issue where the `POST` results in a `400`. This looks distinct from #886 but we can revisit that behavior after #886 is addressed.

**Comment by dondi** [comment]
@igreen1 reports that XSD validation is working locally and next needs to move into making requests from within the code.

**Comment by igreen1** [comment]
Believe my error is actually coming from the linked xsd schema being incorrect. After extensive debugging failed, tried replacing it with a simple XSD schema I found online and the code ran fine. Unclear as to why, but seems that the XSD schema itself is the issue.
It's possible the parsers I have found don't place nice with graphml.
Or its possible GRNSight doesn't use the proper names for graphml, throwing errors.
Or, this could simply be a bad version of the graphml description in XSD.

**Comment by dondi** [comment]
@igreen1 clarified the report above with additional details on how the implementation is currently set up and it genuinely likes like there is just some mismatch between the XML library we are using and the XSD file being tested.

One observation is that the file currently being used is 1.1 of the schema yet our GraphML test files are based on 1.0—so this may be a factor.

Eventually after this first phase is finished, @igreen1 will make sure to use the XML schema that is actually declared within a file (not only because there may be newer versions of GraphML itself, but also because GraphML has variants like the YED extensions).

**Comment by igreen1** [comment]
@igreen1 has narrowed down the issue. It appears that the graphml .xsd validation file doesn't work with most Javascript validation methods. @igreen1 was able to validate the graphml against a standard xml validation format but not against the graphml specifically.
There are a few candidates for the reason why, including that the graphml version of the xsd includes a link to other files.

Little lost on how to move forward with this. Best solution seems to be to create a new xsd without the links by mashing the 4 graphml specifications together, but I'm pretty new to XML so I'm not sure how successful this would be. Would love to go over how it is done in meeting if we go with this solution.

GraphML appears to be pretty static now, haven't been updates in a while, so could probably get away with storing the .xsds on our server.

**Comment by dondi** [comment]
@igreen1 will isolate this work in a specific branch for examination by @dondi during the break.

**Comment by dondi** [comment]
@igreen1 will finish up this branch portion and pass it on to @dondi so that @igreen1 can move on.

**Comment by igreen1** [comment]
Added branch xsd-validation for review of the two best solutions (not working) found by @igreen1

**Comment by dondi** [comment]
I reviewed the xsd-validation validations and since they weren’t functional anyway, plus XSD validation has lowered in priority of late, I’ll go ahead and close this
