### ISSUE TITLE
Reload button should reload graph in grid configuration if that was what state it was in + other reload issues

### ISSUE THREAD

**Issue by mihirsamdarshi** [dondi/GRNsight#600]
Manipulating graph manually during grid layout should change force graph layout button back to grid layout button

**Comment by kdahlquist** [comment]
I altered the name for this issue a little based on discussion with @mihirsamdarshi and @johnllopez616.  Currently the File > reload menu item reloads the current graph in the force graph layout, regardless of whether force graph or grid is selected.

We want to alter the meaning of this option so that if you click reload when the graph is in force graph, it reloads as force graph.  If you click reload when the graph is in grid layout, it reloads it as a grid.

Changing this would mean that the original title for this issue is moot.

The value of this is that if a user has the graph in a grid layout and starts moving nodes around and then wants to get it back into the grid, there is no way to do this now without first going through the force graph layout (or re-opening the file).

**Comment by kdahlquist** [comment]
As I review the Client Side Testing Document, I have found some other issues that have to do with this one and reloading the graph as force graph layout when it is unwanted.  Each of these actions triggers a reload, which is interpreted as a reload to force graph, even when the graph is in a grid layout:
- Changing the edge weight normalization factor (from sidebar or dropdown menu)
- Resetting the edge weight normalization factor (from sidebar or dropdown menu)
- Changing the gray edge threshold (from slider or dropdown menu)
- Showing gray edges as dashed or reverting to solid lines (from sidebar or dropdown menu)

**Comment by dondi** [comment]
This is a great example of an issue that would be easier to resolve when we have a unified model -> view -> controller cycle. Having all of these settings in a single `grnState` would allow the unified `updateApp` function to take all of them into consideration when determining how (or whether) to reload a graph.

**Comment by kdahlquist** [comment]
Yes, also, the Client Side Testing Document is also giving us a record of desired behaviors.  I'll note that Enable/Disable node coloring occurs without triggering a reload; you can click and just see the colors appear/disappear.

**Comment by kdahlquist** [comment]
- [x] Reload button should reload graph in grid configuration if that was what state it was in
- [x] Changing the edge weight normalization factor (from sidebar or dropdown menu) with a grid layout should not trigger a reload to force graph
- [x] Resetting the edge weight normalization factor (from sidebar or dropdown menu) with a grid layout should not trigger a reload to force graph
- [x] Changing the gray edge threshold (from slider or dropdown menu) with a grid layout should not trigger a reload to force graph
- [x] Showing gray edges as dashed or reverting to solid lines (from sidebar or dropdown menu) with a grid layout should not trigger a reload to force graph
- [ ] Manipulating graph manually during grid layout should change force graph layout button back to grid layout button

Since most of this is fixed in beta 3.1.12, I'm going to close this one and open an issue for the last item.
