### ISSUE TITLE
Changing gray threshold causes grid layout to go back to force graph layout

### ISSUE THREAD

**Issue by mihirsamdarshi** [dondi/GRNsight#610]
Changing gray threshold removes force graph layout

**Comment by kdahlquist** [comment]
I'm not exactly sure what @mihirsamdarshi meant by this, but if it means that the graph is no longer responding to the force graph sliders, then this also happens when selecting a expression dataset to color the nodes with.  That is, if you choose a dataset from the dropdown, the graph no longer responds to sliders.

**Comment by mihirsamdarshi** [comment]
@kdahlquist I meant that any input on the gray threshold sliders removes the force graph settings

**Comment by kdahlquist** [comment]
So, is the same thing happening with the force graph parameter sliders or is this something different?

**Comment by kdahlquist** [comment]
My issue is something different.

**Comment by kdahlquist** [comment]
Confirmed fixed in beta 3.1.10, so closing.
