### ISSUE TITLE
General Gene Page Bugs

### ISSUE THREAD

**Issue by johnllopez616** [dondi/GRNsight#638]
I wanted to create a single issue thread regarding gene page issues relating to overall functionality or visual mishaps that are prominent enough to consider a bug rather than a stylistic change. 

API Functionality:

- [x] Whenever a user clicks on a node on beta, it does not link them to the gene page. It returns a 404 error instead.
- [x] If an API call is successfully made but returns a blank string instead of data, the "Not found" string does not load.
- [x] Whenever JASPAR makes an API call to a gene that doesn't exist, it returns undefined data, causing the above error to display, but also disallowing the overall error modal to display as well.

Visual Changes:

- [x] Source links attached at the end of gene page data would protrude into the accordion tabs.
- [ ] Add default "loading" text line to parts of the page

**Comment by kdahlquist** [comment]
The "Page is loading" is an enhancement request and should get it's own issue, if the intent behind this issue is to report bugs.  I think this issue is closable, since I'm getting JASPAR data on gene pages.  If these bugs are fixed, then close this issue and open a new one with the enhancement request.
