### ISSUE TITLE
Review API for JASPAR

### ISSUE THREAD

**Issue by johnllopez616** [dondi/GRNsight#709]
Created this issue to document the results of my investigation in #698 since it seemed to, sadly, get forgotten from the rest of the APIs

**Comment by johnllopez616** [comment]
```
let getJasparInfo = function (geneSymbol) {
    return $.get({
        url: serviceRoot + "/jaspar/api/v1/matrix/?tax_id=4932&format=json&name=" + geneSymbol.toUpperCase(),
        dataType: "json",
        beforeSend: function (xhr) {
            xhr.setRequestHeader("content-type", "application/json");
        },
    }).then(function (data) {
        return (data.results.length === 0 || data.results === undefined) ? {} :
            $.get({
                url: serviceRoot + "/jaspar/api/v1/matrix/" + data.results[0].matrix_id,
                dataType: "json",
                beforeSend: function (xhr) {
                    xhr.setRequestHeader("content-type", "application/json");
                },
            });
    });
};
```

**Comment by johnllopez616** [comment]
```
  let taxon = "4932";
    return $.get({
        url: serviceRoot + "/jaspar/api/v1/matrix/?tax_id=" + taxon + "&format=json&name=" + geneSymbol.toUpperCase(),
        dataType: "json",
        beforeSend: function (xhr) {
            xhr.setRequestHeader("content-type", "application/json");
        },
    }).then(function (data) {
```
Un-hardcoding this was fairly straightforward.

**Comment by johnllopez616** [comment]
One thing to note, the taxon that returns results for the JASPAR API is different than the one for UniProt in issue #694:

Compare 559292:
![image](https://user-images.githubusercontent.com/21348600/49561793-b85eba00-f8cd-11e8-9e82-316a7586a041.png)

...to 4932:
![image](https://user-images.githubusercontent.com/21348600/49561836-e3e1a480-f8cd-11e8-8565-1360600c82ae.png)

**Comment by kdahlquist** [comment]
Well, I figured that this would come up at some point.  Taxon ID 4932 is referring to the species Saccharomyces cerevisiae, see https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=4932,
while taxon ID 559292 is a substrain of 4932, see https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=559292.

If you look at the first link, you will see that the strain S288C is included in the long list of substrains.

What is special about S288c is that it was the first strain to be sequenced completely, so it is the _reference_ genome for yeast.  However, now that many more substrains have been completely sequenced, the databases had to be able to distinguish between them.

So, in the case of our gene pages, all the data we are providing are still for the same species.  Since UniProt pre-dates the time when separate sub-strain designations were made, it still uses the parent ID, 4932.  However, JASPAR is referring to the sequenced strain.  What happens if you query UniProt with 559292?

**Comment by dondi** [comment]
#694 #697 #696 #709 updates: @johnllopez616 will work on these Wednesday and gather up the information into a definitive single source (wiki page). We can then close this and move on to #698 after.

**Comment by johnllopez616** [comment]
https://github.com/dondi/GRNsight/wiki/Web-API-Guide 

First draft of the Web API page is up!

**Comment by kdahlquist** [comment]
With the posting of the wiki page and today's discussion; this issue is closed.
