### ISSUE TITLE
Implement UI for export to xlsx

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#714]
Once @afiller1 gets up and running, she will tackle implementing a UI for the function of export to xlsx.

**Comment by afiller1** [comment]
Update: I have it so that there's an "Export to Excel Workbook" option in the Exports tab. When you click this option, an Excel workbook downloads to your computer. Currently, it tells me this workbook doesn't have data in the correct format or something along those lines, so I'm going to stop in to Dondi's office hours today to sort that out and make sure I'm using the correct functions (I'm still working on maneuvering through all of this code!).

**Comment by afiller1** [comment]
I'm at the same spot with this issue for the week because I was focused on issue #717 since that might help to fix my problem with downloading faulty Excel files.

**Comment by afiller1** [comment]
Up and functioning on my branch now. Dondi helped me figure out that Justin's code was calling the "export to graphML" function instead of the "export to Excel" function in one place, so it was exporting in an Excel workbook, but contained graphML data so it was confused and failing to open. I guess the next step is for me to submit a pull request? I haven't done that before so I'll talk through the steps with you in the meeting. @kdahlquist @dondi

**Comment by kdahlquist** [comment]
@afiller1, if you can get in touch with @mihirsamdarshi or @johnllopez616, they can guide you if you want to get the PR up before the meeting.  There is a pull request checklist on the wiki here:  https://github.com/dondi/GRNsight/wiki/Pull-Request-Checklist

Another case where we might add some additional instructions to the wiki to help newcomers to the project.

**Comment by kdahlquist** [comment]
UI is present.   Closing this, but there is some testing that will need to be done.  I will open new issues for that.
