### ISSUE TITLE
Re-review library dependencies wiki page and fix package.json versions

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#717]
Our library dependencies wiki page is due for a review (last modified January 2017). The package.json dependencies need to be cleaned up and set to fixed versions; a fresh install should be done so as to reset package-lock.json plus a round of tests should be performed.

For Node itself, we will adhere to the current LTS version.

**Comment by kdahlquist** [comment]
Related to issue #205.

**Comment by afiller1** [comment]
I cleaned up the package.json and attempted to npm install again to fix up the package-lock.json with the changes, but I had an error in trying that. It says "Unexpected end of JSON input" with a more detailed error message elsewhere on my computer that I could not elicit any significant information from (I can show you at the meeting). In any case, when I npm start, GRNsight still seems to work fine. My excel files still don't download properly, though (see issue #714 ). @kdahlquist @dondi

**Comment by johnllopez616** [comment]
@afiller1 Was it this same error?


```
npm ERR! Unexpected end of JSON input while parsing near '...1.0.0",
npm ERR!             
npm ERR! '

npm ERR! A complete log of this run can be found in:
npm ERR!     [USER].npm/_logs/2019-02-04T20_29_05_453Z-debug.log
```

**Comment by afiller1** [comment]
@johnllopez616 Yes! And when I looked in the log, I couldn't really tell what the problem was...?

**Comment by mihirsamdarshi** [comment]
Can you upload the log @afiller1 please?

**Comment by afiller1** [comment]
[2019-02-04T19_24_44_686Z-debug.log](https://github.com/dondi/GRNsight/files/2829942/2019-02-04T19_24_44_686Z-debug.log)
@mihirsamdarshi

**Comment by afiller1** [comment]
I probably need to look through all of the Verbose Stack issues and find where in the file they're located. I didn't notice the locations at first.

**Comment by mihirsamdarshi** [comment]
@afiller1 the very end of the log should give you a clue. It states that there was an unexpected end in the JSON. Scrolling up, you can see that it ends around where xmlbuilder is. I’m on my phone, or I would give you a line number but start at the end of the log for now.

**Comment by afiller1** [comment]
Ok, I worked on this for a bit and it looks to me like there's probably something of with my Node install and that's where these errors are coming from. The errors point to files on my computer that I can't open, so I'm hoping to sit down with @dondi during his office hours tomorrow and go through how to fix it (classic snag, the downloaded packages are the things causing the problems :P And I'm not too gifted with Node downloading...). Besides that, I made a draft of an updated wiki page for the libraries everyone currently has. I kept it as a draft because I want to verify that we're keeping certain versions of libraries and double check that I have the versions right. I'm attaching the file with my error message and my wiki draft, maybe we can look over them tomorrow. 
[2019-02-04T22_57_00_703Z-debug.log](https://github.com/dondi/GRNsight/files/2830190/2019-02-04T22_57_00_703Z-debug.log)
[library_updates_draft.txt](https://github.com/dondi/GRNsight/files/2830203/library_updates_draft.txt)

**Comment by dondi** [comment]
@afiller1 Have you tried a complete re-install? This involves completely wiping out the _node_modules_ folder and also _package-lock.json_. Do those and `npm install` again, and see if that helps.

Otherwise, yes, let's look in my office sometime.

**Comment by kdahlquist** [comment]
Summary of "clean room" reset:
- Uninstall node
- Reinstall the newest LTS version of node
- Delete _node_modules_ folder in GRNsight (if present)
- Delete _package-lock.json_
- Run `npm install`
- See what happens

**Comment by kdahlquist** [comment]
@johnllopez616  See if the clean room procedure ^^^^ helps you.

**Comment by johnllopez616** [comment]
Ran the "clean room" reset on my machine, then tried to run `npm run start-dev`, recieved the following error:

**Comment by johnllopez616** [comment]
Reinstalling `webpack-dev-server` resulted in the same error as above. Will investigate further into this error to try and understand what it means.

**Comment by johnllopez616** [comment]
I _possibly_ found the culprit to our dependencies issues:

Turns out we've been using a package called 'parallelshell' which has caused problems for multiple users when upgraded beyond 3.0.1. Refer to here: https://github.com/darkguy2008/parallelshell/issues/57

Our package.json had the following attribute: `    "parallelshell": "^3.0.1", `, so it was a matter of removing the little arrow, reperforming the "clean state" procedure, and 'npm run start-dev' worked as it should have!

**Comment by afiller1** [comment]
Ok I have officially updated the Wiki with the correct versions of everything. I have also removed the ^'s and ~'s from package.json.

I got `npm install` to work (finally). @johnllopez616 , here are the steps to making that happen (@dondi , correct me if I'm wrong on any of this):
1. Uninstall Node.js from your machine using the uninstaller on your computer.
2. Delete node-modules folder
3. Delete package-lock (right, Dondi?)
4. Re-download Node online (working version is LTS v10.15.1) [here](https://nodejs.org/en/download/).
5. Try out `npm install` and try to run a local version on your machine to see if it works.

@kdahlquist you can scan over the Wiki if you want.

**Comment by kdahlquist** [comment]
I added a last modified date to the wiki.  @afiller1, can you add a note about using the LTS version of node?  

So where in the documentation is there an explanation of what to do when we onboard a new team member and they run into the same kind of problem?

**Comment by afiller1** [comment]
@kdahlquist I can make a Troubleshooting page on the Wiki where we can put fix instructions to general problems. And I will add the LTS detail.

**Comment by afiller1** [comment]
Mainly worked on re-designing the Wiki this week. Restructured a little, re-labled, added Troubleshooting section and the clean house procedure page under it, in addition to the beta release procedure page under Procedures. Added other details here and there (about LTS, versions, whatnot). I can talk about it more at the meeting, and if anyone has anything else they would like to see on the Wiki, let me know. I still have a few edits to make on the new pages and some questions about various little things...I will bring it all up tomorrow.

**Comment by afiller1** [comment]
Finished the two pages I was working on (Updating Beta and NPM Troubleshooting). Wiki can be continually updated whenever we find more buggy things that would be easy to document for future users. Closing the issue now!
