### ISSUE TITLE
Apply special case handling for yeast taxon IDs

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#723]

**Comment by kdahlquist** [comment]
For yeast, Uniprot expects taxon ID 559292 for yeast, while JASPAR expects taxon ID 4932 for yeast.

We need some special handling for yeast that says when GRNsight knows that it is dealing with yeast genes, it needs to send the correct taxon ID to Uniprot and JASPAR.

Note, again, the reason for the discrepancy is that 4932 refers to Saccharomyces cerevisiae, but 559292 is for Saccharomyces cerevisiae S288c.

After #718, this seems like the next issue for @johnllopez616 to tackle because it affects our main functionality right now.

**Comment by johnllopez616** [comment]
Addressed this issue during my work session on 2/18/19. Results should be visible in the next PR.

**Comment by kdahlquist** [comment]
State which PR this is in, please.

**Comment by johnllopez616** [comment]
Should be fixed following PR #731

**Comment by dondi** [comment]
Noted and verified in pull request.
