### ISSUE TITLE
Node coloring leaves white space when there are wide nodes

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#744]
![image](https://user-images.githubusercontent.com/6463867/53981109-c7b8f380-40c6-11e9-868e-25080a929533.png)

Look at the node "YGR067C" in the lower right-hand corner of the screenshot.  You can see that it is wider than the rest because it has a wider label.  However, the part of the node that is colored is only the size of the smaller nodes.  It looks like the node coloring might not resize with the size of the nodes.  I believe there is a test workbook that has lots of different node widths.  We need to add expression data to those and test and fix this phenomenon so that node coloring extends across the whole node (and is smaller for smaller nodes).

**Comment by kdahlquist** [comment]
@dondi, I think this is the most egregious issue out of the list to be addressed next.  I changed the priority to 0.

**Comment by dondi** [comment]
Got it, will do this for the next programming task.

**Comment by dondi** [comment]
We will line this up as @Onariaginosa’s next programming task after she updates the status of the previous ones. Some things to test in order to warm up:
* Explore the limits of node names for the graph
* Explore behavior when the node name is long but made up of multiple words
* Explore behavior when the node name is long _and_ is a single word
* Finally, the bug itself: unhardcode the node coloring bounding box to use the actual bounding box of the gene node

**Comment by Onariaginosa** [comment]
I found the issue. Node coloring for all genes seems to be determined by the length of the first gene name listed, rather than the current gene.  When I listed a 12 character name first the behavior was: 
![image](https://user-images.githubusercontent.com/21343072/94315612-b436dd00-ff37-11ea-8314-9eaecfbad081.png)

When I listed the same gene second, the behavior was:
![image](https://user-images.githubusercontent.com/21343072/94315680-d3356f00-ff37-11ea-89fd-1a8057c60394.png)

**Comment by Onariaginosa** [comment]
The node coloring seems to be fixed. @Onariaginosa will do more tests to see if there are any edge cases.

**Comment by Onariaginosa** [comment]
![image](https://user-images.githubusercontent.com/21343072/94323718-c1f65d80-ff4b-11ea-9760-653ccfd40d27.png)

**Comment by kdahlquist** [comment]
confirmed fixed in beta v4.0.26
