### ISSUE TITLE
Return error when a file size is too large for GRNsight to handle

### ISSUE THREAD

**Issue by mihirsamdarshi** [dondi/GRNsight#766]
Related to issue #747. Currently, there is a limit to the size of the workbook that maybe uploaded, although I am unsure of the capability as it differs between the remote server and local server. We should determine the limit, and return an error if a file exceeds the maximum size, as well as warn the user of the max size in the import menu.

**Comment by kdahlquist** [comment]
I'm going to close #747 because we have this one.  The file that crashed the server in that issue was 5MB.

**Comment by mihirsamdarshi** [comment]
A fix is pushed to my branch. I chose an arbitrary file size of 1 MB.

**Comment by kdahlquist** [comment]
Do you know what the actual limit is?  Obviously 5MB is too big.  Just wondering.

**Comment by mihirsamdarshi** [comment]
I have no clue, 2 MB seems to be far above the upper limit for any of the files that we currently have in the testing suite and the demo files

**Comment by kdahlquist** [comment]
I think that at some point, we need to empirically test this, i.e., try uploading larger and larger files and see when it crashes.  Doing it at a time when someone is available to restart the server would be preferable.  We can't just assume that because our test suite files are of a certain size, that is the size we need.  Bear in mind that we allow 74 nodes and 99 edges as our largest graph, so we need to at least be able to accommodate that.  People might have more than 3 timepoints of expression data, too.

**Comment by kdahlquist** [comment]
I've verified that the error message appears and works.  I will close this one and open another issue with a lower priority to check on file sizes on a later date.
