### ISSUE TITLE
Clicking Set or Reset Normalization factor releases nodes that were previously moved to respond to force graph

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#770]
I discovered this while testing the normalization factor fix for #708.  While I am in force graph layout mode, if I manually move nodes around, they should then stay fixed in place unless I double-click to release them.

However, if I click the set normalization factor button, nodes that I had moved and were stationary in place, then become responsive to the force graph layout again and start moving around.  This also happens if I click the "reset" normalization factor button.  

This might happen with other features as well, but I have not tested them.

**Comment by mihirsamdarshi** [comment]
I think this would best be solved when we convert the graph.js file to an object that contains the locations of all the nodes in a centralized format. Right now, I believe this would take a little too much time to de-bug before the next release.

**Comment by kdahlquist** [comment]
OK, I'll lower the priority.

**Comment by dondi** [comment]
This does happen when other graph settings change, and showed up as a combination of the force graph vs. grid layout switch using the same coordinate values as the per-node fixed-position feature plus our streamlined MVC cycle. Unfortunately, in this particular case, the streamlined cycle worked to our disadvantage because every change to `grnState` behaved like a "reset" to force graph, which in turn cleared any previously-set fixed positioning. The potential solution I came up with was to diverge the graph layout flow slightly from the current MVC cycle. It does give special treatment to how changes to graph layout are handled, but this is necessitated by a mechanism over which we currently don’t have control, which is the way D3 tracks which nodes are fixed vs. "floating." It appears to work on my build and will be visible on the next beta.

**Comment by kdahlquist** [comment]
Verified fixed on beta 4.0.1.
