### ISSUE TITLE
Color scale bar behave strangely when small max fold change values chosen

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#773]
I am not expecting this to be fixed in the next release, but I wanted to document the behavior.

When the max log fold change value goes below 0.3, the color scale starts to behave strangely, getting asymmetrical around 0.  

Let's leave this one for later.

**Comment by kdahlquist** [comment]
Color bar has a different number of bins, depending on the scale.  Ideally, they would have the same number of bins, but just distributed across the range.

@dondi wants to know whether it's just the color bar or the node coloring that is behaving strangely.

**Comment by dondi** [comment]
Upon code inspection, this does look like just a color bar issue. The problem was that the color increment being used for calculating the gradient was held constant, regardless of the size of the max log fold change. Thus, smaller ranges yielded fewer color bins. Changing the color increment to be proportional to the size of the [–log fold change, log fold change] interval appears to fix the issue.

**Comment by kdahlquist** [comment]
The weird behaviors are not happening anymore, but now the color bar is not reflecting the colors of the nodes.  See in this screenshot, I've set the max to a low value so most of the nodes are very dark, but the corresponding dark colors are not seen on the color bar.

![image](https://user-images.githubusercontent.com/6463867/62251522-dd47f600-b3a4-11e9-9395-361fa27e066a.png)

I.e., the colors on the color bar are not changing when I change the value.

**Comment by dondi** [comment]
Oh right—I was so focused on getting the correct coloring on the sidebar that I missed making sure that the clamping was also being done on the nodes. I’ll fix that.

**Comment by dondi** [comment]
I found the issue (and committed a possible fix) but the full nature of the problem turned out to be different from initially thought. The node coloring calculation was actually correct; the issue was that my “fixing” of the gradient in the legend was the thing that was off. In trying to keep the gradient smooth, the new legend-rendering code made the gradient _too_ smooth, washing out the colors from their true range. With the legend now fixed to show the colors accurately (while retaining a smooth appearance independent of the max log fold change value), the node coloring now corresponds to the legend and the max value.

**Comment by kdahlquist** [comment]
This looks good.  A couple comments:

* When I set the scale max to "100", the legend for the bar says "100.00" because we are including 2 decimal places.  However, there is not enough space for this because the right zero is partially cut off.
* Everything looks great when the browser is 100%.  However, if I zoom the browser (not GRNsight, but Firefox) in either direction, little white lines appear in the color bar.  I don't know if this can be helped, but I thought I would mention it.

Neither of these is a deal breaker, but I'll wait to close this issue off until @dondi can comment.

**Comment by dondi** [comment]
The first item in the preceding comment has been addressed on my branch; second one turns out to be a little more involved so that is currently in progress.

**Comment by kdahlquist** [comment]
Confirmed fixed in beta 4.0.3.
