### ISSUE TITLE
Zoom not working from drop-down menu

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#778]
Zoom is not working from the drop-down menu.  I've seen a number of strange behaviors that I'm not able to necessarily track.  I'll try to be more systematic and log actions in a new comment on this issue.

**Comment by kdahlquist** [comment]
One issue is that if you load one of the demo files, and then go to zoom in the view menu, you can click the up or down arrows to change the zoom, and the number value will change.  However, it reverts back to 100 and the graph doesn't change its zoom level.

**Comment by dondi** [comment]
This required quite a bit of work, but the behavior looked right in my testing now.

Essentially, the zoom implementation was not transitioned to the cleaner MVC flow, likely because the zoom code could not be extricated from _graph.js_ easily.

However, even though the file separation was hard to do, the _actual_ MVC flow could be done, but it just had to all take place inside _graph.js_. When the zoom values and controls were placed under strict MVC, the coordination issues appeared to resolve.

**Comment by kdahlquist** [comment]
Confirmed fixed in beta 3.1.23. Closing.  I discovered a different behavior with zoom that is non-critical to fix; I will break it out in a different issue.
