### ISSUE TITLE
Displayed demo file name needs to be restored to the original behavior

### ISSUE THREAD

**Issue by mihirsamdarshi** [dondi/GRNsight#810]

**Comment by mihirsamdarshi** [comment]
Added a hack-y fix for this. @dondi let me know if I should approach this differently.

**Comment by kdahlquist** [comment]
@dondi Will look at the code and revision history to validate "hack-y fix."

**Comment by kdahlquist** [comment]
@mihirsamdarshi notes that the original issue stemmed from having a different loading routine between the two, `loadGRN` and `importGRN` (or something like that).

**Comment by mihirsamdarshi** [comment]
@dondi this is the link to the original file: https://github.com/dondi/GRNsight/blob/212de147dc33372fd60f88beee4c6435b29d50e2/web-client/public/js/setup-load-and-import-handlers.js

**Comment by kdahlquist** [comment]
Just to document what I said in the meeting yesterday,
Demos 3 and 4 follow the current expected format for GRNmap and GRNsight.
Demos 1 and 2 do not because they pre-date the format refactor in GRNmap.  Demos 1 and 2 need to be kept around for historical purposes because they are tied to the _Bulletin of Mathematical Biology_ paper.

My understanding about the demo files was that they were already converted to JSON and were loading independently of the Excel import process.

**Comment by kdahlquist** [comment]
Upon further review, the demo file functionality is kind of a mess in v4.0.8

I think whatever changes were made are loading the wrong demos for demo 1 and demo 2.  Demos 1 and 2 have node coloring expression data associated with them in master, but not in beta.  They might have been reverted to some prior versions of the files.  The filename info is wrong in beta.  It should read what is being shown in Master.

Let's get it working back to what it is doing on Master.

**Comment by kdahlquist** [comment]
Actually, no node coloring is happening in beta now. Starting another issue.

**Comment by kdahlquist** [comment]
I didn't realize that this was marked as review requested.  I think it is fixed, so closing.
