### ISSUE TITLE
@dondi will look into dependabot

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#830]
@dondi will look into dependabot to see if we can turn it off.

Or, we could just close the PR's and then have a running tally of packages that have been updated that we can check into later.

**Comment by dondi** [comment]
The opt-out for this was found in Security > Alerts. I’ve gone ahead and opted out, as well as closed the pull requests that were autogenerated by this setting.

We’ll manually do this pass as we approach release, so that versioning issues are more easily isolated and won’t get mixed up with lingering bugs.
