### ISSUE TITLE
Node detection permanently loops with buggy workbook uploaded

### ISSUE THREAD

**Issue by Kevboe** [dondi/GRNsight#849]
I encountered this error while testing my made-up workbooks with different species. They are all based on a full yeast workbook, which I changed the network and species information in. The interesting thing about the bug is that it is not triggered by a single workbook. I was able to repeat the bug, but with a different workbook each time. Furthermore, workbooks which triggered it once would work fine after a refresh. I have attached an image of what I see in the console when I encountered the bug.

![image](https://user-images.githubusercontent.com/22015530/80321528-99b6d700-87d2-11ea-9d05-63eb341f678e.png)

**Comment by kdahlquist** [comment]
So, maybe this is what crashed beta just now?  #860  I reloaded the same workbook a couple times in a row and it crashed.

I note that in the file that crashed it, "kev-fake-data-bad-species.xlsx", it looks like @Kevboe used demo 1 as the base file, retaining all of the worksheets, except changing the network and network_weights sheets to his fake 3-gene network.  Thus, the genes in the network and network_weights sheets don't match the rest of the worksheets.   

This file won't properly load in GRNsight master because of this (it gives a weird-looking network with black nodes).  This is the stuff that @Onariaginosa is working on testing, actually.

**Comment by kdahlquist** [comment]
I'm going to assign this to @Onariaginosa, with a low priority.  The problem here is a buggy workbook that we can address once she's made a first pass through all the worksheets for testing, aka #884, #883.

**Comment by Onariaginosa** [comment]
The files listed were not in the current state of the beta branch, so got the files from the beta branch when[ this commit ](https://github.com/dondi/GRNsight/commit/6868c0028a67c6850a7dcf0a57d5c55bbf8aefc7) was made. I tested with all of the species-test-data files and they all throw a long list of errors. This issue appears to have been resolved at some point.

**Comment by dondi** [comment]
It sounds like the adjustments made by @igreen1 helped with resolving this error.
