### ISSUE TITLE
Expression Database schema?

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#867]
@afiller1, is there a database schema committed somewhere for documentation?  For XMLPipeDB, we used schemaspy.  I'm not sure if that would work here, but we need that before you leave the project.

We will be adding data to the database, so an explanation of how you processed the data for the database is also needed.  Maybe a wiki page?

**Comment by afiller1** [comment]
@dondi do you think using schemaspy would be a good idea? I'm looking at the documentation and it looks like I would need to call it from within the ec2 in order to access the database properly, meaning I would have to get Masao to install the necessary pieces. I can do that, but I don't want to ask him to do it if you don't think it will work or something. The documentation I'm looking at is [here](http://schemaspy.sourceforge.net/).

**Comment by dondi** [comment]
@afiller1 It depends on the complexity of your database. The benefit of SchemaSpy is that it is automatic: it reads your schema and generates the diagram, and you're done. So this is particularly useful for large, complex schemas, and also schemas that are still changing (updating the schema diagram is then a matter of just re-running SchemaSpy).

So that is the main thing to weigh vs. drawing manually. A manual drawing is much harder for a complex, fluid schema, but if the schema is simple and stable enough, then this might trade off the effort of learning and installing SchemaSpy.

**Comment by afiller1** [comment]
Ok. The schema is decently simple, and I guess I drew it out roughly before when we were outlining the database in the first place. Perhaps I will give a shot at doing it manually.

**Comment by kdahlquist** [comment]
There might be some tools out there to make it easier to draw the manual diagram, too.  Like a template with table diagrams already in it or something.

**Comment by afiller1** [comment]
Look [here](https://github.com/dondi/GRNsight/wiki/Preparing-Data-for-Entry-into-Expression-Database) for the wiki I wrote up. Also check [here](https://github.com/dondi/GRNsight/blob/master/documents/SDF/CMSI_402/spring_2020/Alexia%20Filler/Expression%20Database%20Schema.pdf) for my database schema. Open to comments.

**Comment by kdahlquist** [comment]
The documentation looks good, thanks @afiller1!
