### ISSUE TITLE
Onboarding tasks for new team members

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#871]
We typically prefer to keep tasks very focused, but since this is a package of relatively small tasks, this time around we’re OK with collecting them together:
* Settle on a standardized work schedule during the week
   * Include some times where the entire group is available
   * Schedule work times for at least 2 hours or more in order to stay in the flow
* Add yourselves as current students to this list: https://dondi.github.io/GRNsight/people.html
    * …and “graduate” any prior students to the “Former Students” list.
* Clone, set up, and run the GitHub repository on your own computer
* Examine the presentations from recent student graduates to familiarize yourself with the latest changes to GRNsight
* Explore those new features live on your installation of the software and take note of any bugs, points that need refinement, etc.

**Comment by dondi** [comment]
Protip for @igreen1 and @luluriffic—and possibly @Onariaginosa if you haven’t seen this before: GitHub can embed checklists in comments! You can copy the Markdown source below and create a comment for yourself with this checklist, then check things off as you do them:
- [ ] Settle on a standardized work schedule during the week
   - [ ] Include some times where the entire group is available
   - [ ] Schedule work times for at least 2 hours or more in order to stay in the flow
- [ ] Add yourselves as current students to this list: https://dondi.github.io/GRNsight/people.html
    - [ ] …and “graduate” any prior students to the “Former Students” list.
- [ ] Clone, set up, and run the GitHub repository on your own computer
- [ ] Examine the presentations from recent student graduates to familiarize yourself with the latest changes to GRNsight
- [ ] Explore those new features live on your installation of the software and take note of any bugs, points that need refinement, etc.

**Comment by luluriffic** [comment]
- [ ] Settle on a standardized work schedule during the week
   - [ ] Include some times where the entire group is available
   - [ ] Schedule work times for at least 2 hours or more in order to stay in the flow
- [ ] Add yourselves as current students to this list: https://dondi.github.io/GRNsight/people.html
    - [ ] …and “graduate” any prior students to the “Former Students” list.
- [ ] Clone, set up, and run the GitHub repository on your own computer
- [ ] Examine the presentations from recent student graduates to familiarize yourself with the latest changes to GRNsight
- [ ] Explore those new features live on your installation of the software and take note of any bugs, points that need refinement, etc.

**Comment by igreen1** [comment]
Notes: 
Will be working 2-4MF on GRNSight, except this week I will work later on Friday since I have to go buy a washing machine with my roommates. (I will probably do 4-6 roughly)
Alexia/Kevin didn't have post-work presentations? Looked at their intros. I also looked at presentations from Prof. Dahlquist, which I found helpful!
From Slack: worth mentioning that NPM doesn't work well (or at all) on separate partitions. This was an issue for me and worth knowing for future Onboarding if other people have weird dual-boot setups


- [ ] Settle on a standardized work schedule during the week
   - [ ] Include some times where the entire group is available
   - [ ] Schedule work times for at least 2 hours or more in order to stay in the flow
- [ ] Add yourselves as current students to this list: https://dondi.github.io/GRNsight/people.html
    - [ ] …and “graduate” any prior students to the “Former Students” list.
- [ ] Clone, set up, and run the GitHub repository on your own computer
- [ ] Examine the presentations from recent student graduates to familiarize yourself with the latest changes to GRNsight
- [ ] Explore those new features live on your installation of the software and take note of any bugs, points that need refinement, etc.
