### ISSUE TITLE
grnsight.cs.lmu.edu server has run out of disk space

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#878]
@dondi said: During the 9/18 meeting it was discovered that the grnsight.cs.lmu.edu server had run out of disk space. A temporary measure was found by deleting certain files that the beta didn't need but @dondi will look further into this offline to see either where additional space can be reclaimed or if unavoidable, the EC2 host might need to get more disk space.

**Comment by dondi** [comment]
The beta checkout has been moved to another volume on the server that has more than 100G free, so this should give us sufficient room for a while longer.

I’ll close this one right away because there isn’t exactly an approach for “reviewing” this beyond just monitoring that missing-disk-space errors no longer occur.
