### ISSUE TITLE
Test import of GRNmap input workbooks for non-standard formatted worksheets

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#884]
Test import of GRNmap input workbooks for non-standard formatted worksheets
- optimization_parameters
- optimization_diagnostics

**Comment by Onariaginosa** [comment]
@Onariaginosa is in the middle of writing tests for these sheets.

**Comment by Onariaginosa** [comment]
@Onariaginosa completed implementation of the tests for the optimization parameters sheet, as well as wrote the tester code for them. I am also in the middle of creating tests for the optimization diagnostics sheets. @Onariaginosa intends to complete those on the 18th after her finals, so that this isn't left unfinished for next semester.

**Comment by Onariaginosa** [comment]
@Onariaginosa finally completed the optimization diagnostics sheet tests, and made sure that prior tests were not impacted.

**Comment by dondi** [comment]
Process for @ahmad00m: Take a workbook with the aforementioned sheets then modify to diverge from the format, and check for errors/warnings as a result from those changes.

**Comment by ahmad00m** [comment]
Tested the file from GRNsight/test-files/demo-files/15-genes_28-edges_db5_Dahlquist-data_estimation_output.xlsx and modified optimization_parameters and optimization_diagnostics looked for errors. No error list was shown; however, the errors were in the form of warnings. The graph was drawn unlike my expectation even though I thought the graph should have not been drawn. Moreover, the errors given were accurate and could directly be fixed from the warning list. Screen shot of the warning list is also attached.
<img width="1351" alt="Screenshot 2021-02-03 at 12 01 41 pm" src="https://user-images.githubusercontent.com/75926755/106802423-cd534700-6617-11eb-9a79-96f2f53e8af9.png">

**Comment by dondi** [comment]
These sheets are currently used only by GRNmap and do not currently affect the GRNsight visualization. From that perspective, these can be considered as warnings.

However, upon export, these should be considered as errors.

It’s looking like the approach to take is to revise messaging so that we clearly state that these files may not export properly.

**Comment by Onariaginosa** [comment]
@Onariaginosa gave @ahmad00m  a tour of the testing suite as a whole, and how to edit/create new tests. We decided to change the Warnings Intro to say that the file may not export properly if there are warnings rather than any individual warning tests because it seemed redundant to do so for every single warning message.

**Comment by dondi** [comment]
Now that this is in beta, @ahmad00m can go ahead with verification.

**Comment by ahmad00m** [comment]
@ahmad00m confirms the new message in the warning list intro, suggesting the file may not export properly if the error remains in the workbook.
