### ISSUE TITLE
GraphML and SIF imports run afoul of recent species feature

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#886]
The species feature that was worked on last year does not carry over to our GraphML and SIF import code. The underlying principle of our files is that the only true requirement is a network—everything else should be “icing on the cake” and so should not produce errors if they are missing.

For the GraphML and SIF importers, the `meta` property which contains the `species` will be missing because there is flat-out no (standard) way to introduce that value in the files. Thus, the species code that was added last year should gracefully skip itself if the `meta` property is missing.

For the default behavior, there is existing code in the workbook importer and we should investigate how to refactor GRNsight so that the existing default logic applies across all file formats.

**Comment by igreen1** [comment]
@igreen1  got the import function working by adding a manual optional (I don't believe optional chaining works in the Node we are running unfortunately). There is definitely a better way but it would require more refactoring. I will be working tonight on that but wanted to give everyone an update well before the meeting. I'd call this a working solution but not an elegant one.

However, now, there are issues with the expression dataset. Graphml doesn't have expression data, so accessing that throws errors. Most, but not all, of the attempts to access the expression property are shielded by 'if exists'. So, @igreen1  need to expand this to all accessing. This is another thing I will be working on tonight ! 

(I had a midterm Wednesday in my hardest class, so only did 2/4 of my hours. I skipped my Monday hours and will do them tonight)

**Comment by dondi** [comment]
@igreen1 has implemented a fix but needs to update the test suite since this is new behavior.

**Comment by igreen1** [comment]
When attempting the build, the test throws the following error

![image (1)](https://user-images.githubusercontent.com/40191185/98403735-ac825200-2026-11eb-8542-44c943e80a75.png)

This is because the best fix I found, following the notation of the .xslx import, requires an addition of .meta and .expression to the sif and graphml imports. However, the test is expecting a deep equality. The next goal, then, is to add this new format to the tests.

Discussed in the meeting today how to implement this fix; should be a simple paste into the expected results of two empty fields.

**Comment by igreen1** [comment]
Officially working on igreen1 commit #6abe1dd 

Fixed the test issue by adding expression and meta objects.

Also converted expression and meta imports to objects instead of arrays to more closely reflect the type of data they store.

PR is waiting for some final bug fixes on the graphML validation.

**Comment by dondi** [comment]
Clarification for @ahmad00m—SIF and GraphML used to report errors when they were loaded because they don't contain species information. This should no longer be an issue.

**Comment by ahmad00m** [comment]
Tested all test files in GRNsight/ test-files/ import-samples. The graph was drawn correctly and no error was shown for neither the SIF or GraphML formats. However, not quite sure if correct files were tested for this issue.

**Comment by dondi** [comment]
@dondi confirmed that the correct files were tested and it was also confirmed that the missing species error does not apply to SIF and GraphML.
