### ISSUE TITLE
Eliminate gray border when Restrict-to-Viewport is active

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#889]
Because of the pending changes to zoom behavior for Restrict Graph to Viewport (mentioned in #804), the gray border will no longer be applicable.

**Comment by igreen1** [comment]
Fixed in igreen1 branch, commit f64bc456d151696d2f6262b93c4859652d5f0b79

The 'stroke' of the border was changed. The reliance on `adaptive` was removed and instead only `none` is in place now

Former:
https://github.com/dondi/GRNsight/blob/8a9eeb9b3642253cfdec31d2dece1b25af0fca6a/web-client/public/js/graph.js#L230-L232

New: 
https://github.com/dondi/GRNsight/blob/f64bc456d151696d2f6262b93c4859652d5f0b79/web-client/public/js/graph.js#L230-L232

However, I don't know if #804 was ever finished. As it stands, the bounding box is still present, merely hidden.

**Comment by igreen1** [comment]
The fix mentioned above is once again implemented. However, @igreen1 feels it may actually make it harder to use the software

**Comment by igreen1** [comment]
The issue appears out-of-date as now the restrict graph functionality removes the ability to use the zoom controls. See #804 for a more complete update

**Comment by dondi** [comment]
Closing since this issue no longer applies given what is coming in #804.
