### ISSUE TITLE
Refactor network parsing/error-checking to match structure for expression and miscellaneous data

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#890]
The existing spreadsheet controller code needs to be restructured so that network parsing is a "peer" of all other parsing routines.

**Comment by dondi** [comment]
@Onariaginosa will leave some links for @dondi to indicate the “before” and “after” states of the code in terms of this refactor-in-progress.

**Comment by Onariaginosa** [comment]
@dondi, @Onariaginosa finally fixed the Onariaginosa branch so that it is working as intended before the refactor. The Onariaginosa_refactor branch is the one where the refactor in progress is going. Sorry it took so long I kept on running into errors because I edited a test file, and libreOfficeCalc does not have the same column capacity as Excel, so it threw an error because data was lost.

**Comment by kdahlquist** [comment]
@Onariaginosa, I'm worried that the use of libreOfficeCalc might introduce more differences than even the issue you encountered.  Microsoft Office 365 is free for LMU students:

"You'll need to use firstname.lastname@lmu.edu when first prompted to login, then your MyLMU credentials when asked to authenticate.

For detailed, step-by-step instructions on how to download Office 365 on your personal devices, click Download Office 365 for personal devices. https://its.lmu.edu/media/its/Office%202016%20download%20home.pdf"

**Comment by Onariaginosa** [comment]
@kdahlquist Microsoft Office 365 is not available on Linux machines. They only offer Microsoft Teams so far. I tried using the online version, but it didn't let me open the workbook. Should I try to install it on a virtual machine?

**Comment by dondi** [comment]
No regressions seen in the tests and the final code structure looks good. Workbooks with expected errors/warnings showed the corresponding messages when opened in GRNsight.
