### ISSUE TITLE
Node colouring dropdown not properly checking/unchecking

### ISSUE THREAD

**Issue by igreen1** [dondi/GRNsight#906]
From the Node dropdown menu, when 'Enable Node Coloring' is selected, the selection will remain checked, despite Node Coloring turning off. The sidebar 'Enable Node Coloring' will also remain checked. However, selecting the 'Enable Node Color' on the sidebar will properly update the checked state.

It appears then, that the 'checked' property is not properly updated when using Dropdown menu: Node -> Enable Node Coloring. 

The dropdown looks like this regardless of state/input/graph:
![image](https://user-images.githubusercontent.com/40191185/106072909-e6ab3f00-60bd-11eb-83a4-6c6e9c50b18d.png)

**Comment by mihirsamdarshi** [comment]
This issue has to do with [Lines 655 - 776 in update-app.js](https://github.com/dondi/GRNsight/blob/c7ef42057498fdf8af71ab487dbaff855bfb9b26/web-client/public/js/update-app.js#L659-L776). 

Unfortunately, it seems that that chunk of code isn't really following the MVC architecture that was setup, as the state of the checkboxes are being read inside update-app, instead of setup-handlers. An example can be seen [here] (https://github.com/dondi/GRNsight/blob/c7ef42057498fdf8af71ab487dbaff855bfb9b26/web-client/public/js/update-app.js#L670). I am working on a fix, but it does involve some refactoring of the expression data work, which I am unfamiliar with, as of right now.

**Comment by mihirsamdarshi** [comment]
This issue has to do with Lines 655 - 776 in update-app.js

https://github.com/dondi/GRNsight/blob/c7ef42057498fdf8af71ab487dbaff855bfb9b26/web-client/public/js/update-app.js#L659-L776

Unfortunately, it seems that that chunk of code isn't really following the MVC architecture that was setup, as the state of the checkboxes are being read inside update-app, instead of setup-handlers. An example can be seen here: 

https://github.com/dondi/GRNsight/blob/c7ef42057498fdf8af71ab487dbaff855bfb9b26/web-client/public/js/update-app.js#L670

I also have a couple questions about the variable `expressionDBdesired`? it kind of just exists, and I was wondering if it served any purpose?
https://github.com/dondi/GRNsight/blob/c7ef42057498fdf8af71ab487dbaff855bfb9b26/web-client/public/js/update-app.js#L96
https://github.com/dondi/GRNsight/blob/c7ef42057498fdf8af71ab487dbaff855bfb9b26/web-client/public/js/update-app.js#L656
https://github.com/dondi/GRNsight/blob/c7ef42057498fdf8af71ab487dbaff855bfb9b26/web-client/public/js/update-app.js#L658

**Comment by dondi** [comment]
Merged and now on beta; @ahmad00m can verify.

**Comment by ahmad00m** [comment]
@ahmad00m tested the updated version and it worked perfectly fine. The 'checked' property is updated every time it is checked/unchecked .
