### ISSUE TITLE
Web App Doesn't Update Correctly After Loading The Bottom Dataset First Then The Top Dataset

### ISSUE THREAD

**Issue by Onariaginosa** [dondi/GRNsight#941]
If you load the bottom dataset 1st the website looks like it doesn't load, however, the network request comes back alright.

**Comment by dondi** [comment]
@dondi and @Onariaginosa did a deep dive into this bug and were able to implement a fix. It involved removing some conditions that were there before, and the reason for those conditions remains a side puzzle for now because we couldn’t work out why those were necessary in the first place. We even followed the history of the code back a few commits but that didn’t help.

Perhaps regression/QA testing will reveal the reason eventually. But for now, in our immediate testing, removing those conditions appears to fix the bug.
