### ISSUE TITLE
Fit to window causes the graph to shrink to one node 

### ISSUE THREAD

**Issue by ahmad00m** [dondi/GRNsight#945]
When fit to window option from the setting is chosen, the graph shrinks down to one node but it appears that reselecting another view size causes the graph to go back to normal.
<img width="966" alt="Screenshot 2021-12-09 at 4 36 16 pm 2" src="https://user-images.githubusercontent.com/75926755/145497486-a82d3631-803a-4a31-b075-290aa067655a.png">

**Comment by dondi** [comment]
This one will need some prior reading on the D3 library. The classic starter is the [“Three Circles” article](https://bost.ocks.org/mike/circles/). It also appears that D3 has updated its [introductory page](https://observablehq.com/@d3/learn-d3) in the interim

**Comment by Sarronnn** [comment]
Could not get the graph to show up: do I need to upload a gene sequence? 
- Looked at developers tool: Error message showed 
  "Failed to load resource: the server responded with a status of 404 (Not Found)"
  " DevTools failed to load source-map"

**Comment by kdahlquist** [comment]
You should be able to reproduce this just by loading the demo files under the demo menu.

**Comment by Sarronnn** [comment]
I tried the files under demo:
- The graph does not show up on the **local** GRNsight, but it does on the actual one .

**Comment by Sarronnn** [comment]
And what is a D3 scale=> A function; calling it returns the visual value (such as an x-position) corresponding to the given abstract value (such as a count).
![Screenshot (48)](https://user-images.githubusercontent.com/89826597/159205129-38f8e04a-1301-4069-8ce5-d08a8a8483fe.png)
Under graph.js: 
Am I looking at the correct function?
if so: 
From _Thre Little Circles_ :
- _- With a selection, we can make various changes to selected elements. For example, we might change the fill color using [selection.style] and the radius using [selection.attr]
- - circle.style("fill", "steelblue");
- - circle.attr("r", 30);_
Questions:
-  _.attr("height", $(".grnsight-container").hasClass(VIEWPORT_FIT) ? newHeight : newHeight);_ : what does this line of code do?
- Still do not understand _adaptive_? 
- viewport class?

**Comment by dondi** [comment]
@Sarronnn if you have any updates on this since last time, please post when you can, thanks!

**Comment by Sarronnn** [comment]
**Currently**: Trying to understand what code is saying. 
// Subtract 1 from SVG height if we are fitting to window so as to prevent scrollbars from showing up
       // Is inconsistent, but I'm tired of fighting with it...
 d3.select("svg").attr("width", newWidth)
            .attr("height", $(".grnsight-container").hasClass(VIEWPORT_FIT) ? newHeight : newHeight);
        d3.select("rect").attr("width", width).attr("height", height);
        d3.select(".boundingBox").attr("width", width).attr("height", height);

**Question**: Am I looking in the correct place? Searched the key word "fit to window" and this line of code showed up. But I'm not sure if this part of the code deals with fitting the graph to the window because the comment above it says something about scrollbars.

**Comment by Sarronnn** [comment]
This seems to no longer be an issue. When the "fit to window" setting is selected, the graph shrinks to fit the window, i.e it no longer shrinks to just one node.
<img width="1440" alt="Screen Shot 2022-11-30 at 8 59 19 AM" src="https://user-images.githubusercontent.com/89826597/204860690-aa6fe697-c302-4a8e-ac88-5e95256fbb01.png">

**Comment by dondi** [comment]
Interesting—we can verify this upon the next deployment to `beta`

**Comment by dondi** [comment]
Unfortunately, on beta v6.0.3, I was still able to replicate this behavior 😔

**Comment by kdahlquist** [comment]
@Sarronnn will check to see if this is replicable as part of #1012

**Comment by Sarronnn** [comment]
- I was not able to replicate this bug on my branch.
- But the bug is replicable on beta v6.0.3.
Here is my version: 
<img width="1333" alt="Screen Shot 2023-01-21 at 3 37 43 PM" src="https://user-images.githubusercontent.com/89826597/213894372-e50e27c6-6f68-4409-a49c-5f1a24943be9.png">

Here is beta v6.0.3:
<img width="1333" alt="Screen Shot 2023-01-21 at 3 44 03 PM" src="https://user-images.githubusercontent.com/89826597/213894379-82e5480d-6125-4880-88c8-7cb2f60f8b66.png">

**Comment by dondi** [comment]
This may need more triage—vary various conditions, log/journal specific sequences of actions (so you know not to repeat yourself)…discrepancy is confirmed by @Onariaginosa

**Comment by Sarronnn** [comment]
<b id="docs-internal-guid-63cc5e9a-7fff-59c0-58f2-8012daeca4d9" style="font-style: normal; font-variant-caps: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-weight: normal;"><div dir="ltr" align="left" style="margin-left: 0pt;">

On my machine | On Beta
-- | --
Reload → pick demo → fit to windowBug isn’t replicable | Reload → pick demo → fit to windowBug is replicable
Reload → fit to window → pick demoBug isn’t replicable | Reload → fit to window → pick demoBug isn’t replicable
Reload → pick demo → large view → fit to windowBug isn’t replicable | Reload → pick demo → large view → fit to windowBug is replicable
Reload → pick demo → small view → fit to windowBug isn’t replicable | Reload → pick demo → small view → fit to windowBug is replicable
Change demos as fit to window is checkedBug isn’t replicable | Change demos as fit to window is checkedThe now loaded graph is not shrinking

</div><br><ul style="margin-top: 0px; margin-bottom: 0px; padding-inline-start: 48px;"><li dir="ltr" aria-level="1" style="list-style-type: disc; font-size: 11pt; font-family: Arial; color: rgb(0, 0, 0); background-color: transparent; font-weight: 400; font-style: normal; font-variant-ligatures: normal; font-variant-numeric: normal; font-variant-caps: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-position: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><p dir="ltr" role="presentation" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: rgb(0, 0, 0); background-color: transparent; font-weight: 400; font-style: normal; font-variant-ligatures: normal; font-variant-numeric: normal; font-variant-caps: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-position: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Conclusions =&gt; </span></p></li><ul style="margin-top: 0px; margin-bottom: 0px; padding-inline-start: 48px;"><li dir="ltr" aria-level="2" style="list-style-type: circle; font-size: 11pt; font-family: Arial; color: rgb(0, 0, 0); background-color: transparent; font-weight: 400; font-style: normal; font-variant-ligatures: normal; font-variant-numeric: normal; font-variant-caps: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-position: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><p dir="ltr" role="presentation" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: rgb(0, 0, 0); background-color: transparent; font-weight: 400; font-style: normal; font-variant-ligatures: normal; font-variant-numeric: normal; font-variant-caps: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-position: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">The bug is replicable on beta only. Could not replicate bug on my branch; at least not in the possible checks that I have tried. </span></p></li><li dir="ltr" aria-level="2" style="list-style-type: circle; font-size: 11pt; font-family: Arial; color: rgb(0, 0, 0); background-color: transparent; font-weight: 400; font-style: normal; font-variant-ligatures: normal; font-variant-numeric: normal; font-variant-caps: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-position: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><p dir="ltr" role="presentation" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: rgb(0, 0, 0); background-color: transparent; font-weight: 400; font-style: normal; font-variant-ligatures: normal; font-variant-numeric: normal; font-variant-caps: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-variant-position: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Looks like if we check “fit to window” first, before loading a demo, then proceed to load demo, the bug is not replicable. </span></p></li></ul></ul></b>

**Comment by kdahlquist** [comment]
Hypothesis:
- when we do npm install today, we get a separate set of libraries than have been sitting on the server
- @dondi will download from server so a comparison can be made
- If file isn't too large, zipped, will post to issue, otherwise post on slack
- move current node modules elsewhere and then replace the folder with the downloaded on and see if the bug can then be replicated
- d3 library is a suspect

**Comment by kdahlquist** [comment]
Could also investigate whether being embedded in the website has an effect.

**Comment by dondi** [comment]
Total size: 321M, compressed is ~80M

GitHub issues will only accept a 25M maximum, so this has been placed in the Box GRNsight folder: https://lmu.app.box.com/folder/100940731183 (_node_modules_beta.zip_)

@Sarronnn ☝🏽 (or anyone else who is interested in trying, for that matter)

**Comment by Sarronnn** [comment]
- Downloaded zip file of beta's node module
-Moved current node modules elsewhere and then replaced the folder with the downloaded one. 
- Could not do npm run start-dev
 
<img width="814" alt="Screenshot 2023-02-21 at 9 49 46 PM" src="https://user-images.githubusercontent.com/89826597/220539086-844e17f9-e609-4451-9d23-e165823df5af.png">
- Another issue I ran into: When trying to "Load from database", the network source has a default selection of "undefined: 2022-09-24"; and I can't seem to change this. 
- I deleted package lock and change the pg in the package.json file to 8.0.3; but the issue still persists. 
- Node version is 14.21.2
<img width="822" alt="Screenshot 2023-02-21 at 10 20 30 PM" src="https://user-images.githubusercontent.com/89826597/220539226-8b16282b-c325-468f-afbc-9685f8ad7d55.png">

**Comment by kdahlquist** [comment]
To clear the undefined bug, pull from @Onariaginosa 's branch.

@Sarronnn and @dondi will meet to work on the npm run start-dev issue in office hours.

**Comment by Sarronnn** [comment]
Theory about the error:
     - Coordinates? => Issue with the coordinates that are used to define the path
             - No,because both beta & my branch have the same d3 network
    - Discussed with Dondi:
             - Issue could be because of Node version difference
                   - Our server is on Node 10, and I am on Node 14 (Can't go lower)

**Comment by dondi** [comment]
It turns out that @Onariaginosa can run Node 10, so she will see if the bug replicates locally for her

**Comment by dondi** [comment]
@Sarronnn see if the bug can be reproduced on the Lambda installation: https://2dz4kdk52j37d7xhm6cwi4u4wq0ydwdv.lambda-url.us-east-1.on.aws

**Comment by Sarronnn** [comment]
Bug cannot be produced on the Lambda Installation. Although, the whole window seemed to be buggy..
<img width="1395" alt="Screenshot 2023-03-22 at 10 39 45 AM" src="https://user-images.githubusercontent.com/89826597/226991355-0313f131-5b25-4f8b-9015-8224d72ca100.png">

**Comment by dondi** [comment]
Based on these findings, it looks like the root cause is the specific dependency versions that are installed when running a version of Node that is too old

This will be a non-factor going forward due to our ability to use newer versions of Node via the Lambda approach
