### ISSUE TITLE
Create and run GRNmap input workbooks with all Yeastract and SGD networks

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#959]
1. Load Apweiler data into PostgreSQL
2. Export the Apweiler data into an Excel workbook
3. Run the Excel workbook on @kdahlquist’s research lab MATLAB installation

**Comment by kdahlquist** [comment]
@ahmad00m, I am trying to run your input workbooks on GRNmap and have encountered the following issues so far:
- inputWorkbook_SGD_profile2.xlsx
    - "network" worksheet needs to have all lowercase in the sheet name
    - "network_optimized_weights" needs to be called "network_weights".  The "network_optimized_weights" sheet gets made in the output file.
    - The adjacency matrix for the "networ" and "network_weights" sheet needs to be identical and they are not.

**Comment by kdahlquist** [comment]
I was able to get the YEASTRACT network input workbook to run with the changes noted above.  I also changed the order of the worksheets.

GRNmap can handle duplicate data, so I think we should also create input workbooks that don't have the averages, but have the duplicate datapoints.  Also, I think we need to run it only up to the 110 datapoint.  It looks like the cells have reached steady state by then (or even by 60 min) and I think GRNmap is having a problem modeling the initial timepoints because it goes out so long.  We'll need to investigate the results of the model further.


[YEASTRACT_network_results.zip](https://github.com/dondi/GRNsight/files/8358902/YEASTRACT_network_results.zip)

**Comment by ahmad00m** [comment]
Thank you for running GRNmap and notes regarding the input workbooks, I will make sure to correct that for other workbooks. I will start making the input workbooks for the the duplicate datapoints. I will exclude the data for 150 and 300 minute timepoints. Also, I have some time to run GRNmap on the new workbooks tomorrow if @kdahlquist is available any time after 11:10 am to let me into the lab.

**Comment by dondi** [comment]
Goal is to accomplish some runs, particularly to put some preliminary data for the WCBSURC poster #963

**Comment by ahmad00m** [comment]
I was able to run GRNmap on two of the profiles, but I could not run it on all of them because it was taking a little bit too long but if @kdahlquist is available later in the week to let me into the lab I would be happy to run GRNmap on the remaining input workbooks.

**Comment by kdahlquist** [comment]
@ahmad00m , I am going to request card-key access for you to my lab so you can get in on your own.  I don't know how long it will take to process, though.  Also, any biology faculty/staff member can let you in if I'm not around.  Tomorrow I'm around all day if all you need is for me to let you in.  Thursday is a university holiday I won't be in the office.

**Comment by ahmad00m** [comment]
I finished running GRNmap on all the input workbooks containing the duplicate timepoints. I was wondering whether I should push the results to [DahlquistLab](https://github.com/kdahlquist/DahlquistLab)/data/ and create a folder for the input workbooks.

**Comment by kdahlquist** [comment]
@ahmad00m, yes please go ahead and do that.  Take a look around at the repository to see the conventions we use for naming data files and organizing them in the directories.  You'll want to save both the input and all the output files (zipped together is a good way to do that).  We try to make a list in a readme that gives the details of the runs.  Like I said, check out some of the other directories to see how we did it.

**Comment by dondi** [comment]
For the purposes of the WCBSURC poster, @ahmad00m can generate screenshots based on loading the output files indicating the calculated weights. Grid layout can make for easier comparison but the highlight would be the weights computed by GRNmap. A draft of the poster will then be made available for final review. Some questions came up on what next steps to mention and @dondi provided a general direction but will need to defer to @kdahlquist for specifics

**Comment by dondi** [comment]
@bengfitzpatrick was able to look at the initial results and provided @ahmad00m with some pointers and observations. Questions arose about what’s happening at time 0, and @ahmad00m will send the publication to @bengfitzpatrick for further examination of the precise experimental conditions

**Comment by ahmad00m** [comment]
@ahmad00m met with Dr. Fitzpatrick and he suggested to create the graphs for the expression data at each timepoint to better grasp what happened at zero timepoints and indicate what our next move would be. Here are the scatter plots created for each timepoints. Moreover, he suggested to contact the authors of the paper to understand how the experiment was conducted, because the paper suggests that the expression data at each timepoints is the average of the four replicate mutant to average of all WT’s. I’m kind of confused about what I have to do and I understand that @kdahlquist is busy but I would appreciate it if Dr. Dahlquist got a chance to take a look at the comments and guide me towards the steps I need to take.
The graphs suggest a positive slope at all timepoints except for timepoints 0. I believe we expect to see a flat line centered around zero at timepoint 0 but we see a negative slope which suggests otherwise. So, I was wondering what my next move would be considering the following information.

<img width="834" alt="Screen Shot 2022-04-16 at 12 40 18 PM" src="https://user-images.githubusercontent.com/75926755/163689248-17bdd9fb-fbf2-4605-bd9f-18fadb7f0e8b.png">

**Comment by kdahlquist** [comment]
@ahmad00m, what are the x and y axes of these plots?  I'll be able to come to the meeting on Monday and will try to review the paper again ahead of time so we can talk about the experimental design.

**Comment by ahmad00m** [comment]
The x and y axis are the gene expression of the duplicates at each timepoints (the x axis is the first duplicate and the y axis is the second duplicates).

**Comment by kdahlquist** [comment]
OK, thanks.  Let me think about it.

**Comment by dondi** [comment]
After discussing the t0 aspect, we’ve concluded that the best next step is to summarize and document the work so far, as a record for posterity. That way if we pick this up later, we can reference that document to refresh our memory on where things left off

**Comment by ahmad00m** [comment]
The [Documentation](https://github.com/dondi/GRNsight-archive/blob/main/documents/Apweiler-2012-data/Scripts/Documentation.md) has been updated. However, it doesn't yet reflect the steps taken to run GRNmap on input workbooks. Also, the step of getting the regulation matrices from sgd database needs to be updated because @Onariaginosa helped me get those from the database. I hope to finish it completely by the end of this week.

**Comment by dondi** [comment]
We’re looking to finish this work slightly past the semester; @ahmad00m will meet with @kdahlquist at the end of the week to resolve the issue with lab computer access

**Comment by dondi** [comment]
@ahmad00m also asked about a summary document describing the overall work and that sounds like a good idea

**Comment by kdahlquist** [comment]
@ahmad00m, is there anywhere I can access the Apweiler dataset with all the genes and expression data?  not just the GRNmap input/output files, but the whole dataset with duplicates removed so I can make my own input workbooks?

**Comment by ahmad00m** [comment]
Yes I believe I have them on my computer but unfortunately I don’t have access to my computer now. I will send it to you when I get back home which will be in around 3 or 4 days.

**Comment by ahmad00m** [comment]
Sorry for the delay. Here is the file with the genes and expression data that I ran on STEM.
[uniqueID's.txt](https://github.com/dondi/GRNsight/files/9348338/Unique_systematic_ID.copy.txt)
