### ISSUE TITLE
Clarifying Load from Database modal

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#982]
![Load-from-Database-modal_v6 0 0](https://user-images.githubusercontent.com/6463867/188977234-599b3773-f13f-4363-94c3-5dd6db462c6e.jpg)

**Comment by Onariaginosa** [comment]
2. I will make that change, and shorten the source name. Should I shorten the source name within the database, or create logic to display a limited amount of characters of the source and the timestamp.
3. The warning is if someone chooses something different from the dropdown, it will erase the genes they have searched for already. I wasn't intending to warn that their previously loaded network will go away, because that seemed kinda self explanatory (the network is the first step in the user pipeline, but maybe that isn't clear)

I will change the other comments as requested, and send screenshots for confirmation

**Comment by Onariaginosa** [comment]
I implemented changes 1, 4, 5, 6, and 7. Waiting for feedback before I implement changes 2 and 3.
![Screenshot from 2022-11-09 10-10-13](https://user-images.githubusercontent.com/21343072/200919369-2b534bc1-1960-4e36-9663-560e459bcdef.png)

**Comment by dondi** [comment]
We can do this in the database but we should define a new `display_name` column that we will switch to when displaying a source to the user. This will avoid cascading changes due to reference key constraints and will allow more freedom in customizing how we list a source
